### ISSUE TITLE
Receiving the following error

### ISSUE THREAD

**Issue by Dartterious** [lstein/stable-diffusion#10]
My knowledge of coding is nil. But I can follow instructions. It should be working as far as I can tell. Please help! 

Thanks in advance!
![2022-08-20 17_09_31-Anaconda Prompt (Miniconda)](https://user-images.githubusercontent.com/109719059/185738190-84028e10-4e2d-4938-8d1f-83d819547616.jpg)

**Comment by Dartterious** [comment]
Oh, sorry. important bit of information I am using the old leaked SD model and assumed if the final names were the same there wouldn't be an issue. This obviously, could be the issue.

**Comment by lstein** [comment]
Is it possible you’re using the config file for one model and are trying to load the weights for another? If you are using the leaked weights then be sure to use the stable-diffusion-v1 YAML file.

**Comment by KnobleSavage** [comment]
Hey, I'm getting EXACTLY the same result... I'm not sure I follow what you're saying the solution is.  I'm using the model.ckpt linked   in the readme.md here.  Mainly I'm just trying to get prepared so that I can drop in the proper model that hopefully drops tomorrow.

**Comment by lstein** [comment]
Thanks for picking that up! I have fixed the README.
