### ISSUE TITLE
GFPGAN tries to run even when I don't specify --gfpgan

### ISSUE THREAD

**Issue by Cubox** [lstein/stable-diffusion#100]
When running dream.py, on each image generated, I get the following message:
`GFPGAN not initialized, it must be loaded via the --gfpgan argument█████████████████████| 50/50 [00:07<00:00,  6.74it/s]`

And when running dream_web.py, I get 
```
Request to generate with prompt: test
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.04it/s]
Error running GFPGAN - Your image was not enhanced.█████████████████████████████████████| 50/50 [00:09<00:00,  5.27it/s]
'>' not supported between instances of 'NoneType' and 'int'
Sampling: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.62s/it]
```

I assume this isn't the intended behaviour, unless I explicitly call for GFPGAN, I don't want to try to run it/initialize it

Thanks for the work on this

**Comment by Oceanswave** [comment]
Thanks for the bug report! Yes, the default strength is unintentionally not None

**Comment by lstein** [comment]
This was fixed by Oceanswave's PR just above. Enter the stable-diffusion directory, do a "git pull", and possibly run "conda env update -f environment.yaml" if it doesn't work at first.

Feel free to enter a new Issue if it recurs.
