### ISSUE TITLE
GFPGAN model not found at path ../GFPGAN

### ISSUE THREAD

**Issue by smirnov-mv** [lstein/stable-diffusion#104]
**environment:** windows 10
**error description:** When i run command `python scripts/dream.py --gfpgan`, i get this error
```
* --gfpgan was specified, loading gfpgan...
Error loading GFPGAN:
Traceback (most recent call last):
  File "scripts/dream.py", line 89, in main
    raise Exception(
Exception: GFPGAN model not found at path ../GFPGAN\experiments/pretrained_models/GFPGANv1.3.pth
```

Seems like it's wrong path parameters in dream.py.

So i manually write parameters as:
`python scripts/dream.py --gfpgan --gfpgan_dir ./GFPGAN --gfpgan_model_path ./experiments/pretrained_models/GFPGANv1.3.pth`

**Comment by blessedcoolant** [comment]
Is your GFPGAN folder in the root folder of Stable Diffusion? That's where your path suggests it is. So make sure the path is correct.

**Comment by smirnov-mv** [comment]
> Is your GFPGAN folder in the root folder of Stable Diffusion? That's where your path suggests it is. So make sure the path is correct.
Yes, GFPGAN folder in the root folder of Stable Diffusion. 

```
(ldm) PS C:\sd\stable-diffusion> ls

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23.08.2022     11:52                assets
d-----        23.08.2022     11:52                configs
d-----        23.08.2022     11:52                data
d-----        26.08.2022      5:09                flagged
d-----        26.08.2022     13:46                GFPGAN
```

**Comment by mariusberget92** [comment]
+1 on this one. Checked that the GFPGAN is installed in the root folder for stable-diffusion. Might be some weird stuff with the mixed back and forward slashes `../###\###/`. Don't know for sure.

**Comment by Oceanswave** [comment]
The intent is that GFPGAN is in a sibling to stable-diffusion

e.g.

```
src\
      stable-diffusion\
      GFPGAN\
```

basically so if one clones GFPGAN from the parent folder of stable-diffusion it works by default.

e.g. if you're contributing to stable diffusion it's not cluttering up your commits, but also if you're not wanting to use GFPGAN at all it's not pulled as a dependency...

**Comment by smirnov-mv** [comment]
@Oceanswave, thank you! This moment wasn't clear for me in readme. Now i moved GFPGAN directory and all works well. Then i close issue.
