### ISSUE TITLE
Allow --grid argument to dream.py

### ISSUE THREAD

**Issue by Cubox** [lstein/stable-diffusion#106]
Hi,

I'd love the ability to give dream.py a -g or --grid option, so that all my prompts will be generated with a grid by default, with then the ability to use -i on specific prompts to override the grid.

Thanks!

**Comment by lstein** [comment]
Sure. I will do that after working more on the CFPGAN integration.

**Comment by Cubox** [comment]
@lstein After some thinking, it looks like it would be even better to change this issue into more of allowing every parameter to have a default set on dream.py instance.

When I populate a file with prompts, I want to set a default flag for all of them, without having to add it to each line. Being able to call dream.py with -n 10 -s250 -g -U 2 -G 0.5 and have it use those as defaults (unless overwritten inside each prompt) would be great
I know -n already exists.
