### ISSUE TITLE
ModuleNotFoundError when python ./scripts/dream.py or python scripts/dream_web.py

### ISSUE THREAD

**Issue by mohammedalsayegh** [lstein/stable-diffusion#109]
During "python ./scripts/dream.py" or python scripts/dream_web.py, the fallowing ModuleNotFoundError occurred 

```
(ldm) red@yellow:/mnt/c/stable-diffusion$  python ./scripts/dream.py
Traceback (most recent call last):
  File "./scripts/dream.py", line 10, in <module>
    import ldm.dream.readline
ModuleNotFoundError: No module named 'ldm'
```

```
(ldm) red@yellow:/mnt/c/stable-diffusion$ python scripts/dream_web.py
Loading model...
Traceback (most recent call last):
  File "scripts/dream_web.py", line 9, in <module>
    from ldm.simplet2i import T2I
ModuleNotFoundError: No module named 'ldm'
```
WSL and Windows produced the same error in a conda built environment. The model.ckpt placed in "stable-diffusion\models\ldm\stable-diffusion-v1".

**Comment by mohammedalsayegh** [comment]
The issue resolve by recreate conda environment

**Comment by shinya7y** [comment]
I encountered the same issue. It will be kind to add the following instruction to README.md or FAQ.

If you reuse the `ldm` environment of `CompVis/stable-diffusion` by installing additional requirements, don't forget to run

```shell
pip uninstall latent-diffusion  # uninstall CompVis/stable-diffusion
pip install -e .  # install lstein/stable-diffusion
```
