### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

### ISSUE THREAD

**Issue by wasyleque** [lstein/stable-diffusion#111]
(ldm) piotr@piotr-GA-78LMT-S2:~/Documents/wow/stable-diffusion-main$ python3 scripts/dream.py 
Traceback (most recent call last):
  File "scripts/dream.py", line 10, in <module>
    import ldm.dream.readline
  File "/home/piotr/anaconda3/envs/ldm/lib/python3.8/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

**Comment by lstein** [comment]
Which branch are you using? There's no such call anywhere in "main".

**Comment by BlueAmulet** [comment]
They've accidentally installed the ldm package on pypi.

**Comment by wasyleque** [comment]
I tried, but after ` pip uninstall ldm` 
Another error
`(base) piotr@piotr-GA-78LMT-S2:~/Documents/wow/stable-diffusion-main$ python3 scripts/dream.py 
Traceback (most recent call last):
  File "/home/piotr/Documents/wow/stable-diffusion-main/scripts/dream.py", line 10, in <module>
    import ldm.dream.readline
ModuleNotFoundError: No module named 'ldm'
`

**Comment by wasyleque** [comment]
OK, getting another SSD and will make a clean install, so if I understood what are the steps ?
I don`t need to install stable diffusion or getting anything from net (models, weights) ?
I just run 
`python3 ./scripts/dream.py `
and everything should be fine ?

**Comment by tildebyte** [comment]
@wasyleque; You'll need to start from step `conda env create -f environment.yaml` of the README.
