### ISSUE TITLE
Web Interface: No option for the --strength parameter when using img2img

### ISSUE THREAD

**Issue by namion** [lstein/stable-diffusion#134]
The web interface has no UI element for adjusting the --strength parameter when using img2img. I feel like this is a critical parameter for img2img.  It can still be passed in the prompt, but for consistency sake, I believe this should be included in the UI.

Thank you

**Comment by 1blackbar** [comment]
also buttons to load previosu/next image in folder would speed up workflow a lot.

**Comment by theRolento** [comment]
I second this, the `--strength -f` parameter should be integrated in the web interface
