### ISSUE TITLE
Feature request: adding BSRGAN as optional image upscaler

### ISSUE THREAD

**Issue by mariusberget92** [lstein/stable-diffusion#135]
Feature request: adding [BSRGAN ](https://github.com/cszn/BSRGAN) in addition to the already added realESRGAN

I don't know if this is possible. But for me it looks like [BSRGAN](https://github.com/cszn/BSRGAN) does upscaling better than realESRGAN for some reason, even though realESRGAN should be preserving details pretty good.

**Comment by lstein** [comment]
I don't see why this shouldn't be possible, particularly if BSRGAN uses a similar API to realESRGAN. i'm looping in @blessedcoolant, since he did most of the work on upscaling.
