### ISSUE TITLE
os.path.append('.') is causing error on linux

### ISSUE THREAD

**Issue by bmaltais** [lstein/stable-diffusion#14]
```bash
(ldm2) bernard@DESKTOP-4M9DSE4:~/stable-diffusion-cli$ python3 scripts/dream.py
posix
* Initializing, be patient...

Traceback (most recent call last):
  File "scripts/dream.py", line 279, in <module>
    main()
  File "scripts/dream.py", line 39, in main
    os.path.append('.')
AttributeError: module 'posixpath' has no attribute 'append'
```

Commenting line 37 fix this issue. If this is a fix for windown then perhaps it should only be applied on windows system an not linux.

**Comment by dendrocom** [comment]
It's causing the same error in Windows, fixed the same way.

**Comment by lstein** [comment]
My fault for accepting a reasonable-looking pull request that looked without testing it. The contributor meant sys.path.append('.'), and I've just made a commit to fix it.
