### ISSUE TITLE
pickle.unpicklingerror: invalid load key, '\x00'

### ISSUE THREAD

**Issue by t1i12** [lstein/stable-diffusion#141]
Hello, I have followed the installation tutorial step by step 4 times now and have deleted every trace of anaconda and reinstalled it, as well as deleted every file related to the install and downloaded fresh files. I am not well practiced in coding and do not understand what this error means but it is consistently occurring and is preventing me from using this variant of Stable Diffusion. Can someone please advise me on what may be going on and what methods I should try to fix this?

![Screenshot 2022-08-27 143215](https://user-images.githubusercontent.com/112223863/187043633-0b3ce5b6-04e4-4208-900f-ac15206c0241.png)
![Screenshot 2022-08-27 143857](https://user-images.githubusercontent.com/112223863/187043823-58e65197-81d6-415f-b6ae-44cf1a2a1783.png)

**Comment by BlueAmulet** [comment]
Is it possible that your model.ckpt is corrupted? I notice from the error that it's trying to use the legacy torch loading system instead of the modern zip based method that the ckpt is supposed to use.

sd-v1-4.ckpt should be 4,265,380,512 bytes and have the following hashes:
crc32 675D6DD2
md5 C01059060130B8242849D86E97212C84
sha1 210783247AF4F65A3D23D026490CC37A670964DD

**Comment by t1i12** [comment]
If it were corrupted then wouldn't it have been resolved by downloading a fresh copy? Each time I've gone through the installation process, I've used fresh copies of everything. I can also get other versions of Stable Diffusion to work, but no matter what I try it is this one that has this error.

**Comment by lstein** [comment]
Very strange. Just to eliminate an easy fix, could you go ahead and verify the checksums on the model and config files?

~~~~
lstein:~/projects/stable-diffusion$ sha1sum models/ldm/stable-diffusion-v1/sd-v1-4.ckpt configs/stable-diffusion/v1-inference.yaml 
210783247af4f65a3d23d026490cc37a670964dd  models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
73de3f1b41365be1ab43aa40a8b00b0a5d8d2309  configs/stable-diffusion/v1-inference.yaml
~~~~

You say that other forks work. Are you running them in the same conda environment as this one? They are all doing the same thing during the initialization/model loading phase.
