### ISSUE TITLE
Inpainting code and video

### ISSUE THREAD

**Issue by 1blackbar** [lstein/stable-diffusion#144]
https://www.youtube.com/watch?v=N913hReVxMM

I think it works pretty well but i wouldnt implement it like he did (on small 512 image and synthesizing whole image)

What i would do is open a big image and start to synthesize by moving a window with adjustable size 512x512 lets say and mask things i want to apply inpainting to, this way we can work on huge images and fill them up with a lot of generated windos at various sizes .
Well, basically something like this would be better approach , scaling the window and synthesizing on small parts is a good way to save gpu cycles and time .
https://twitter.com/EMostaque/status/1555245665676132353?s=20&t=rVGevPHhk5hHooQWA-S1sw
A moveable window, not sure if thats possible in gradio.

**Comment by lstein** [comment]
Inpainting is a great feature. I see that at least a couple of other forks have implemented WebUIs to support it. Interactive web design is not my strong point and I'm hoping another developer will volunteer to reimplement or copy the approach.

**Comment by AK391** [comment]
@lstein this repo support inpainting https://github.com/hlky/stable-diffusion-webui, if you are looking for simple interface, check out the hosted version here: https://huggingface.co/spaces/stabilityai/stable-diffusion, you can add inpainting quiclky with huggingface diffusers: https://github.com/huggingface/diffusers#in-painting-using-stable-diffusion
