### ISSUE TITLE
Error when trying to train with textual inversion

### ISSUE THREAD

**Issue by cvar66** [lstein/stable-diffusion#146]
Been trying to get the training to work with the following command: python main.py --base ./configs/stable-diffusion/v1-finetune.yaml -t --actual_resume models/ldm/stable-diffusion-v1/model.ckpt -n cip --gpus 0, --data_root E:/textual-inversion/cip --init_word cpixel 

I proceed to get this error:

  File "E:\stable-diffusion\ldm\modules\embedding_manager.py", line 27, in get_clip_token_for_string
    assert (
AssertionError: String 'cpixel' maps to more than a single token. Please use another string

**Comment by maddavid123** [comment]
Seems to be as intended, the original lead author of the Textual Inversion paper and accompanying code also enforces the limitation of a single token.
See https://github.com/rinongal/textual_inversion/issues/6 and https://github.com/rinongal/textual_inversion/issues/18

The main takeaway is that your --init_word is merely the starting point for what your trained image should start from, not how it will later be referred to. A couple of examples include: leaf, sculpture, dog, painting. The model already understands these concepts, and by starting from a well-conceptualised single token, training will be quicker.

It is possible to remove the assertion and bypass the single token restriction, although the original lead author recommends against doing so.
