### ISSUE TITLE
If possible add more samplers?

### ISSUE THREAD

**Issue by tcflying** [lstein/stable-diffusion#147]

**Comment by blessedcoolant** [comment]
Which ones?

**Comment by bmaltais** [comment]
You already have the same as on the stabilityAI web site. Do you have other in mind?

**Comment by LipcaCZ** [comment]
How to change the sampler? I don't see anything about that in the documentation. Thanks.

**Comment by blessedcoolant** [comment]
> How to change the sampler? I don't see anything about that in the documentation. Thanks.

You can pass the -m argument at script launch along with one of the available samplers to change it.

I've made a PR #149 that will allow you to change samplers using prompt arguments too. If that gets pulled in, then you can just supply `-m` and the sampler name to your prompt to change samplers on the fly.

This repo currently supports k_lms, k_euler_a, k_euler, k_dpm_2_a, k_dpm, k_heun, ddim and plms.

**Comment by lstein** [comment]
This change is in the main branch as of last night. For compatibility with the Discord bot, you can use the -A option or -m to change samplers at the dream> command line.
