### ISSUE TITLE
Background mode with reduced GPU usage

### ISSUE THREAD

**Issue by TingTingin** [lstein/stable-diffusion#148]
Is it possible to add a mode that has reduced GPU usage when inferencing or could someone point me in a direction of the code that would need to change

**Comment by lstein** [comment]
I don't have an answer to this since my knowledge of CUDA tuning is minimal. Anyone?

**Comment by lstein** [comment]
If this is a Windows system, perhaps the NVIDIA control panel can be used? https://nvidia.custhelp.com/app/answers/detail/a_id/3130/~/setting-power-management-mode-from-adaptive-to-maximum-performance
