### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by thezveroboy** [lstein/stable-diffusion#15]
after typing python scripts\dream.py -l

i'm getting this error:

Traceback (most recent call last):
  File "scripts\dream.py", line 277, in <module>
    main()
  File "scripts\dream.py", line 37, in main
    os.path.append('.')
AttributeError: module 'ntpath' has no attribute 'append'

**Comment by pmongan** [comment]
I am also getting this error.  In case a screenshot help
![error](https://user-images.githubusercontent.com/111465041/185794831-281db0cd-ca96-4ce3-9957-384570305f21.jpg)
s

**Comment by Caliban0101** [comment]
I have the same issue

**Comment by lstein** [comment]
Sorry. I committed a pull request without testing it. Please perform a git pull for latest version, or re-download.
