### ISSUE TITLE
Plugin architecture?

### ISSUE THREAD

**Issue by janekm** [lstein/stable-diffusion#155]
There are a number of features that I would love to have/implement that while very useful to me, might not be of interest to many other users. Examples:
- Load prompt from AWS SQS
- Store generated file to AWS S3

You mentioned in response to another pull request that you were working on a refactoring of the code, so I'm holding off on making pull requests at the moment. I thought it might be helpful to consider whether a plugin architecture could help to implement less frequently used features, and potentially these could be maintained in forks without too much dependency on the base repo code. Here's an interesting article on python plugin architectures: https://eli.thegreenplace.net/2012/08/07/fundamental-concepts-of-plugin-infrastructures

**Comment by bmaltais** [comment]
Code has already been refactored

**Comment by tildebyte** [comment]
@janekm This sounds like a really good idea.

**Comment by lstein** [comment]
@janekm Please go ahead! The basic organization of the code won't change anytime soon. I finished the urgent refactoring a few days ago.

**Comment by bakkot** [comment]
NB: @verderog linked a plugin system they're working on in [this comment](https://github.com/lstein/stable-diffusion/issues/32#issuecomment-1229535698).

**Comment by bmaltais** [comment]
This look like a brilliant idea. Looking forward to this being implemented.

**Comment by MarcusLlewellyn** [comment]
Since this uses S3, I wonder if this could also be compatible with Digital Ocean Spaces (which is just a rebranded/differently hosted S3.) I serve virtual world assets from one of these, and I've been pondering the idea of using Stable Diffusion to regularly generate and update 2D artwork.

**Comment by janekm** [comment]
@MarcusLlewellyn I haven't prepared the pull request yet (need to do some tidying up and integrating the recent upstream changes) but I imagine it would work, the code is here: https://github.com/lstein/stable-diffusion/commit/660c5ecef4cd3fa9c557381ddce63780519e5ea0

The line that initialises the s3 client would need to be updated for digital ocean spaces... simple enough but have to think about an easy way to configure that. Could just use an environment variable called "ENDPOINT_URL" I suppose to keep things simple.

It's looking for whether an environment variable "S3_BUCKET" is set and calls the upload code in that case. You should also have your authorisation

**Comment by lstein** [comment]
@janekm are you still working on this? The right way to get your feature into the repository is to make a pull request.

**Comment by janekm** [comment]
> 

Yes sorry for the delay... this repo has been moving so quickly I have to do quite a lot of merging before I can make the pull request 😅 Should have some time this weekend. (this is for the AWS stuff... the plugin infrastructure is more complicated and probably not best handled in a pull request anyway)
