### ISSUE TITLE
Feature request: dream_web webpage needs a reset settings button

### ISSUE THREAD

**Issue by Cubox** [lstein/stable-diffusion#157]
I had an issue where my sister got somehow 64x64 as image size, and didn't have a clue what the default was.
A simple button to reset all fields (steps/number of images/prompt/size) to default would greatly help people who don't know what those defaults are.

**Comment by lstein** [comment]
I wonder if @tesseractcat or @dagf201 could have a look at this? It sounds simple, but I wouldn't know how to do it.

**Comment by lstein** [comment]
Just added this feature on PR #178. I made the reset button nice and red 😊. Please do a pull from "main".

**Comment by Cubox** [comment]
You're the best!
