### ISSUE TITLE
Dream.py no longer working after 'dagf2101-main' branch merge

### ISSUE THREAD

**Issue by namion** [lstein/stable-diffusion#163]
I get the following when trying to run the new web interface:

(ldm2) W:\AI Art\stable-diffusion>python scripts/dream.py --web
Traceback (most recent call last):
  File "scripts/dream.py", line 12, in <module>
    from ldm.dream.server import DreamServer, ThreadingDreamServer
  File "w:\ai art\stable-diffusion\ldm\dream\server.py", line 12, in <module>
    from dream_server import DreamServer, ThreadingDreamServer
ModuleNotFoundError: No module named 'dream_server'

I had no issues with the Web UI prior to this merge

**Comment by theRolento** [comment]
Even without `--web`, the normal `dream.py` script doesn't work anymore

**Comment by namion** [comment]
> 

well look at that, you are absolutely correct. I didn't even try that as I was just trying to check out the web interface. So yeah, as of right now I can't run the script at all.

**Comment by BassJMagan** [comment]
Same issue.
(ldm) <omitted>\stable-diffusion>python scripts/dream.py
Traceback (most recent call last):
  File "scripts/dream.py", line 12, in <module>
    from ldm.dream.server import DreamServer, ThreadingDreamServer
  File "c:\users\chray\stable-diffusion\ldm\dream\server.py", line 12, in <module>
    from dream_server import DreamServer, ThreadingDreamServer
ModuleNotFoundError: No module named 'dream_server'

**Comment by tildebyte** [comment]
@lstein; Looks like we (basically) have 'scripts/dream.py' -> 'ldm/dream/server.py' instead of  'scripts/dream_web.py' -> 'ldm/dream/server.py'

**Comment by BassJMagan** [comment]
fixed w/ latest update

**Comment by lstein** [comment]
Very sorry. Had tested the change out in a different branch and then mistyped the mv command in main. Should test, test test.

Fixed in commit ac02a775e41fc0027180c962b5af8ffa3496f5e0
