### ISSUE TITLE
Crash when using japanese characters or accented characters.

### ISSUE THREAD

**Issue by BassJMagan** [lstein/stable-diffusion#174]
Whenever an accented or Japanese character(kanji,hiragana,katakana) is entered, it will generate the prompt, finish generating all images, and then crash out of dream.py back into ldm with the following for instance when using "かわいい":
Traceback (most recent call last):
  File "scripts/dream.py", line 475, in <module>
    main()
  File "scripts/dream.py", line 95, in main
    main_loop(t2i, opt.outdir, cmd_parser, log_path, infile)
  File "scripts/dream.py", line 205, in main_loop
    write_log_message(t2i, normalized_prompt, results, log_path)
  File "scripts/dream.py", line 249, in write_log_message
    file.writelines(log_lines)
  File "C:\Users\chray\.conda\envs\ldm\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 44-47: character maps to <undefined>

**Comment by bakkot** [comment]
https://github.com/lstein/stable-diffusion/pull/175 should fix this.

**Comment by lstein** [comment]
I just brought in pull request #175, which adds support for unicode characters. Please let us know if this fixes the problem.

**Comment by BassJMagan** [comment]
The crash is no longer present, tried with kanji and accented characters, Thanks!
