### ISSUE TITLE
Filename  and foder classification proposition

### ISSUE THREAD

**Issue by vinyvince** [lstein/stable-diffusion#183]
Please change or add option to have a different more explicit output file name. So we could more easily find for each prompt which image is referring too (without having the log file open which extend quite a lot everyday). Is especially useful when batch processing. I think it will be beneficial if they will be classified by prompt folders too.

Thanks, awesome effort

**Comment by BlueAmulet** [comment]
#126 was superseded by #189

**Comment by lstein** [comment]
Merge has gone in. Pass the -p (--prompt-dir) flag to dream.py to activate this feature. Folders are named after the prompt string, and files still have the numeric names+seeds. Please open an issue if you find any situations in which the system tries to create illegal file names, creates unopenable files/directories, and other nastiness.
