### ISSUE TITLE
The help text incorrectly refers to CFG scale as "Prompt configuration" scale instead of "Classifier Free Guidance" scale

### ISSUE THREAD

**Issue by n00mkrad** [lstein/stable-diffusion#188]
CFG does not stand for configuration, it stands for Classifier Free Guidance, as mentioned in the title.

**Comment by blessedcoolant** [comment]
Thanks for pointing it out. I'll add it to my next bug fix patch.

**Comment by lstein** [comment]
This has been fixed in commit 19e4298cf9d9fbe0c1ee855f808e36101a811f18
