### ISSUE TITLE
Its overwriting my images 

### ISSUE THREAD

**Issue by 1blackbar** [lstein/stable-diffusion#19]
I dont remember it happening, how to prevent it ? i just run a prompt 

dream chuck norris!!! clay! close detailed sculpted head  of chuck norris , style: claymation puppet kids clay , by guldies -n 4

and my images kept being overwritten to the same 4 filenames
--- ok i deleted dream log and its not doing that so all is fine for now
but i think it has something to do that i used grid setting... 

 another bug - it kicked me out of model for not closing quotation

--
OK it started overwriting my images again, i think it gets confused when i use -n 4 after awhile and keeps outpitting to the same filenames as before, there must be some extra checks in the code to prevent that IMO

**Comment by thezveroboy** [comment]
this are for all forks. it's a problem of original code

**Comment by morganavr** [comment]
Problem appears when trying to regenerate an image with the same seed.
Original image was generated with filename 00008.png
Then, if you run the prompt below (this prompt is slightly different from original) - script overwrites 00008.png file with new image and reports that new image has exactly the same seed. This behavior makes experiments (attempt to create variations of image by tweaking its parameters) more difficult compared to SD discord bot that generated new seed for each newly generated image and the most frustrating part is that original image is overwritten.

Example of prompt that causes the problem:

dream> "photo of an elephant reading a book" -s150 -b1 -W512 -H512 -C8.5 -I./init-images/5.png -f0.5 -S1108544598

**Comment by lstein** [comment]
I've fixed the closing quote problem (and similar problems parsing the prompt). Use \' to get a quote mark.

With respect to overwriting files, I've observed this as well. I will replace the original filenaming algorithm with something that never overwrites a file.

**Comment by morganavr** [comment]
What about adding seed number at the end of each image name? Every generated image should have unique seed.
Like 0000000001_S1108544598.png

Also, I propose to increase number of decimals in filename from 5 decimals to at least 10 because people will generate tons of images.

**Comment by lstein** [comment]
This could work. I'd also like to number img2img mods so that the basename of the original file is reused, so something like 0005-revision1.png

**Comment by morganavr** [comment]
I like idea with revisions! For correct file sorting I propose to increase number of digits to at least 3:  revision001.png

> Does anyone mind if I replace the 00042.png filenames with a timestamp, such as 22Aug22-14:10:11.png

If you decide to use timestamp, I propose to use UNIX format because filenames could be correctly sorted in File Explorer.

Example of UNIX timestamp: 1661213008

**Comment by lstein** [comment]
I'm going to stick with the simple numbers and just add a few leading zeroes for the time being. The problem with the original code is that it counted the number of files in the current directory and named the next file 1+the count. However, if some of the files had been deleted, the count would be wrong and files would get overwritten because the code didn't check whether it clobbered a file. For revisions, I'll append a dot and an additional 3 digits (nobody's gonna do an img2img 999 times, are they?).

In the future one could specify a printf string on the command line to format filenames according to your preference, e.g.
~~~~
--filename_format="%Y-%d-%p-%S.png"
~~~~
The various % formats would be replaced with something like p="text of prompt", S=seed, %Y=year, etc.

**Comment by 1blackbar** [comment]
is half precision used as default? i think its the full one from what i see in the dream file

**Comment by lstein** [comment]
* Filenames now use the following formats:
~~~~
       000010.95183149.png      -- Two files produced by the same command (e.g. -n2),
       000010.26742632.png      -- distinguished by a different seed.

       000011.455191342.01.png  -- Two files produced by the same command using
       000011.455191342.02.png  -- a batch size>1 (e.g. -b2). They have the same seed.

       000011.4160627868.grid#1-4.png  -- a grid of four images (-g); the whole grid can
                                          be regenerated with the indicated key
~~~~

Yes, half precision is the default. The arg parser's syntax is a little weird.
