### ISSUE TITLE
Web UI: All images are produced using the K_lms sampler regardless of which sampler is selected.

### ISSUE THREAD

**Issue by namion** [lstein/stable-diffusion#191]
When using the Web UI, all images are being produced with the k_lms sampler.

a yorky standing on the moon -s100 -S1328222811

All sampler selections produce this image:
![000473 1328222811](https://user-images.githubusercontent.com/42051395/187254839-ccca3498-be09-48fc-b131-a64ea8df3c60.png)

When not using web UI:

ddim:
![000470 1328222811](https://user-images.githubusercontent.com/42051395/187255024-d65a5ca3-87de-4d1e-81f1-9b4723562fe1.png)

k_dpm_2_a:
![000471 1328222811](https://user-images.githubusercontent.com/42051395/187255102-20cb331d-fee4-4079-bfec-f1aa0411dc58.png)

k_lms:
![000472 1328222811](https://user-images.githubusercontent.com/42051395/187255171-59edd6c8-b44b-4eaf-8b2c-61c89ee249f3.png)

**Comment by Cubox** [comment]
Can confirm

**Comment by lstein** [comment]
Pull request #193 will fix this.

**Comment by lstein** [comment]
This is now merged into main.
