### ISSUE TITLE
init image not working in google collab

### ISSUE THREAD

**Issue by rickyars** [lstein/stable-diffusion#194]
when i try use an init image in google collab i get an error that crashed the dream script:
```
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```
a quick good search indicates this might be an issue with PIL. look like we might need to use 9.1.0 not 9.0.1 (which is in the current requirements.txt file)

**Comment by lstein** [comment]
There seem to be a few of these cases in which packages just don't behave the same in Google Colab. Try 9.1.0 and if it works, I'll change requirements.txt (after testing on other systems).

**Comment by rickyars** [comment]
I tried 9.1.0 and that got me further along but then I ran into another error (something about tensor lengths - don't remember). I'll open up a new ticket.

**Comment by lstein** [comment]
Ok. I'll close this one. Please post a stack trace in the new issue.
