### ISSUE TITLE
dream_web.py gone from the code?

### ISSUE THREAD

**Issue by arothmanmusic** [lstein/stable-diffusion#196]
I just did a 'git pull' and the _python scripts\dream_web.py_ no longer works as described in the instructions. I tried _dream.py --web_ and it does load a page, but the CSS and JS aren't found. Is there something wonky going on with my setup or is there a new method I need to use for the GUI?

**Comment by bakkot** [comment]
Nice catch on the instructions being stale; I'll submit a PR updating those.

Re: "the CSS and JS aren't found", that's probably [this issue](https://github.com/lstein/stable-diffusion/pull/192); you could try the fix in that PR.

**Comment by arothmanmusic** [comment]
Thanks @bakkot - Adding the .lower() to the code fixed the paths.

**Comment by bakkot** [comment]
@arothmanmusic would you be up for trying out [this change](https://github.com/lstein/stable-diffusion/pull/192#discussion_r957681533) instead? I like that fix better but I'm not in a position to test if it works, and it sounds like you are.

**Comment by arothmanmusic** [comment]
@bakkot I've swapped that line and restarted the server. Seems to work just as well that way as it did the other!

**Comment by bakkot** [comment]
Should be fixed on main between https://github.com/lstein/stable-diffusion/pull/198 and https://github.com/lstein/stable-diffusion/pull/192. Thanks for the report.
