### ISSUE TITLE
No Module named k_diffusion

### ISSUE THREAD

**Issue by Dartterious** [lstein/stable-diffusion#20]
With the new weights released I thought I could slot it into the stable diffusion V1 folder and start generating images. But i'm getting the following error 
![2022-08-23 03_04_06-Anaconda Prompt (Miniconda)](https://user-images.githubusercontent.com/109719059/185999156-a05057df-bcd9-4b2a-8526-8d99dc3eadd9.jpg)

**Comment by 1blackbar** [comment]
when you activate it run this  -    conda env update -f environment.yaml   also name your model   model.ckpt
