### ISSUE TITLE
Missing --strength parameter for img2img in Web Server UI and can't use --strength flag in prompt anymore

### ISSUE THREAD

**Issue by theRolento** [lstein/stable-diffusion#202]
The --strength parameter for img2img is missing in the web UI
#134 discussion from here

**Comment by cvar66** [comment]
Using the strength flag in the prompt doesn't work anymore either in the Web UI.

**Comment by theRolento** [comment]
> Using the strength flag in the prompt doesn't work anymore either in the Web UI.

Indeed you are right.

**Comment by cvar66** [comment]
Not sure why this hasn't received much attention. Seems important and easy to fix. img2img is useless without being able to control the strength.
