### ISSUE TITLE
img2img should resize init image to -W and -H values when specified

### ISSUE THREAD

**Issue by thelemuet** [lstein/stable-diffusion#207]
This might seem trivial but this appears to be quite standard with other generators that allow init images as input, including other versions of SD and previous diffusion/older models. So I was wondering is there a reason why this was removed/disabled?

Of course it depends on an individual's workflow, but when working with init images, it is often much more convenient to work from original high resolution files.

For example I may want to take an image with 1:1 ratio and try generating with it at 512x512, 576x576, 640x640, etc. Or doing multiple small edits to init image(s) between runs. Currently it can get quite tedious having to resize and maintain multiple versions of the same images. Exponentially bothersome when working with variations or animated sequences of init images ;)

It would make things so much more simple if img2img took care of resizing to specified -W and-H values, instead of using an external app.

**Comment by n00mkrad** [comment]
+1

I was surprised this fork doesn't have this useful feature since most others have had it for a while

**Comment by lstein** [comment]
Absolutely right. Currently we're doing it in exactly the opposite way - ignoring the provided width and height and using the init_img dimensions. I assume you would want to pad the image with black borders to keep the aspect ratio correct?

I will fix the mod32-64 problem at the same time.

**Comment by thelemuet** [comment]
> Absolutely right. Currently we're doing it in exactly the opposite way - ignoring the provided width and height and using the init_img dimensions. I assume you would want to pad the image with black borders to keep the aspect ratio correct?
> 

Personally I would expect that it would simply fit and fill the whole image into the specified dimensions regardless of aspect ratio. I can't think of a case where I would want padding or anything extra but maybe others might think differently.

**Comment by n00mkrad** [comment]
Does not work as of right now.
