### ISSUE TITLE
Can Textual Inversion images be recreated with the same seed on another PCs?

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#209]
Using Textual inversion I have teached SD to generate plastic figures. But when I sent the prompt below to my friend he got a completely different image. How is it possible? He uses lstein fork also (the latest version, and I use version released few days ago)
I thought that identical prompt + seed should result in identical images... Can somebody check if you get the same image?

`python scripts/dream.py --embedding_path emb/embeddings-d1.pt`

`"a photo of *" -s50 -b1 -W512 -H512 -C10.0  -S3224941461`

[embeddings-d1.gz](https://github.com/lstein/stable-diffusion/files/9451546/embeddings-d1.gz) (you need to create "emb" folder and place that file inside and change file extension from .gz to .pt)

![003101__ 3224941461](https://user-images.githubusercontent.com/51041813/187399822-bb048548-c5b1-449b-91b1-b7d6cfff9cfd.png)

**Comment by blessedcoolant** [comment]
I got this with k_lms. What sampler were you using? 

![000002 3224941461](https://user-images.githubusercontent.com/54517381/187473905-a591738c-6e9b-403e-809c-f4fdcbc823c2.png)

**Comment by morganavr** [comment]
I did not specify any sampler. Inside PNG this metadata is written:
`"a photo of *" -s50 -b1 -W512 -H512 -C10.0 -mk_lms -S3224941461`

**Comment by morganavr** [comment]
Is it possible that sd14.ckpt was updated recently? It could explain a difference.

**Comment by Ratinod** [comment]
"a photo of *" -s50 -b1 -W512 -H512 -C10.0 -S3224941461
"a photo of *" -s50 -b1 -W512 -H512 -C10.0 -mk_lms -S3224941461
a photo of * -s50 -b1 -W512 -H512 -C10.0 -mk_lms -S3224941461
a photo of * -s50 -b1 -W512 -H512 -C10.0 -S3224941461
all gave me the same result:
![000001 3224941461](https://user-images.githubusercontent.com/12137233/187484739-0c0189e1-b15a-4692-aa24-a0df3187c4f4.png)

**Comment by morganavr** [comment]
Very interesting! We have the same results with @Ratinod but @blessedcoolant generated a different image.

**Comment by Ratinod** [comment]
I couldn't find an image similar to that of  @blessedcoolant by changing samplers
![claytest](https://user-images.githubusercontent.com/12137233/187488488-0ba477ff-2e54-4f60-b42d-bf00808b322c.png)

**Comment by blessedcoolant** [comment]
> 

Let me get this updated model and try again.

**Comment by morganavr** [comment]
@blessedcoolant what is MD5 checksum of your model.ckpt file? In my post above I wrote how to see it.

**Comment by blessedcoolant** [comment]
> @blessedcoolant what is MD5 checksum of your model.ckpt file? In my post above I wrote how to see it.

They're different. Also I was using the non-ema model. Maybe that was the difference maker. I'll download and try the ema one.

**Comment by Ratinod** [comment]
By the way. @morganavr, how long have you been training the model? It's not entirely clear how to decipher this "~1h @1.6 iterations/sec"...

**Comment by namion** [comment]
> They're different. Also I was using the non-ema model. Maybe that was the difference maker. I'll download and try the ema one.

>Edit: Yep. That was the difference. The 4GB model gave me the result I posted. The 7GB ema one gives me what OP posted.

@blessedcoolant So is one "better" than the other? All the instructions I found online pointed towards the 4gb file. Is there any reason to used the 7gb file over the 4gb file? I don't have a good enough technical understanding to know. Thanks!

**Comment by blessedcoolant** [comment]
> @blessedcoolant So is one "better" than the other? All the instructions I found online pointed towards the 4gb file. Is there any reason to used the 7gb file over the 4gb file? I don't have a good enough technical understanding to know. Thanks!

I haven't done extensive checks on this but from the few samples I generated, I personally prefer the results of the 4gb model. It converges much faster on most of the samplers and the results seem to high quality and accurate.

**Comment by morganavr** [comment]
> By the way. @morganavr, how long have you been training the "Textual inversion"? It's not entirely clear how to decipher this "~1h @1.6 iterations/sec"...

around 1 hour on Google Colab free T4 GPU

**Comment by morganavr** [comment]
I think this issue can be closed. Reason for difference was a different model ckpt file.
