### ISSUE TITLE
Is it possible to run dream.py in --full_precision mode on 8GB VRAM?

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#222]
I thought there is not much difference between `half precision` mode and `full precision` but then I found a comparison image on Reddit or Discord - can't remember a place but I can remember results - `full precision` images (faces of people, eyes) were of much higher quality. 

Is there a way to apply some magic to lstein code so it can run on 8GB GPUs in `--full_precision` mode?

**Comment by Ratinod** [comment]
I tried to run `--full_precision` and i can generate 512x512 pictures. 7.9/8.0 GB
Try turning off everything that uses the video card memory

**Comment by morganavr** [comment]
7.9/8 is too much VRAM reserved for SD. I need at least 1GB of VRAM for daily work.

**Comment by Ratinod** [comment]
> 7.9/8 is too much VRAM reserved for SD. I need at least 1GB of VRAM for daily work.

Then the only thing you have to use is generate smaller images with -W and -H arguments (-W448 -H448 or less for example)
I would also like less consumption of video memory, but glad that on a local system with 8 VRAM, you can somehow generate the standard size (512x512) of images.

**Comment by lstein** [comment]
A solution would be to implement the optimizedSD algorithm which sacrifices speed for VRAM usage and lets you generate 512x512 images in 4GB RAM:  https://github.com/basujindal/stable-diffusion. I'm not currently focused on doing this, but rather on growing out the feature list (e.g. inpainting), but happy to take volunteers.

**Comment by GordonFreeeman** [comment]
Came here to ask that exact question. I've got a 6 GB 1660 Ti, which will always produce blank green images in half-precision mode. 🤔

**Comment by lstein** [comment]
I believe this issue was fixed in one of last week's M1-related patches. I personally can see no difference in the resulting images between half and full precision, except that the latter takes 50% more memory.
