### ISSUE TITLE
Request: Option to show intermediate images in CLI, not just web

### ISSUE THREAD

**Issue by n00mkrad** [lstein/stable-diffusion#224]
Today code to show the generation progress for the web ui was added.

Is it possible to also add this as a CLI switch? Would be very helpful for my use case.

**Comment by bakkot** [comment]
The CLI has always shown progress:

<img width="847" alt="Screen Shot 2022-08-30 at 3 24 46 PM" src="https://user-images.githubusercontent.com/1653598/187554302-2ceaac83-1d79-4904-8a3d-9627ef6bff58.png">

What more are you looking for?

**Comment by blessedcoolant** [comment]
> The CLI has always shown progress:
> 
> <img alt="Screen Shot 2022-08-30 at 3 24 46 PM" width="847" src="https://user-images.githubusercontent.com/1653598/187554302-2ceaac83-1d79-4904-8a3d-9627ef6bff58.png">
> 
> What more are you looking for?

I believe he's probably asking for a way to save intermediary progress so he can make a video out of the progress later.

**Comment by lstein** [comment]
Ah. In that case I think we should just use the callback mechanism to create a video.

**Comment by n00mkrad** [comment]
> The CLI has always shown progress:
> 
> <img alt="Screen Shot 2022-08-30 at 3 24 46 PM" width="847" src="https://user-images.githubusercontent.com/1653598/187554302-2ceaac83-1d79-4904-8a3d-9627ef6bff58.png">
> 
> What more are you looking for?

I want to dump a PNG every x steps.

**Comment by n00mkrad** [comment]
> > The CLI has always shown progress:
> > <img alt="Screen Shot 2022-08-30 at 3 24 46 PM" width="847" src="https://user-images.githubusercontent.com/1653598/187554302-2ceaac83-1d79-4904-8a3d-9627ef6bff58.png">
> > What more are you looking for?
> 
> I believe he's probably asking for a way to save intermediary progress so he can make a video out of the progress later.

Yes but for my use case just saving PNGs is fine, stuff like creating videos can be done afterwards with ffmpeg etc.

**Comment by tildebyte** [comment]
Tricky, because of the matrix formed by 1- Differences in how terminals allow displaying images 2 - Differences across OSs

**Comment by bakkot** [comment]
I don't know if it's worth having a CLI flag for this, but it's easy to do with a small bit of code. This will save the intermediate frames to `outputs/intermediates`.

```py
import transformers

from ldm.dream.pngwriter import PngWriter
from ldm.simplet2i import T2I

t2i = T2I()
transformers.logging.set_verbosity_error()
t2i.load_model()

prompt = "a warrior prince, highly detailed digital art"

step_writer = PngWriter('./outputs/intermediates/')
step_index = 1
prefix = step_writer.unique_prefix()

def image_progress(sample, step):
    global step_index
    seed = t2i.seed
    image = t2i._sample_to_image(sample)
    name = f'{prefix}.{seed}.{step_index}.png'
    metadata = f'{prompt} -S{seed} [intermediate]'
    step_writer.save_image_and_prompt_to_png(image, metadata, name)
    step_index += 1

t2i.prompt2png(
    prompt=prompt,
    outdir="outputs/results",
    steps=15,
    step_callback=image_progress
)
```

**Comment by n00mkrad** [comment]
> I don't know if it's worth having a CLI flag for this, but it's easy to do with a small bit of code. This will save the intermediate frames to `outputs/intermediates`.
> 
> ```python
> import transformers
> 
> from ldm.dream.pngwriter import PngWriter
> from ldm.simplet2i import T2I
> 
> t2i = T2I()
> transformers.logging.set_verbosity_error()
> t2i.load_model()
> 
> prompt = "a warrior prince, highly detailed digital art"
> 
> step_writer = PngWriter('./outputs/intermediates/')
> step_index = 1
> prefix = step_writer.unique_prefix()
> 
> def image_progress(sample, step):
>     global step_index
>     seed = t2i.seed
>     image = t2i._sample_to_image(sample)
>     name = f'{prefix}.{seed}.{step_index}.png'
>     metadata = f'{prompt} -S{seed} [intermediate]'
>     step_writer.save_image_and_prompt_to_png(image, metadata, name)
>     step_index += 1
> 
> t2i.prompt2png(
>     prompt=prompt,
>     outdir="outputs/results",
>     steps=15,
>     step_callback=image_progress
> )
> ```

How do I integrate this into dream.py from this repo? Sorry, my Python skills are rather basic.

**Comment by bakkot** [comment]
Don't - just save it as a file in this directory and run it with `python this-script.py`.

**Comment by n00mkrad** [comment]
> Don't - just save it as a file in this directory and run it with `python this-script.py`.

But that's not what I wanted, I want to have the same functionality as usual, but in addition to dumping a progress PNG every x steps.

**Comment by n00mkrad** [comment]
Any help? Can't be too hard to do this, but my limited Python skills fail me here.

**Comment by search620** [comment]
I Would like to request additions to the next version that the steps will be added to the name of the image.
And also removing the date from the name of the image is confusing. Thanks!

**Comment by lstein** [comment]
Sorry for the delay on acting on this. I'm going to put this into the feature request list in the Discussion section. It will get implemented at some point in the not-too-distant future.
