### ISSUE TITLE
Feature Request: Specify a file of prompt requests.

### ISSUE THREAD

**Issue by KnobleSavage** [lstein/stable-diffusion#23]
Hi, loving the script.  It's really nice to run just like the discord did.

It would be really nice if we could hand the script a text file and it would run the prompts out of that text file.  I'd be okay with it bombing as normal when there were issues like oom, or whatnot.  That would be par for the course.  A simple file that perhaps supported comments with lines that began // (or some such) would be fantastic.  I'm picturing something like this:

dream>-inputFile "c:\stable-diffusion\inputfile.txt"

----inputFile.txt----
// sample prompt file
"a unicorn in manhatten" -n4 -H512 -W640 -S1234
"a fantastic futuristic landscape, trending on artstation" -n4 -H512 -W512 -S5678
// and now for the bulk generation
"this prompt will generate quite a few images by greg rutkowski, 8k, trending on artstation" -n1000 -H512 -W640

**Comment by lstein** [comment]
That's actually a feature of the original CompViz text2img and img2img scripts. I think I can shoehorn the same functionality in.

**Comment by AchillesPDX** [comment]
Hey - is this actually working? I just pulled the 1.06 commit and I can't seem to get --from_file to actually do anything. Keep up the amazing work! Crazy how fast this is all evolving.

**Comment by KnobleSavage** [comment]
> 
It works.  The --from_file attribute is a command line prompt, not a dream> prompt.  So to see this feature work, add the parameter as you start up the script... like so:


C:\sd\stable-diffusion>python scripts/dream.py --from_file "c:\sd\prompts.txt"

**Comment by AchillesPDX** [comment]
> > 
> 
> It works. The --from_file attribute is a command line prompt, not a dream> prompt. So to see this feature work, add the parameter as you start up the script... like so:
> 
> C:\sd\stable-diffusion>python scripts/dream.py --from_file "c:\sd\prompts.txt"

Well hot damn! Thanks so much! Time to go nuts.
