### ISSUE TITLE
Migrate Preload weight to offline environment

### ISSUE THREAD

**Issue by NTNguyen13** [lstein/stable-diffusion#242]
Hi, thanks for the great repo.

I am trying to deploy your version to an offline environment, without the shared drive. I think that if I can manually copy the file from my computer to the offline environment, the model will still work, but I'm not sure where the weight/config is located, and where should I put it on the new environment?

Thank you so much.

**Comment by lstein** [comment]
There is a big issue you need to be aware of. Yes, you can just copy the weights from models/ldm/stable-diffusion-v1/model.ckpt to the like-named directly on the offline system. That's no problem.

**However**, there are also a bunch of other ML models that Stable Diffusion relies on, including BERT, CLIP, Kornia, and optionally the RealESRGAN and GFPGAN models. These models are "loaded on demand" the first time they are referenced, and get copied into a cache directory using the [HuggingFace Hub repository](https://huggingface.co/docs/huggingface_hub/how-to-manage) system. The right thing to do is to create a local hub for your offline system to use by following the instructions at the page referenced in the previous sentence. This seems fairly involved, so my hack-around is to load all the models from an online system using scripts/preload_models.py using a shared drive between the online and the offline system. Unfortunately this won't work for you.

So the right thing to do is to go through the steps described in the HuggingFace docs, get the files downloaded to the right place, keep track of what you had to do, and then share the info with the rest of the community here. We've got a WIKI set up for this type of expert tips.

The wrong thing to do -- but which might work -- is to find out where the Hugging Face cache lives on your system and copy the whole thing kit-and-kaboodle over to the offline system. On my system, it is located in ~/.cache/huggingface, but it might be located somewhere else on yours, particularly if you are working on a Windows system.

Good luck, and let me know what happens!

**Comment by NTNguyen13** [comment]
Hi, after playing around, I think the best option is making a docker image. Even though it could pose some difficulties in installing nvidia-docker, but it avoids all huggingface shenanigans.
