### ISSUE TITLE
M1 RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED ... MPSAllocator.mm

### ISSUE THREAD

**Issue by cosalexelle** [lstein/stable-diffusion#244]
Running `python3 scripts/dream.py`

Most recent console log: 

`making attention of type 'vanilla' with 521 in_channels`

**Device:** MacBook Air M1

Full error:

```Traceback (most recent call last):
  File "/Users/cosalexelle/stable-diffusion/./scripts/dream.py", line 518, in <module>
    main()
  File "/Users/cosalexelle/stable-diffusion/./scripts/dream.py", line 85, in main
    t2i.load_model()
  File "/Users/cosalexelle/stable-diffusion/ldm/simplet2i.py", line 537, in load_model
    model = self._load_model_from_config(config, self.weights)
  File "/Users/cosalexelle/stable-diffusion/ldm/simplet2i.py", line 591, in _load_model_from_config
    model.to(self.device)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
    return super().to(*args, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED at "/Users/runner/miniforge3/conda-bld/pytorch-recipe_1660136240338/work/aten/src/ATen/mps/MPSAllocator.mm":124, please report a bug to PyTorch.```

**Comment by lstein** [comment]
@magnusviri , flagging this to your attention.This is something I can't reproduce for lack of the appropriate hardware.

**Comment by eous** [comment]
`Traceback (most recent call last):
  File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 319, in <module>
    main()
  File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 195, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 43, in load_model_from_config
    model.to(choose_torch_device())
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
    return super().to(*args, **kwargs)
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1661929724579/work/aten/src/ATen/mps/MPSAllocator.mm":124, please report a bug to PyTorch. `

Similar error on Mac OS X from txt2img.py using latest checkout with naturally installed PyTorch release and nightly PyTorch

**Comment by cosalexelle** [comment]
> Similar error on Mac OS X from txt2img.py using latest checkout with naturally installed PyTorch release and nightly PyTorch
> 
> ```
> Traceback (most recent call last):
>   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 319, in <module>
>     main()
>   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 195, in main
>     model = load_model_from_config(config, f"{opt.ckpt}")
>   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 43, in load_model_from_config
>     model.to(choose_torch_device())
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
>     return super().to(*args, **kwargs)
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in to
>     return self._apply(convert)
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
>     module._apply(fn)
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
>     module._apply(fn)
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 662, in _apply
>     param_applied = fn(param)
>   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 985, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1661929724579/work/aten/src/ATen/mps/MPSAllocator.mm":124, please report a bug to PyTorch. ```
> ```

I wonder if it is the Nightly PyTorch constantly being committed to that is causing different errors for different people. The error you received is similar, but on a different line in `torch.py`

A working version of stable diffusion for M1 may not be available until MPS becomes stable in PyTorch

**Comment by eous** [comment]
> > Similar error on Mac OS X from txt2img.py using latest checkout with naturally installed PyTorch release and nightly PyTorch
> > ```
> > Traceback (most recent call last):
> >   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 319, in <module>
> >     main()
> >   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 195, in main
> >     model = load_model_from_config(config, f"{opt.ckpt}")
> >   File "/Users/patrickbuckley/git/stable-diffusion/scripts/orig_scripts/txt2img.py", line 43, in load_model_from_config
> >     model.to(choose_torch_device())
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
> >     return super().to(*args, **kwargs)
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in to
> >     return self._apply(convert)
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
> >     module._apply(fn)
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
> >     module._apply(fn)
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
> >     module._apply(fn)
> >   [Previous line repeated 1 more time]
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 662, in _apply
> >     param_applied = fn(param)
> >   File "/Users/patrickbuckley/opt/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 985, in convert
> >     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> > RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1661929724579/work/aten/src/ATen/mps/MPSAllocator.mm":124, please report a bug to PyTorch. ```
> > ```
> 
> I wonder if it is the Nightly PyTorch constantly being committed to that is causing different errors for different people. The error you received is similar, but on a different line in `torch.py`
> 
> A working version of stable diffusion for M1 may not be available until MPS becomes stable in PyTorch

Yeh, it is looking like MPS is fairly broken atm after much jiggling. You can still play with this on a Mac by changing dream/devices.py and forcing it to return cpu instead of mps. It will be a lot slower but its something.

**Comment by magnusviri** [comment]
@cosalexelle @eous Is this still a problem for you? I haven't seen anyone else mention this and I know other people have it working.

**Comment by cosalexelle** [comment]
@magnusviri Yes, the same error as above is still occurring with the latest git main branch

**Comment by cosalexelle** [comment]
I was thinking it could be out of RAM as this is an 8GB MacBook Air, but using htop shows approx 4GB RAM usage and swap space at 2GB out of 4GB so I am not sure

**Comment by cosalexelle** [comment]
Update: after Conda remove, then Conda env create: 

```
k_diffusion/sampling.py line 10
ImportError: cannot import name TypeAlias from 'typing' (python3.9/typing.py)
```

**Comment by eousphoros** [comment]
> I was thinking it could be out of RAM as this is an 8GB MacBook Air, but using htop shows approx 4GB RAM usage and swap space at 2GB out of 4GB so I am not sure

I'm on an m1 max with 64 GB of ram and 8 TB nvme so unlikely my issue. 

> Update: after git pull origin main, Conda remove, then Conda env create:
> 
> ```
> k_diffusion/sampling.py line 10
> ImportError: cannot import name TypeAlias from 'typing' (python3.9/typing.py)
> ```

Did you activate the conda environment after creating it?

> @cosalexelle @eous Is this still a problem for you? I haven't seen anyone else mention this and I know other people have it working.

Unfortunately.

I have some more time today so was planning on going a little deeper to figure out what's going on.
