### ISSUE TITLE
BUG: File names counter does not increment

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#247]
I run this prompt `"a dog" -n 50`
and got 50 images named `000001` followed by random seed number. It's a problem because I can't scroll through them in image viewer (IrfanView) in chronological order.

```
000001.3343649363.png
000001.3251890462.png
```

Instead I propose to increase counter and generate files like:

```
000001.4343649363.png
000002.8821890462.png
000003.943649363.png
000004.0251890462.png
```

I mentioned about this problem in https://github.com/lstein/stable-diffusion/issues/30#issuecomment-1229183071

**Comment by lstein** [comment]
The idea was to group images that were generated with the same prompt together. I think if we change this now, there will be a chorus of people who want the current behavior back. However, I'm open to feedback.

A few questions for clarification:

- Does IrfanView not allow you to sort files in chronological order?
- How is the ability to view in chronological order matter used in your workflow?
- If the format were something like "000001.01.3343649363.png",   "000001.02.943649363.png", etc, would that help you out?

**Comment by MarcusLlewellyn** [comment]
I've been thinking about this myself. When it comes to keeping items in order, I've often favored timestamps. UNIX epoch would be pretty solid, but perhaps not user friendly. So maybe something like: `YYYYMMDD-HM.<seed>`, or `20220831-0230.9379547937`. I shouldn't think sub-second timing would be an issue even for someone running a monster of setup.

**Comment by morganavr** [comment]
@lstein 
```
A few questions for clarification:

Does IrfanView not allow you to sort files in chronological order?
How is the ability to view in chronological order matter used in your workflow?
If the format were something like "000001.01.3343649363.png", "000001.02.943649363.png", etc, would that help you out?
```

> Does IrfanView not allow you to sort files in chronological order?

I don't know. By default it surely is not sorting files by creation date. It sorts them by file name.

> How is the ability to view in chronological order matter used in your workflow?
I use txt2img module to create variations of the same image. I need quick way to compare the most recently generated image with previously generated image. I modified dream.py to automatically open IrfanView as soon as new image is generated. Then I can just slide a mouse wheel to quickly browse through all images in that folder. But with current file naming IrfanView shows not a previous image but the image whose seed number is the closest to the current image and since seed numbers are generated randomly I can't confidently scroll through all images knowing that all images displayed when I slide mouse wheel forward are newer images.

>If the format were something like "000001.01.3343649363.png", "000001.02.943649363.png", etc, would that help you out?

Yes, it would fix the problem. Just tested it on these file names. As you can see you don't even need to add leading 0. IrfanView is smart enough to sort them correctly but I am not sure about other image viewers.
```
000051.04.1799653396.png
000051.01.3018629632.png
000051.100.3018629632.png
000051.1247.3018629632.png
000051.03.1917881035.png
000051.2.2687350527.png
000051.202.2687350527.png
```
