### ISSUE TITLE
txt2img on MPS seed not working of fixed_code not used.

### ISSUE THREAD

**Issue by Vargol** [lstein/stable-diffusion#260]
Using txt2img.txt

python ./scripts/orig_scripts/txt2img.py --prompt 'they were dark and golden eyed' --W 256 --H 256  --n_sample=2 --n_iter 5 --ddim_steps 5 --sed 999

run twice and get 10 different images would expect second set of images to be the same as the first.

I can see two potential fixes, one change the random noise generation in each sampler to use the same fix as fixed_code 

e.g, 

change ldm/models/diffusion/ddim.py   line 197
```
        if x_T is None:
            img = torch.randn(shape, device=device)
        else:
            img = x_T
```
to
```
        if x_T is None:
           if device.type == 'mps':
                img = torch.randn(shape, device='cpu').to(device)
           else:
                torch.randn(shape, device=device)       
        else:
            img = x_T
```

or use something similar to fixed_code and generate the noise in txt2img for each iter and pass it into the sampler.

```
                        if not opt.klms:

                            if not opt.fixed_code:
                                if device.type == 'mps':
                                  start_code = torch.randn([opt.n_samples, *shape], device='cpu').to(device)

                            samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
                                                            conditioning=c,
                                                            batch_size=opt.n_samples,
                                                            shape=shape,
                                                            verbose=False,
                                                            unconditional_guidance_scale=opt.scale,
                                                            unconditional_conditioning=uc,
                                                            eta=opt.ddim_eta,
                                                            x_T=start_code)
                        else:
                            sigmas = model_wrap.get_sigmas(opt.ddim_steps)
                            if start_code:
                                x = start_code
```

I see you've already got something like this for opt.klms...that probably needs the cpu randn for MPS too :-)
I think the later would require less maintenance

**Comment by tildebyte** [comment]
Wrong script: `./scripts/orig_scripts/txt2img.py`

**Comment by Vargol** [comment]
@emmajane1313  I do at the moment, let me checkout the main branch and try

**Comment by Vargol** [comment]
Also with the main branch

**Comment by magnusviri** [comment]
Yes, you have to specify fixed_code for seed to work on MPS. I'm summarizing what other's have said, so this isn't my first-hand knowledge. Basically pytorch doesn't support a consistent seed for MPS yet. --fixed_code causes the script to get the seed from the CPU, which is consistent.

**Comment by Vargol** [comment]
I need to check, but I did start this thread with  potentail fixes, need to see if it still works and the easy fix probably doesn't work for all samplers. As soon as randn is called to fill a MPS tensor then yes it becomes non-deteministic breaking the pattern of random numbers that should follow the seed,

There are also potential bugs in the convolution code that generate infinity values which is probably the cause of the odd blank image.

**Comment by Vargol** [comment]
Just had a quick render, and it seems to work for dim and plms (ignoring that I got a blank image in the second run).
klms I just get blank images as I did before applying my change.
