### ISSUE TITLE
The script cant seem to find the ckpt file on M1

### ISSUE THREAD

**Issue by owen109** [lstein/stable-diffusion#265]
followed all the install instruction and got this error:

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 319, in <module>
    main()
  File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 195, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 30, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'

any ideas on how to fix? thanks!

**Comment by cosalexelle** [comment]
Sometimes the `ln -s model_path models/ldm/stable-diffusion-v1/model.ckpt` doesn't work for me on MacBook M1. Try using Finder to copy/paste the model to the directory listed.

Otherwise, ensure your file names are correct. Browse to the directory using Finder to see if the link/shortcut is working correctly.

**Comment by cosalexelle** [comment]
> followed all the install instruction and got this error:
> 
> Loading model from models/ldm/stable-diffusion-v1/model.ckpt Traceback (most recent call last): File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 319, in main() File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 195, in main model = load_model_from_config(config, f"{opt.ckpt}") File "/Users/owendorsey/stable-diffusion/scripts/orig_scripts/txt2img.py", line 30, in load_model_from_config pl_sd = torch.load(ckpt, map_location="cpu") File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "/Users/owendorsey/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 211, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'
> 
> any ideas on how to fix? thanks!

Sometimes the `ln -s model_path models/ldm/stable-diffusion-v1/model.ckpt` doesn't work for me on MacBook M1. Try using Finder to copy/paste the model to the directory listed.

Otherwise, ensure your file names are correct. Browse to the directory using Finder to see if the link/shortcut is working correctly.

**Comment by owen109** [comment]
the file seems to be there? unless im looking in the wrong place?
<img width="922" alt="Screen Shot 2022-08-31 at 3 15 06 PM" src="https://user-images.githubusercontent.com/30698769/187763774-65c2772b-1949-4f2a-b7c4-bee938051715.png">

**Comment by owen109** [comment]
ah ok it seems like the link is missing i just need to find the original file somewhere, thanks!

**Comment by owen109** [comment]
Do you have any ideas where the original sd-v1-1.ckpt  is located i cant seem to find it?

**Comment by cosalexelle** [comment]
> Do you have any ideas where the original sd-v1-1.ckpt is located i cant seem to find it?

See here: https://huggingface.co/CompVis

You'll want the sd-1-v4-original download (or any of the other original downloads)

**Comment by owen109** [comment]
Great, Thank you
