### ISSUE TITLE
img2img issues after latest update

### ISSUE THREAD

**Issue by cvar66** [lstein/stable-diffusion#267]
So img2img seems to be working again but everything is still being resized improperly even if image dimensions are entered and givin black bars to compensate the aspect ratio. 

Another issue that I find worse is that I noticed my img2img outputs looked much worse than I remembered previously with a lot more noise. So I re ran some old img2img prompts with identical settings and I don't even get the same image anymore. The image I do get is different and has a ton more distortions than previously. 

Could the resizing be causing this? I know if I use the same prompt settings with txt2image but change the dimensions that it will produce a different image sometimes. I just checked and noticed that the resizing happens before the image is decoded. This might be the reason the images look different now. Just a guess.

**Comment by blessedcoolant** [comment]
Yes. Changing the resolution of the input image gives a different generation result.

**Comment by cvar66** [comment]
I re installed 1.12 and there is a pretty big difference in quality, not just a different image. Is there an easy way to just strip all the resizing code out of the latest release?

**Comment by thelemuet** [comment]
I think maybe there are too many fail-safes that make it a bit complicated and prone to bugs? Here is what I would suggest to make things simpler.

`"cool prompt" -W576 -H704`

Resize image to 576*704 regardless of aspect ratio, no black bars.

`"cool prompt" -W576`

Resize image to 576*xxx and keep aspect ratio, no black bars, let it return error if not multiple of 64.

`"cool prompt"`

Use original image untouched. Let it return errors if it doesn't fit into memory or if not multiple of 64.

**Comment by cvar66** [comment]
Agreed. I also think that most people that do want to resize would rather do that post in imaging software anyways.

**Comment by vinyvince** [comment]
Is there any hope to maje the drawing mask better please? It's very slow, capricious, can't do much....  i will also prefer to have the possibility to load a mask ... Cheers everyone, warm my heart to see the world unit for progress, i wish everything could be solved like that...

**Comment by blessedcoolant** [comment]
> I think maybe there are too many fail-safes that make it a bit complicated and prone to bugs? Here is what I would suggest to make things simpler.
> 
> `"cool prompt" -W576 -H704`
> 
> Resize image to 576*704 regardless of aspect ratio, no black bars.
> 
> `"cool prompt" -W576`
> 
> Resize image to 576*xxx and keep aspect ratio, no black bars, let it return error if not multiple of 64.
> 
> `"cool prompt"`
> 
> Use original image untouched. Let it return errors if it doesn't fit into memory or if not multiple of 64.

I think the fail safes are important for a lot of reasons. The current system basically does what you said except that in cases where the ratios dont match, it black boxes.

I've been experimenting a lot with it and I think the ideal solution for images of that nature would be to scale up to fit the given valid size instead of black boxing. This would mean some parts of the original image might get cropped, but for an automated system this is the best we can go.

If people want to not lose that extra crop, then I guess they'll need to manually resize their images (which will anyway make them crop) ... So in a way, scaling up would be the most perfect solution. Because that is what a user would do manually.

**Comment by lkewis** [comment]
> I re installed 1.12 and there is a pretty big difference in quality, not just a different image. Is there an easy way to just strip out all the resizing code out of the latest release?

What happens if you comment out lines 632 + 633 in recent simplet2i.py, is the quality still ending up different compared to 1.12?

**Comment by lstein** [comment]
Pull request #275 adds a switch that lets you turn image rescaling on and off. Do you want to give it a try? However, there's still some resizing that occurs to ensure the image's dimensions are a multiple of 64, and maybe we can see what happens when we don't even do that.

**Comment by cvar66** [comment]
I don't know if I will have time today to try it, but personally I would like an option with no resizing at all, especially if it happens before the image is decoded.

**Comment by lstein** [comment]
The changes are now in. On the CLI, if you provide the switch --fit, the image will be scaled to whatever the width and height are (512x512 by default), while preserving the correct aspect ratio. Without the switch, you will get whatever the init image size is. The WebGUI has a checkbox that does the same thing.
