### ISSUE TITLE
dream.sh fail on M1

### ISSUE THREAD

**Issue by i3oc9i** [lstein/stable-diffusion#273]
with last commit [0433b3d](https://github.com/lstein/stable-diffusion/commit/0433b3d625cd81383360691e6b23ee94991cd0e4)

i get this error

╰─ﬀ python ./scripts/dream.py
* Initializing, be patient...

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Setting Sampler to k_lms
model loaded in 5.80s

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> a smiling face
Traceback (most recent call last):
  File "/Users/ivano/Code/Ai/dream2/./scripts/dream.py", line 543, in <module>
    main()
  File "/Users/ivano/Code/Ai/dream2/./scripts/dream.py", line 103, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "/Users/ivano/Code/Ai/dream2/./scripts/dream.py", line 230, in main_loop
    t2i.prompt2image(image_callback=image_writer, **vars(opt))
  File "/Users/ivano/Code/Ai/dream/ldm/simplet2i.py", line 289, in prompt2image
    torch.cuda.torch.cuda.reset_peak_memory_stats()
  File "/Users/ivano/.miniconda/envs/dream/lib/python3.10/site-packages/torch/cuda/memory.py", line 256, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'

**Comment by owen109** [comment]
Also having this issue

**Comment by magnusviri** [comment]
We [are working on it](https://github.com/lstein/stable-diffusion/pull/268).

**Comment by i3oc9i** [comment]
the brach fix-cuda-reset-stats-error fix the error but then not image are generated

> python scripts/dream.py
* Initializing, be patient...

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Setting Sampler to k_lms
>> model loaded in 5.75s

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> a nice smiling girl
User specified autocast device_type must be 'cuda' or 'cpu'
Are you sure your system has an adequate NVIDIA GPU?
Usage stats:
   0 image(s) generated in 0.00s
   Max VRAM used for this generation: 0.00G

**Comment by Vargol** [comment]
@i3oc9i, thats fixed elsewhere, I hit the some issue last night (UK time) and it was fixed by a change proposed by @toffaletti 

I think that may be been merged, but into the main branch.
