### ISSUE TITLE
FEATURE: Implementation of Compositional Visual Generation

### ISSUE THREAD

**Issue by zoru22** [lstein/stable-diffusion#278]
This is a bit of a parking lot ticket, but among the promising papers, Compositional Visual Generation seems to be compatible with Stable Diffusion, and it would be nice to provide this to end-users.

https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch

**Comment by bmaltais** [comment]
This is exactly what I was wondering we could have one day. The ability to add more details to a generated image by using "additive prompt" vs "averaging" sub-prompt with weight method like the current supported method in this fork.

**Comment by bmaltais** [comment]
There is an actual colab notebook implementing this with stable-diffusion: https://colab.research.google.com/github/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/main/notebooks/demo.ipynb#scrollTo=wt_j3uXZGFAS

This look super fantastic

**Comment by lstein** [comment]
Cool idea. There's a growing feauture wish list at https://github.com/lstein/stable-diffusion/discussions/195. please feel free to add!
