### ISSUE TITLE
FEATURE: Providing a feature to swap the stable-diffusion unet model via Patching

### ISSUE THREAD

**Issue by zoru22** [lstein/stable-diffusion#279]
Another parking lot ticket for discussion, I don't expect or want immediate movement on this:

https://arxiv.org/abs/2207.04316

Providing an implementation or tutorial/guide for swapping out the front UNet layer on SD and then finetuning it, seems likely able to reduce the RAM requirements for users to run the model with minimal performance costs (V100s have 16GB vram, so for prosumer graphics cards like the 3080, it becomes viable to train / finetune on one's own PC).

**Comment by lstein** [comment]
I'd like that too. There's a growing wish list on this repository's wiki if you'd like to add this on.

**Comment by tildebyte** [comment]
Wishlist link https://github.com/lstein/stable-diffusion/discussions/195
