### ISSUE TITLE
Add frontend

### ISSUE THREAD

**Issue by random29** [lstein/stable-diffusion#28]
Hello, thanks for your hard work!

Wanted to ask if you could add frontend from this https://github.com/harubaru/waifu-diffusion repository (it's in scripts folder - called txt2img_gradio.py)

**Comment by lstein** [comment]
Thanks for the suggestion, but I'm not sure that's worth doing now. At some point soon the whole ecosystem will be replaced by interactive image editors that make calls into a stable-diffusion backend. By the time I have understood gradio and have done the implementation, there are going to be so many better solutions!

If there's a developer out there who is versed in gradio and wants to do the implementation, I'd very much welcome a contribution.

**Comment by morganavr** [comment]
Personally I don't see a benefit of GUI over terminal atm. When inpainting feature will be implemented by somebody it would be very nice to have a GUI to paint over image to specify areas that user wants to be redrawn by AI while keeping all other parts of the original image intact.

**Comment by random29** [comment]
Okay, thanks, in that case I guess it's better to wait for interactive image editors
