### ISSUE TITLE
Basic flask api for submitting render requests

### ISSUE THREAD

**Issue by ausbitbank** [lstein/stable-diffusion#284]
Hi! You've been doing great work on this repo, thankyou :)

I made a simple flask api that I jammed into your dream.py so I could submit render requests from my nodejs discord bot.

I don't think it's up to scratch to be integrated as is, and may even be redundant with the --web option but just in case anyone else finds it useful here ya go https://gist.github.com/ausbitbank/1958a72510c0c30d2bd922f5236ee6ad

**Comment by blessedcoolant** [comment]
I already have this on a list of to do things here. #195 

I will make a proper React based UI for the script eventually but at the moment I'm focusing on the functionality. At that stage, I will end up making the Flask API.

But if someone is able to do that before, it'll save me time. So if anyone wants to take that up, feel free and make a PR.
