### ISSUE TITLE
FEATURE: keep history of 5 last used prompts in --web with option to click and set it as current prompt again

### ISSUE THREAD

**Issue by smoke2007** [lstein/stable-diffusion#287]
as title says, i've only just begun to use the web server, i've always used the commandline version while waiting for the web version to catch up.

What I did often in commandline was arrow key up and down, to go back to previously used prompts.

Would it be feasable to add a small history of prompts of the current session (like 5 max) and be able to click them to set them as current prompt again in the web interface?

but don't add to history on every "generate" click, only if it's different from the already contained ones.
I think it should be doable with local storage in browser pretty much.

It's just an extra luxury to have ;)

**Comment by namion** [comment]
In case you aren't aware, you can click any image in the web interface and it will reload the parameters that were used to generate it

**Comment by smoke2007** [comment]
Oh yeah , I hadn't noticed it also sets the prompt, I thought it only set the seed, as I've only done it with an image i've just created.

So yeah , that kinds of works if I reset the seed afterwards.
