### ISSUE TITLE
Show preview of last generated image

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#29]
**What this code does?**
As soon as new image is generated - it will be automatically opened in Irfan image viewer. 
It's a nice way to preview images as they are generated.

**Setup:**
1)  Download IrfanViewer  https://www.irfanview.com/ 
2) Modify simplet2i.py code as shown below

![image](https://user-images.githubusercontent.com/51041813/186142804-4fdbe804-82c5-4e63-8d5c-84745be88dbc.png)

```
# Open IrfanView on last generated image
sd_path = "C:\\aim3\\" # path to main folder of SD (where README.md is located)                                        
subprocess.Popen(["C:\\Program Files\\IrfanView\\i_view64.exe", sd_path + filename.replace("/", "\\")])                
```

**Comment by lstein** [comment]
Nice idea and thanks for the feedback. I think this needs to be an option passed as a command-line argument. There are many different image viewers on many different platforms, so it has to be adjustable by the user.

On my desktop, there's an option to display thumbnails of image files within the filesystem browser. So I just keep a window open on the destination folder and get essentiallly the same thing.

**Comment by morganavr** [comment]
Yes, it needs to be a command line argument. Because sometimes I want IfranView to display last image but other times - I want images to be generated siliently.
