### ISSUE TITLE
Newest update breaks img2img

### ISSUE THREAD

**Issue by cvar66** [lstein/stable-diffusion#294]
tried using img2img on webUI after the latest update. Anytime I try to generate anything I get this error:

File "e:\stable-diffusion\ldm\simplet2i.py", line 635, in _squeeze_image
    return InitImageResizer(image).resize(x,y)
NameError: name 'InitImageResizer' is not defined

Doesn't matter if its a 512 X 512 or a weird aspect ratio. Also checking/unchecking fit to size made no difference.

**Comment by lstein** [comment]
I'm very sorry about that. This is my bad. Will fix shortly.

**Comment by lstein** [comment]
Re-pull. I'm 99.8% sure the problem will be fixed.

**Comment by cvar66** [comment]
Thank you! I know its a lot of work. No need to be sorry!
