### ISSUE TITLE
RealESRGAN not working on M1 (upscaler)

### ISSUE THREAD

**Issue by slk333** [lstein/stable-diffusion#297]
Hi, on Apple M1, Upscaler is not working:
```
Error running RealESRGAN - Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
```

**Comment by tildebyte** [comment]
Is there more output? A complete traceback would be helpful...

**Comment by MischaU8** [comment]
This happens because it detects that you have a CPU and won't load the upscaler:
https://github.com/lstein/stable-diffusion/blob/main/ldm/gfpgan/gfpgan_tools.py#L78

**Comment by slk333** [comment]
> This happens because it detects that you have a CPU and won't load the upscaler: https://github.com/lstein/stable-diffusion/blob/main/ldm/gfpgan/gfpgan_tools.py#L78

Thanks, I think support for the upscaler is really important. I hope the macos fork will support it soon

**Comment by eduardoarinopelegrin** [comment]
How about using realesrgan-ncnn-vulkan? https://github.com/xinntao/Real-ESRGAN/releases
This is from Prog Rock Stable and it works on M1
```
def esrgan_resize(input, id):
    input.save(f'_esrgan_orig{id}.png')
    try:
        subprocess.run(
            ['./realesrgan-ncnn-vulkan', '-i', '_esrgan_orig.png', '-o', '_esrgan_.png'],
            stdout=subprocess.PIPE
        ).stdout.decode('utf-8')
        output = Image.open('_esrgan_.png').convert('RGBA')
        return output
    except Exception as e:
        print('ESRGAN resize failed. Make sure realesrgan-ncnn-vulkan is in your path (or in this directory)')
        print(e)
        quit()
```

**Comment by rcarmo** [comment]
Yep. That works for me if I run it separately on my M1 Pro. Mind that it segfaults when it can't find the model files.

**Comment by slk333** [comment]
it is now working (even though it does not run on MPS yet). closing this issue
