### ISSUE TITLE
Turn the main branch into a kind of "nightly" and move daily dev to an unstable branch

### ISSUE THREAD

**Issue by magnusviri** [lstein/stable-diffusion#298]
What do you think of the idea of turning the main branch into a kind of nightly branch that stays stable for at least 24 hours and moving the daily development to a more unstable branch? This will help new people coming here who are more than likely going to try to get the main branch working.

**Comment by lstein** [comment]
I like that idea. How do I socialize this so that people start making PRs against the development branch?

We also need continuous integration going, but I don’t know how to set that up.

**Comment by magnusviri** [comment]
Add a "Contributing" section to the README that explains the expectations. I see you started a Wiki and I think you said something to me about adding a Mac section in there. I can start doing that. Unfortunately GitHub's wiki's can't be forked so nobody can do pull requests. This is one advantage of README's. The wiki can have multiple pages though. Only editors of this project would be able to make changes to it.

What type of CI are you thinking of? Testing or deployment? Are you thinking of putting this on pypi.org? Someone took the original name already (doesn't look like it was CompVis). If you wanted to be on pypi you'd have to pick a new name and go grab it. I imagine it will be a lot of work to get this as easy to install as `pip install sd-dream` (I guess that's my name vote).

If you want testing I'm guessing we wont be able to use GPU's on GitHub's servers. Maybe this is a cool enough project they'll let us... who knows. We probably want test dream.py by running it through the motions but not actually rendering anything.  So it would need a test mode where it starts up but then exits cleanly if everything's ok.

I can work on these things too. I have actually been thinking of it heavily because of all of the different environments people are trying this on. It would make debugging a lot easier.

**Comment by magnusviri** [comment]
[setting-guidelines-for-repository-contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

**Comment by lstein** [comment]
Good advice. I've just created a development branch and made an announcement in the discussion section. I'll write a contribution section for the README and start adding comments to the PRs advising people to do new ones against development.

For the CI, maybe we can create a dummy base class for T2I that pretends to do the work of text2img and img2img, but just accepts the same arguments and emits mock data for verification that call signatures and logic flow are handled right. I think this is what you suggested above. Over the weekend I'm going to try a refactoring again to clean up simplet2i.py and move functionality into separate modules. This has got to be done before I add inpainting, which is another huge code dump.

I've not done CI and know nothing about pypi. Maybe you'd be willing to take the lead on devising the plan? Obviously not critically important, but nice to have.

**Comment by magnusviri** [comment]
I've done this for another project I've worked on so I will do it. On my branch I've already created a first draft for a [macOS workflow](https://github.com/magnusviri/stable-diffusion/blob/main/.github/workflows/macos12-miniforge.yml) (since it's what I know best). I'm sure it will get an [error](https://github.com/magnusviri/stable-diffusion/actions). I need to figure out how to download the model into the github runner.

Also, I did the pull request to the main branch because it wont do any good anywhere else. The same is true with the github action. It wont do anything unless it's in the main branch.

**Comment by magnusviri** [comment]
Regarding pypi.org, go create an account with them and register the name you want. That's step one. It may be a long time before we get anything there, but getting the name might be important since poachers may take all the good names (stable-diffusion is already taken).
