### ISSUE TITLE
The input line is too long. 

### ISSUE THREAD

**Issue by triviatroy** [lstein/stable-diffusion#300]
This is a known windows issue and related to the PATH but its not clear what file or line is being executed in order to change.

This happened on env create during the pip subprocess line as well.

![image](https://user-images.githubusercontent.com/75331477/188022964-dbbb3226-2f90-4a0a-94f1-e010f6629ef8.png)

**Comment by lstein** [comment]
Can running under a different shell help?

**Comment by lstein** [comment]
Anybody else with this issue or insights into how to solve it?

**Comment by triviatroy** [comment]
Didn't work. 

Uninstalled and reinstalled Anaconda a few times and now my whole cmd & Anaconda prompt shell are broken. Opens & immediately closes.

Probs not SD specific. More likely an Anaconda issue but not sure how to troubleshoot.
