### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by magnusviri** [lstein/stable-diffusion#303]
It would really help if the issues always included some basic information, like GPU type, OS, CPU arch. I've never created an issue template but I can [read about it](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) if it's ok to others to add this.

My main reason for this is because I'm trying to hunt down all of the Mac problems but some issues are vague and I can't tell if they apply to Mac or not.

**Comment by lstein** [comment]
That sounds great. If you can figure out how to do it you certainly have my blessing.

**Comment by magnusviri** [comment]
https://github.com/lstein/stable-diffusion/pull/305

**Comment by magnusviri** [comment]
https://github.com/lstein/stable-diffusion/pull/307 (I had to close the original pull request because I did it from my main branch and I need to do it from a different branch)

**Comment by lstein** [comment]
I moved it in main just now and it seems to be working. Thanks so much for doing this!
