### ISSUE TITLE
API: how to use parameters?

### ISSUE THREAD

**Issue by NikitaSavik** [lstein/stable-diffusion#31]
Sorry if a dumb question, but could you provide extended example of API usage?
e.g. I'd like to generate 10 variations of img2img with escalating weight paramaeter (from 0.2 to 0.8)

**Comment by lstein** [comment]
Sure! I'll add this to the documentation in a day or two (fixing high priority bugs right now).

**Comment by lstein** [comment]
I haven't forgotten this. Just dealing with a lot of great new features that people have volunteered over the past couple days.
