### ISSUE TITLE
Building ldm environment on M1 Pro never ends

### ISSUE THREAD

**Issue by heurihermilab** [lstein/stable-diffusion#310]
Environment: MBP 14", M1 Pro, 16GB, latest OS, running miniforge with a base of Python 3.10.6. Ran conda clean and reset while debugging.

I am following the instructions in README-Mac-MPS.md with little success.  This is unlike the installation I did yesterday, which just worked, so it's likely a configuration issue.

What happens is after executing

```
CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml
```
the process never completes.

interestingly, whenever I've lost patience (T up to 2 hours) and ctrl-Z the process (and, later, kill -9 it), the following is returned:
```
Stopped                 ( __add_sys_prefix_to_path; "$CONDA_EXE" $_CE_M $_CE_CONDA "$@" )
```

A quick search of the folder doesn't turn up CONDA_EXE anywhere in the code, perhaps that's a hint.  My Conda-fu is weak.

I'm likely to try out "Switch to regular pytorch channel and restore Python 3.10 for Macs. (#301)" next in the debugging process, as my previous installation ran 3.10 well enough for txt2img.py, though dream.py didn't seem to work.

**Comment by ideologysec** [comment]
Try this: https://github.com/lstein/stable-diffusion/issues/63#issuecomment-1227849008

**Comment by outcassed** [comment]
this happens when you are updating an existing installation because pip is waiting for user input to confirm overwriting files

instead of `CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml`

try

`PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml`

**Comment by heurihermilab** [comment]
Success!  I followed the instrux from #315 with no trouble.

I'm running into the `cannot import name 'TypeAlias' from 'typing'` issue with both dream.py and txt2img.py, but I think the current problem may be resolved.

**Comment by magnusviri** [comment]
TypeAlias is being discussed [here](https://github.com/lstein/stable-diffusion/issues/302)
