### ISSUE TITLE
Provide prebuilt binaries

### ISSUE THREAD

**Issue by sindresorhus** [lstein/stable-diffusion#314]
The Real-ESRGAN project provides [prebuilt binaries](https://github.com/xinntao/Real-ESRGAN#portable-executable-files-ncnn) which makes it so much easier to get started. It would be amazing if that could be provided here too.

The reality is that it's difficult to get the correct environment set up. Most threads on the internet (for example, Reddit) about Stable Diffusion or any other ML thing end up being a 100+ thread about various Python dependency issues.

**Comment by cosalexelle** [comment]
I second this, if it is possible under the source licenses. I would guess it will depend on getting the main branch stable for a new release first?

**Comment by slk333** [comment]
Yes please, was not able to run Real-ESRGAN and lost many hours on it

**Comment by n00mkrad** [comment]
@nihui makes them, ask her.

Unless someone else here is familiar with NCNN.

**Comment by lstein** [comment]
Just had a look at the [NCNN](https://sourceforge.net/projects/ncnn.mirror/) website. It isn't clear to me that we can use it unless we completely rewrite the ML code to use the NCNN framework. Correct me if I'm wrong.

An alternative would be Docker, which I have more experience (and comfort) with. Would this be helpful? It might be one large image.
