### ISSUE TITLE
Can't pip install realesrgan on M1

### ISSUE THREAD

**Issue by user799595** [lstein/stable-diffusion#316]
Looks like it tries to build numpy from source.

Build output (too long to include here): https://gist.github.com/user799595/7544428976415caa49fc134edaa8cb4d

Related: https://github.com/xinntao/Real-ESRGAN/issues/425

**Comment by yousifa** [comment]
The reason is it requires numpy-1.20.3 which is unsupported with the python version required for this repo.

**Comment by yousifa** [comment]
Here is a temporary fix until cog.yaml file is fixed on GFPGAN's repo.

Clone gfpgan repo and install locally:
```
git clone git@github.com:TencentARC/GFPGAN.git
cd GFPGAN
pip install basicsr facexlib
pip install -r requirements.txt
python setup.py develop
```

Then you can run `pip install realesrgan` successfully.

**Comment by cgodley** [comment]
I was able to switch to python 3.10.4 with no problems:
```diff
diff --git a/environment-mac.yaml b/environment-mac.yaml
index 44cd1ef..c0cc6ca 100644
--- a/environment-mac.yaml
+++ b/environment-mac.yaml
@@ -3,7 +3,7 @@ channels:
   - pytorch-nightly
   - conda-forge
 dependencies:
-  - python==3.9.13
+  - python==3.10.4
   - pip==22.2.2
  
   # pytorch-nightly, left unpinned
```

Then I ran:
`conda env update -f environment-mac.yaml --prune`

**Comment by user799595** [comment]
@cgodley numpy-1.20.3 doesn't seem to work any better with 3.10.4 for me

**Comment by user799595** [comment]
> Here is a temporary fix until cog.yaml file is fixed on GFPGAN's repo.
> 
> Clone gfpgan repo and install locally:
> 
> ```
> git clone git@github.com:TencentARC/GFPGAN.git
> cd GFPGAN
> pip install basicsr facexlib
> pip install -r requirements.txt
> python setup.py develop
> ```
> 
> Then you can run `pip install realesrgan` successfully.

This fixed the installation error for me, thank you.

**Comment by stillmatic** [comment]
try using the requirements.txt setup here: https://github.com/lstein/stable-diffusion/issues/302#issue-1359489755

**Comment by user799595** [comment]
Thanks @stillmatic

Did you ever figure out the `RuntimeError: expected scalar type BFloat16 but found Float` error?

**Comment by stillmatic** [comment]
i'll take a deeper look this weekend, but it's probably something like adding
```python
        if self.device.type in ['mps', 'cpu']:
            scope = nullcontext 
```
to `simplet2i.py`. About 70% sure that's it, if so I'll send a PR to fix
