### ISSUE TITLE
Slow Generation Latest Update

### ISSUE THREAD

**Issue by forwardslashN** [lstein/stable-diffusion#33]
With the latest update adding weights, image generation speed on my machine went from around 12 seconds to 4.5 minutes. Basic prompts ("a cute puppy"), no special parameters added. After updating through git pull, was there some extra step needed? I hope I am not missing something obvious.

**Comment by bmaltais** [comment]
I have not observed any slowdown either on my system.

**Comment by forwardslashN** [comment]
Restarted my pc, closed everything down, and pulled twice more to update the folder. Everything works as expected, exactly 12 second generation. Not sure why it was taking forever. Closing this one for now as it likely was a local issue. Keep up the awesome work.
