### ISSUE TITLE
webui: Add image filename to dream log when using img2img

### ISSUE THREAD

**Issue by cvar66** [lstein/stable-diffusion#332]
I think it would be a great idea to add the image filename to dream log when using img2img. I am trying to recreate some images from last night but I used a bunch of different init images and now I am having problems figuring out which ones I used.

**Comment by lstein** [comment]
Good pickup! That's an inadvertent omission that's easily fixed. Should have it into main within a day or so.

**Comment by lstein** [comment]
I just went to add the feature and it's already there in "main", since August 25. Maybe I'm misunderstanding your request?

**Comment by cvar66** [comment]
When I use the webUI all I get is "initimg": " in the logs, will try from command line and see

**Comment by lstein** [comment]
This is now fixed in the development branch.
