### ISSUE TITLE
FEATURE: Visual analysis tool to see which parts of the image each token influences

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#333]
Very often it is difficult in SD to get exact image you want in your mind by typing the best words to describe what you want.
If only there was a way to see how each word influences what parts of the image - it would be a powerful tool to tweak initial prompt and remove one words or replace them with others if they influence the image not the way you want.

It appears that this tool already exists in Diffusers library and I accidentally read about it in this  [Reddit comment](https://www.reddit.com/r/StableDiffusion/comments/x3qjgt/comment/imrz44m/?utm_medium=android_app&utm_source=share&context=3):

> If you have lots of RAM the [diffusers-interpreter](https://github.com/JoaoLages/diffusers-interpret) is an explainability tool that can show exactly how much each token is beings weighted and which part of the image it is influencing.

Maybe there is a way to port source code from diffusers to lstein repo?

**Comment by lstein** [comment]
We have a variations-generating system that is very close to production, and this should help.

I agree that the prompt explaining tool would be very helpful. Unfortunately it is written for the HuggingFace implementation, which has deviated considerably from the CompViz implementation that this fork is based on. Hence a bit of an undertaking. Not impossible, but not a quick port either. 

We are maintaining a prioritized feature request list in the discussion area. Anyone reading this who thinks it should be a high priority should like this Issue (#333) to indicate your preference.
