### ISSUE TITLE
dream raise ImportError: cannot import name 'TypeAlias' from 'typing' on M1

### ISSUE THREAD

**Issue by i3oc9i** [lstein/stable-diffusion#335]
**Describe your environment**
Mac Studio M1 Ultra 128G

- GPU: mps
- VRAM: 128G
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: main
- Commit: 33936430d0e56228c7c6d310fbc4c094cdaeccb4

**Describe the bug**
dream raise ImportError: cannot import name 'TypeAlias' from 'typing' on M1

**To Reproduce**
conda deactivate
 conda env remove -n ldm-last
 git clone https://github.com/lstein/stable-diffusion.git ldm-last
cd ldm-last
conda clean --yes --all
mkdir -p  models/ldm/stable-diffusion-v1
cd models/ldm/stable-diffusion-v1
ln -s ~/Code/Ai/Models/sd-v1-4.ckpt model.ckpt
cd ../../..
CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml -n ldm-last
conda activate ldm-last
python scripts/preload_models.py
python scripts/dream.py --full_precision

**Expected behavior**
dream prompt

**Screenshots**
python scripts/dream.py --full_precision
* Initializing, be patient...

Traceback (most recent call last):
  File "/Users/ivano/Code/Ai/ldm-last/scripts/dream.py", line 553, in <module>
    main()
  File "/Users/ivano/Code/Ai/ldm-last/scripts/dream.py", line 41, in main
    from ldm.simplet2i import T2I
  File "/Users/ivano/Code/Ai/ldm-last/ldm/simplet2i.py", line 29, in <module>
    from ldm.models.diffusion.ksampler import KSampler
  File "/Users/ivano/Code/Ai/ldm-last/ldm/models/diffusion/ksampler.py", line 2, in <module>
    import k_diffusion as K
  File "/Users/ivano/Code/Ai/ldm-last/src/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/Users/ivano/Code/Ai/ldm-last/src/k-diffusion/k_diffusion/external.py", line 6, in <module>
    from . import sampling, utils
  File "/Users/ivano/Code/Ai/ldm-last/src/k-diffusion/k_diffusion/sampling.py", line 10, in <module>
    from typing import Optional, Callable, TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/Users/ivano/.miniconda/envs/ldm-last/lib/python3.9/typing.py)

**Additional context**

**Comment by user799595** [comment]
https://news.ycombinator.com/item?id=32684850

**Comment by i3oc9i** [comment]
using 3.10.4 does not solve, creation of the environment fail

sed -E 's/python==3.9.13/python==3.10.4/' environment-mac.yaml > /tmp/environment-mac-patched.yml
CONDA_SUBDIR=osx-arm64 conda env create -f /tmp/environment-mac-patched.yml -n ldm-last
...
...
...
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers.git /private/tmp/src/diffusers
  Running command git checkout -q 0c9f5516f34e2bf832fc4a8b77475169fa877fa0
  Running command git clone --filter=blob:none --quiet https://github.com/CompVis/taming-transformers.git /private/tmp/src/taming-transformers
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /private/tmp/src/clip
  Running command git clone --filter=blob:none --quiet https://github.com/Birch-san/k-diffusion.git /private/tmp/src/k-diffusion
ERROR: file:///private/tmp (from -r /tmp/condaenv.lwtqo6li.requirements.txt (line 9)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed

**Comment by i3oc9i** [comment]
i'm going to test the other way and report

(before)

  from typing import Optional, Callable, TypeAlias
(after)
  from typing import Optional, Callable
  from typing_extensions import TypeAlias

**Comment by i3oc9i** [comment]
I confirm that patching ./src/k_diffusion/sampling.py b/k_diffusion/sampling.py solve the issue

diff --git a/k_diffusion/sampling.py b/k_diffusion/sampling.py
index 3df824a..e6ddc6f 100644
--- a/k_diffusion/sampling.py
+++ b/k_diffusion/sampling.py
@@ -7,7 +7,8 @@ import torch
 from torch import Tensor
 from torchdiffeq import odeint
 from tqdm.auto import trange, tqdm
-from typing import Optional, Callable, TypeAlias
+from typing import Optional, Callable
+from typing_extensions import TypeAlias

 from . import utils

**Comment by i3oc9i** [comment]
In my environment I have
pytorch                   1.13.0.dev20220902         py3.9_0    pytorch-nightly
torchvision               0.14.0.dev20220902        py39_cpu    pytorch-nightly

**1 Anubis**
python scripts/orig_scripts/txt2img.py --prompt "Anubis riding a motorbike in Grand Theft Auto cover, palm trees, cover art by Stephen Bliss, artstation, high quality" --ddim_steps=50 --n_samples=1 --n_rows=1 --n_iter=1 --seed 1805504473 --fixed_code
![grid-0001](https://user-images.githubusercontent.com/4766500/188251845-ec14bb74-d1eb-4108-ab5a-ff0f5dce945b.png)

**2/ Dream.py**
I'm not able to get the same image using the same seed

**Comment by user799595** [comment]
> In my environment I have pytorch 1.13.0.dev20220902 py3.9_0 pytorch-nightly torchvision 0.14.0.dev20220902 py39_cpu pytorch-nightly
> 
> **1 Anubis** python scripts/orig_scripts/txt2img.py --prompt "Anubis riding a motorbike in Grand Theft Auto cover, palm trees, cover art by Stephen Bliss, artstation, high quality" --ddim_steps=50 --n_samples=1 --n_rows=1 --n_iter=1 --seed 1805504473 --fixed_code ![grid-0001](https://user-images.githubusercontent.com/4766500/188251845-ec14bb74-d1eb-4108-ab5a-ff0f5dce945b.png)
> 
> **2/ Dream.py** I'm not able to get the same image using the same seed

Sick Anubis.

https://github.com/lstein/stable-diffusion/issues/317

**Comment by i3oc9i** [comment]
ok I wiill follow #317 for seed in dream.py issue
