### ISSUE TITLE
Support for AMD GPUs using HIP

### ISSUE THREAD

**Issue by erkinalp** [lstein/stable-diffusion#338]
**Is your feature request related to a problem? Please describe.**
Currently does not work on AMD GPUs.

**Describe the solution you'd like**
Use Radeon Open Compute and HIP to support AMD GPUs.

**Describe alternatives you've considered**
*none*

**Additional context**
HIP code can be generated by mechanically translating from CUDA.

**Comment by lstein** [comment]
I don't know whether any of the collaborators on this project currently have access to AMD GPUs with HIP. Is this something you might be able to work on yourself? We would welcome your contributions.

**Comment by erkinalp** [comment]
I have an RX 5500 XT. I could try working on this. Also to mention, for RX 6xx0, there is https://github.com/AshleyYakeley/stable-diffusion-rocm/ .

**Comment by rabidcopy** [comment]
I'm not sure how your repo differs from other forks such as https://github.com/AUTOMATIC1111/stable-diffusion-webui but I have been able to use it just fine on my RX 570. (albeit with a bit of work as AMD dropped official ROCM support for it quite a while back) I don't think there's necessarily anything special that has to be done for it to work. I just think there's a lot of unfamiliarity with AMD's support for CUDA through ROCM as it seems to be exclusive to Linux users. (and possibly WSL/Docker users on Windows) I may try your repo out shortly and see if I can get it running or if any meaningful errors crop up.
