### ISSUE TITLE
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'

### ISSUE THREAD

**Issue by putuoka** [lstein/stable-diffusion#34]
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by lstein** [comment]
After conda activating the "ldm" environment, and changing to the stable-diffusion directory run:
~~~~
python scripts\preload_models.py
~~~~
This only needs to be done once. The reason for this is that the original source code downloads these models on a just-in-time basis. However, my university's GPU systems are firewalled and so this step fails. To make it easier for everyone, I decided to have a mandatory preload which caches the required files locally. (It also has the effect of removing about two pages worth of warnings when the CLIP tokenizer is loaded!)

Let me know if this solution does or doesn't work for you. I'll keep the issue open until then.

**Comment by VictorJulianiR** [comment]
if I have installed using the win installation, i don't have this script to run, what should i do?
