### ISSUE TITLE
Dream.py process unexpectedly killed while initializing

### ISSUE THREAD

**Issue by adriandersen** [lstein/stable-diffusion#342]
**Describe your environment**
- GPU: cuda
- VRAM: 8
- CPU arch: x86
- OS: Linux (WSL)
- Python: Anaconda

**Describe the bug**
```> python3 scripts/dream.py                                                                                                                                                           
* Initializing, be patient...

>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
[1]    9301 killed     python3 scripts/dream.py 
```

**Comment by lstein** [comment]
Is it possible that you are running out of main memory (RAM, not VRAM)? During model loading, the underlying AI library will transiently use up to 9G of RAM before settling down into the 4-5G range.

If you do have sufficient RAM, then try running "ulimit -a" and looking at the "max memory size" setting to see if perhaps it is set to a limited amount.

**Comment by adriandersen** [comment]
The VmmemWSL-process seems to use about 6-7 GB of ram before the process is shut down. According to Task Manager in Windows i reach about 85% memory usage, not sure if that is accurate, but if it is it doesnt seem like i run out of memory.

ulimit -a outputs the following information;
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       31678
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  64
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 31678
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```

**Comment by tildebyte** [comment]
Could be Windows doesn't like WSL using that much RAM that quickly... 🤔

I'm not familiar with how Windows manages WSL RAM usage - it's possible that it's like a "standard" virtual machine, i.e. it has a hard limit on RAM when the environment is created.

**Comment by EvanMath** [comment]
I have the same issue. Did you solve it?

**Comment by gmthedoc** [comment]
I have the usual problem if I try to run the current version on Colab Free and it is the OS killing the process.
I haven't had a chance to try, but in this case increasing the ram reserved for WSL might solve the problem. [Here](https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/) is a guide on how to do it.
I hope it can be useful.

**Comment by EvanMath** [comment]
I tried it but it didn't work. Ultimately, I installed it on Windows, and ran perfectly!

**Comment by artmen1516** [comment]
> I have the usual problem if I try to run the current version on Colab Free and it is the OS killing the process. 

My PR with colab improvements and fixes https://github.com/lstein/stable-diffusion/pull/422 was just merged to development branch,
until development is merged to main, colab shortcut will redirect to previous version, please use this link in the meantime.

https://colab.research.google.com/github/lstein/stable-diffusion/blob/development/Stable_Diffusion_AI_Notebook.ipynb
