### ISSUE TITLE
ANNOUNCE: Release 1.13

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#343]
Hi All,

Nightly release 1.13 is now available in the "main" branch. It adds the following features:

  - Support image variations (see  VARIATIONS.md) ([Kevin Gibbons](https://github.com/bakko) and many contributors and reviewers)
  - Supports a Google Colab notebook for a standalone server running on Google hardware [Arturo Mendivil](https://github.com/artmen1516)
  - WebUI supports GFPGAN/ESRGAN facial reconstruction and upscaling [Kevin Gibbons](https://github.com/bakkot)
  - WebUI supports incremental display of in-progress images during generation [Kevin Gibbons](https://github.com/bakkot)
  - A new configuration file scheme that allows new models (including upcoming stable-diffusion-v1.5) to be added without altering the code. ([David Wager](https://github.com/maddavid12))
  - Can specify --grid on dream.py command line as the default.
  - Miscellaneous internal bug and stability fixes.
  - Works on M1 Apple hardware (several contributors, but particular thanks to [James Reynolds](https://github.com/magnusviri) )
  - Multiple bug fixes.

**Comment by essyd** [comment]
I think this may have broken img2img. Spat out this errror:


```
Exception occurred during processing of request from ('127.0.0.1', 51402)
Traceback (most recent call last):
  File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/http/server.py", line 413, in handle_one_request
    method()
  File "/Users/x/Documents/stable-diffusion/ldm/dream/server.py", line 177, in do_POST
    self.model.prompt2image(prompt,
  File "/Users/x/Documents/stable-diffusion/ldm/simplet2i.py", line 378, in prompt2image
    x_T = self._get_noise(init_img,width,height)
  File "/Users/x/Documents/stable-diffusion/ldm/simplet2i.py", line 612, in _get_noise
    return torch.randn_like(init_latent, device='cpu').to(self.device)
NameError: name 'init_latent' is not defined
```

**Comment by essyd** [comment]
> I think this may have broken img2img. Spat out this errror:
> 
> ```
> Exception occurred during processing of request from ('127.0.0.1', 51402)
> Traceback (most recent call last):
>   File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 683, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/socketserver.py", line 747, in __init__
>     self.handle()
>   File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/http/server.py", line 425, in handle
>     self.handle_one_request()
>   File "/Users/x/miniforge3/envs/ldm2/lib/python3.9/http/server.py", line 413, in handle_one_request
>     method()
>   File "/Users/x/Documents/stable-diffusion/ldm/dream/server.py", line 177, in do_POST
>     self.model.prompt2image(prompt,
>   File "/Users/x/Documents/stable-diffusion/ldm/simplet2i.py", line 378, in prompt2image
>     x_T = self._get_noise(init_img,width,height)
>   File "/Users/x/Documents/stable-diffusion/ldm/simplet2i.py", line 612, in _get_noise
>     return torch.randn_like(init_latent, device='cpu').to(self.device)
> NameError: name 'init_latent' is not defined
> ```

Fixed this:

Replaced simplet2i.py with https://github.com/lstein/stable-diffusion/blob/dd2af3f93c69edea0c8a5c9ad4bc40c9b0be6a5b/ldm/simplet2i.py

Replaced dream.py with https://github.com/lstein/stable-diffusion/blob/2d65b03f05c884c4cc5ca5d2df32f249cf267cfb/scripts/dream.py

(Running on an M1 Max)

**Comment by bakkot** [comment]
https://github.com/lstein/stable-diffusion/pull/353 should fix the img2img issue.

**Comment by thipokKub** [comment]
It seems like [xinntao/Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) only support `cuda`, when running on `mps` device the webui didn't return any image. Is it possible to enable optional `cpu` version for `mps` device or disable it altogether?

**Comment by tusharbhutt** [comment]
Hi, the Colab is not launching the Xterm.  Google throws a very helpful "unknown error" message

**Comment by artmen1516** [comment]
> Hi, the Colab is not launching the Xterm. Google throws a very helpful "unknown error" message

Hey @tusharbhutt, just launched a fix using the lastest stable-diffusion release, please see: #422
