### ISSUE TITLE
Add a non-interactive mode to dream.py

### ISSUE THREAD

**Issue by magnusviri** [lstein/stable-diffusion#352]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a non-interactive mode to dream.py. This will make it easier to test. It also enables running large batches of renders on multiple machines using automation and remote management tools like Ansible.

**Describe alternatives you've considered**
The alternative is to use txt2img for testing.

**Comment by bakkot** [comment]
There is already [--from_file](https://github.com/lstein/stable-diffusion#reading-prompts-from-a-file) (which can also read from stdin). If that's not what you're looking for, can you describe what you're looking for more precisely?

**Comment by magnusviri** [comment]
Ok, I feel silly. I was looking at the usage and saw "--from_file" but didn't realize that is what I wanted. After I submitted I tried it and yes, it's what I want. Closing.
