### ISSUE TITLE
NameError: name 'init_latent' is not defined

### ISSUE THREAD

**Issue by magnusviri** [lstein/stable-diffusion#356]
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOS
- Python: Anaconda

**Describe the bug**
At some point get_noise was moved from here

https://github.com/lstein/stable-diffusion/blame/fe5cc792495ec046092227c956c28bfcc34c6d7b/ldm/simplet2i.py#L349

to here

https://github.com/lstein/stable-diffusion/blame/c22c3dec562821e646fa0ec9a56d5969f4011479/ldm/simplet2i.py#L612

And that broke the scope for init_latent. I'd try to fix it myself but I ran out of time.

**Comment by lstein** [comment]
Looking into it now.

**Comment by bakkot** [comment]
https://github.com/lstein/stable-diffusion/pull/353#issuecomment-1236240910 has a fix.

**Comment by magnusviri** [comment]
I could be wrong but the fix might actually be a step backwards. The code in that area has a kind of similarity and although the patch fixes the bug, it makes it different enough that it isn't as easy to read the code. I think we should just move the function back where it was. Unless moving the function was required for something else. If that's the case, then the patch (or one like it) is the best solution.

**Comment by lstein** [comment]
I take the blame for moving the function. It was nested inside another function's scope, and I find it hard to read the code when there's too much nesting. Another reason I don't like these things is that I don't have a good feel for python's scoping rules yet, and this is what bit me.

It's probably safest to move the function back into its nested scope for the time being. I've just rewritten the whole section in the refactor branch anyway. @bakkot and @magnusviri could one of you take care of merging into a bug fix branch, and I'll take a quick look and merge into main to patch it?

There's also a regression in memory usage, dang it.

**Comment by bakkot** [comment]
I won't be able to do a merge for the next twelve hours or so, so if someone else gets to it first go for it.

**Comment by lstein** [comment]
No problem. Only crazy people are up this late.

**Comment by magnusviri** [comment]
LOL, am I crazy? Although I'm not quite sure what you're asking. Do you want one of us to fix it real quick?

**Comment by lstein** [comment]
No, I was just making fun of myself!

Nobody needs to do anything right now.

**Comment by lstein** [comment]
I think this is fixed now. I made a similar change to the refactor-simplet2i branch, and just waiting for confirmation that nothing is broken to merge this into development and ultimately main.
