### ISSUE TITLE
add LDSR upscale please :)

### ISSUE THREAD

**Issue by vinyvince** [lstein/stable-diffusion#357]
Hello guys... This upscale option will be handy... superior result

**Comment by tildebyte** [comment]
Do you have a link to a relevant repo or at least research?

**Comment by vinyvince** [comment]
Hello , im afraid i can't be as precise as i wish i could but here's some information:

LDSR

Quadruple your resolution using Latent Diffusion, to install:

    Git clone https://github.com/devilismyfriend/latent-diffusion into your stable-diffusion-main/src/ folder
    Rename latent-diffusion-main folder to latent-diffusion
    If on windows: run download_models.bat to download the required model files
    Otherwise to manually install the model download [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1) and rename last.ckpt to model.ckpt
    Place both under stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/
    Make sure you have both project.yaml and model.ckpt in that folder and path.
    LDSR should be wokring now.

then you could try it online there: 

https://replicate.com/nightmareai/latent-sr

**Comment by tildebyte** [comment]
It's [LDSR.py](https://github.com/devilismyfriend/latent-diffusion/blob/main/LDSR.py) from the linked repo.

The Replicate demo examples seem very impressive

**Comment by n00mkrad** [comment]
It's pretty great, just very slow - around 3 minutes per 640x640 image on an RTX 3090.

**Comment by vinyvince** [comment]
This one is not slow and i like it better
https://github.com/jquesnelle/txt2imghd

**Comment by tildebyte** [comment]
That's really interesting - some very nice results.

We'll need to wait and see what happens (in *this* repo) with the incoming memory optimizations which allow for larger generations - folks are already describing a two-step workflow like "txt2img@512x512 -> img2img@much larger res" which doesn't yield any of the upscale artifacts usually seen, but also works around the limitations of trying to generate very large resolution images from a model trained at 512x512.

Once the internals are in place, it shouldn't be too hard to turn that into a one step process driven by a single command.

**Comment by vinyvince** [comment]
I did tried it. On like a aerial picture, kind of heightmap or google map,  got great result, couldn't notice any break where it split the image . Possibly on another picture as well, can't remember, speed was the same as the cost of 4 iterations , or something in this idea...

**Comment by travco** [comment]
Embiggen (rough equivalent to txt2imghd with some improvements) is currently on the dev branch. Should be what you're looking for.
