### ISSUE TITLE
Add prompt that created the image to the image metadata

### ISSUE THREAD

**Issue by SpeedOfSpin** [lstein/stable-diffusion#368]
Sorry about that :-(

**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**
I was thinking that when I produce a lot of images it would be useful to have the prompt and parameters I used embedded in the image metadata itself so that I can always recreate it as long as I have the image. I know the log file has this information as well but I think to have it with the image would mean it would never get lost.

**Describe alternatives you've considered**
I thought about using the log file but what if I move the image somewhere else or the log file is deleted. 

**Additional context**
No additional context apart from this repo is amazing!!

**Comment by tildebyte** [comment]
Please actually fill out the template above.

Where it says `A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]`,  **you are supposed to replace that with useful information**. Same for the other items.

**Comment by SpeedOfSpin** [comment]
> Please actually fill out the template above.
> 
> Where it says `A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]`, **you are supposed to replace that with useful information**. Same for the other items.

Sorry about that. I have updated the original text. Thanks again.

**Comment by bakkot** [comment]
The prompt and parameters are already embedded in the image metadata. There's a script which can retrieve them at `scripts\ images2prompt.py`. This is documented in [the readme](https://github.com/lstein/stable-diffusion#interactive-command-line-interface-similar-to-the-discord-bot).

**Comment by SpeedOfSpin** [comment]
Ahh ok sorry to waste your time. I will be more careful next time. Thanks again.
