### ISSUE TITLE
Dream prompt input processing doesn't accept single quotes

### ISSUE THREAD

**Issue by Cubox** [lstein/stable-diffusion#37]
Hi,

While running the dream.py script with a file containing the input prompts, I saw that having a ' will skip the prompt.
The error is "No closing quotation"

I'm unsure if this is normal, or unintended.

Anyways, thanks for the script, it's great! I'd love to see a replica of the bot, so it could be self-hosted and run on my own server, allowing my friends to use it

**Comment by lstein** [comment]
It's a parser problem. I will fix, but in meantime you can backlash escape the quote like this: **it\'s**

**Comment by Cubox** [comment]
Thanks!

**Comment by bmaltais** [comment]
You can also surround the prompt in ""

**Comment by lstein** [comment]
Fixed.
