### ISSUE TITLE
Python 3.10.x needed instead of the Python 3.9.13 from environment-mac.yaml

### ISSUE THREAD

**Issue by turboooooo** [lstein/stable-diffusion#372]
I have followed the instructions, but it would end up giving errors. I figured Python 3.10 or greater is required, but the conda enviroment will be created with python 3.9.13.

Changing the python version to 3.10 in environment-mac.yaml does the trick for me.

**Comment by stillmatic** [comment]
what errors do you see?

**Comment by turboooooo** [comment]
None anymore as creating the enviroment with Python 3.10.x works fine. Just following the directions I ended up with the screen full of errors before. If the errors are important: Is the history logged on macos by default and if so, where?

**Comment by i3oc9i** [comment]
- main branch use python 3.9.3 and pytorch nightly (1.13.0.dev202209xx)
- development branch use python 3.10.5 with pythorch 1.12.1

both work install fine on Mac M1 using miniconda as explained in the [README-Mac-MPS.md](https://github.com/lstein/stable-diffusion/blob/development/README-Mac-MPS.md)

Perosnally I do the following to installENV=dream

```
ENV=ldm
conda env remove -n ${ENV}
rm -rf ./${ENV}
git clone https://github.com/lstein/stable-diffusion.git ${ENV}
cd ${ENV}
conda clean --yes --all
mkdir -p models/ldm/stable-diffusion-v1
cd models/ldm/stable-diffusion-v1
ln -s ~/Code/Ai/@Stuffs/models/sd-v1-4.ckpt model.ckpt
cd ../../..
PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml -n ${ENV}
conda activate ${ENV}
```

**Comment by lstein** [comment]
We are likely going to require Python 3.10 on all platforms. Right now there are some performance issues with the pytorch-nightly modules for Mac M1, but this should be resolved soon.

**Comment by i3oc9i** [comment]
@lstein 

I have instantiated two separates conda environments, one is on the Revision 1.13 (1.13.0.dev202209xx), the other is on the development branch (1.12.1) , and I dont have remarked any difference when I run my prompts.

An image of 512x512 images with 50 samples takes  22sec on my Mac Studio Ultra.

I can do more specific test if you need.
