### ISSUE TITLE
add variations model (link included)

### ISSUE THREAD

**Issue by nicolai256** [lstein/stable-diffusion#376]
I found this repo today and I was wondering if it could be added to the dream.py script
it's a custom model + script to create variations of images without prompt

**link to the repo**
https://github.com/justinpinkney/stable-diffusion#readme

**Comment by lstein** [comment]
Thanks for sending. There's a wishlist for new features in the Discussion, and I've added your request and link.

**Comment by morganavr** [comment]
Anybody can try this model online at https://47725.gradio.app/
