### ISSUE TITLE
I made a new GUI design for SD

### ISSUE THREAD

**Issue by netsvetaev** [lstein/stable-diffusion#379]
Hi! 
I want to stylize GUI a bit. I made some templates in Sketch in 1 hour — with bigger text fields, bigger buttons, good mobile version. For most of them you only need to change CSS, but I’m designer myself and I need help with coding. If someone want to do this, I will provide full UI kit.
I would like to add more deep changes in UI in future, especially in mobile version. What do you think?

### Desktop version
![mobile-diffusion-desktop](https://user-images.githubusercontent.com/83028930/188340654-09d431aa-7697-4190-9df5-14f5d223007c.png)

### Mobile version
![mobile-diffusion-01](https://user-images.githubusercontent.com/83028930/188340646-0c0cb2ea-5a27-4133-a29c-9b8d2c6f3a2e.png)

**Links**
**Mobile version**
[Mobile Diffusion UI](https://www.dropbox.com/s/55l35r1doq1eds7/mobile-diffusion-01.png?dl=0)
[Mobile Diffusion UI — scale edit](https://www.dropbox.com/s/43zr8xgzzjvz2ge/mobile-diffusion-02.png?dl=0)

**Desktop UI**
[Desktop UI for SD](https://www.dropbox.com/s/3h0g5dvd6bly5mu/mobile-diffusion-desktop.png?dl=0)

**Sketch source**
[Source](https://www.dropbox.com/s/6vq33wexatcwev0/mobile-diffusion.sketch?dl=0)

**Comment by netsvetaev** [comment]
Current version

![Screenshot 2022-09-05 at 02 31 07](https://user-images.githubusercontent.com/83028930/188340847-1cb5dc6b-faec-4752-958f-abc4e6c9209e.png)

![photo_2022-09-05 02 53 34](https://user-images.githubusercontent.com/83028930/188340888-13ff5fd9-fef0-4d18-8488-113ebea5416a.jpeg)

**Comment by lstein** [comment]
I do appreciate good visual design and would be happy to see these changes implemented. Indeed, last week we had a pull request that would have brought in a whole theming system, but unfortunately at that point the code was changing so fast that it couldn't be pulled in easily.

If someone reading this would like to pitch in to contribute the CSS and HTML necessary to implement @netsvetaev 's design, just drop me a line, or go ahead and make a pull request.

**Comment by lstein** [comment]
Oh, I'd add the what I **really** would love to see in an improved Web GUI is the ability to drag-and-drop images to load up the initial and mask images. They could be converted into thumbnails and displayed as reference points. So cool.

**Comment by heurihermilab** [comment]
It looks very good.  About the only thing I'd like to add (and this has been brought up multiple times in an adjacent thread) is a reset button for the img2img file selection.

**Comment by netsvetaev** [comment]
> It looks very good. About the only thing I'd like to add (and this has been brought up multiple times in an adjacent thread) is a reset button for the img2img file selection.

I'd thought about it. Seems it just need to be in another tab, before txt2img. User must choose first between txt2img and img2img, then we will show options related to each separately. And instead of img2img after txt2img we can add esrgan and gfpgan options, them are universal for both txt2 and img2. 

But that's already looks like complete rework of UI, it will took some time from coder too (right now I can edit CSS only, but part of code is in JS, don’t know why). Later this week I’ll give more or less complete UI kit with some comments about how it must work.

**Comment by tildebyte** [comment]
Please keep in mind that there is a TON of work to be done on the *new* web UI - our resources might be better spent helping [psychedelicious](https://github.com/psychedelicious) with that work

**Comment by netsvetaev** [comment]
> Please keep in mind that there is a TON of work to be done on the _new_ web UI - our resources might be better spent helping [psychedelicious](https://github.com/psychedelicious) with that work

wow! React is better, of course. His version looks more horizontal oriented, it also good for desktops. Maybe you’re right.

**Comment by tildebyte** [comment]
> more horizontal oriented, it also good for desktops

**Comment by netsvetaev** [comment]
> IIUC, they're planning an adaptive design so it will look good on mobile or wherever (pretty sure that's the wrong term, but you get the idea)

Well, what I want to do is complete design, including mobile, tablet and desktop version. I mean, «adaptive will look good» is not a magic thing, it is a result of UI design :-)  
I will help with it, but on react it will be a way better and faster. Thank you!

**Comment by lstein** [comment]
@netsvetaev I'm cleaning up the issues and closing this one for now. I would very much welcome your participation in the design of the new web interface. I suggest that you work on the visual design wireframes and mockups and post them in the Discussion section as an attachment. Please mention @psychedelicious in your posting so that they are aware, and hopefully you two can work together to refine and implement the UI.
