### ISSUE TITLE
web: allow outdir to be set when running --web mode

### ISSUE THREAD

**Issue by carbocation** [lstein/stable-diffusion#383]
In dream.py, the [outdir is created whether run as a command line app or a web app](https://github.com/lstein/stable-diffusion/blob/751283a2de81bee4bb571fbabe4adb19f1d85b97/scripts/dream.py#L69-L71). 

However, the outdir is only respected [if run as a command line app](https://github.com/lstein/stable-diffusion/blob/751283a2de81bee4bb571fbabe4adb19f1d85b97/scripts/dream.py#L103-L106). It would be nice if --outdir were respected from the web app as well.

**Comment by thealanle** [comment]
I submitted a fix (PR #373), which gets dream_web_log.txt and output and intermediate images working with --outdir in the web app. Note that the --prompt_as_dir argument doesn't work with the web app yet.
