### ISSUE TITLE
img2img producing low quality results on ARM64 Mac

### ISSUE THREAD

**Issue by master131** [lstein/stable-diffusion#384]
**Describe your environment**
- GPU: mps
- VRAM: 8GB
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: main
- Commit: 751283a2de81bee4bb571fbabe4adb19f1d85b97

**Describe the bug**
Specifying an init-image on M2 Mac is producing low quality results that do not resemble the prompt or contain artifacts.

**To Reproduce**
- Install stable-diffusion for Mac as per the instructions here: https://github.com/lstein/stable-diffusion/blob/main/README-Mac-MPS.md
- Activate the ldm environment and run the following command to launch dream.py:
`python3 scripts/dream.py --full_precision`
- Attempt to use img2img to generate another image based on seed image (modified sample from CompVis repo) and prompt:
`"A fantasy landscape, trending on artstation" --init_img ../Downloads/sketch-mountains-input-resized.jpg --strength 0.8 -W256 -H256`
Note: Increase the step size to 100 does not improve results.

**Expected behavior**
A fantasy landscape image that follows the layout of the input image.

**Screenshots**
See input image below:
![sketch-mountains-input-resize](https://user-images.githubusercontent.com/1592009/188405224-056e57c9-aa8c-4db0-9e34-e5d048c30031.jpg)

And examples of the results:
![000023 2832977284](https://user-images.githubusercontent.com/1592009/188405295-68a6e687-e353-4930-873d-ba377a7e6d52.png)

![000024 1586134644](https://user-images.githubusercontent.com/1592009/188405317-d7eb343f-0621-4ea4-9e59-708b43e6b50f.png)

Is anyone able to assist, perhaps I am doing something wrong. I've tried to specify the plms sampler but it is always falling back to DDIM.

`>> sampler 'plms' is not yet supported. Using DDIM sampler`

Note that txt2img is working fine on my M2 Mac, even though it falls back to DDIM as well.

**Comment by manugarri** [comment]
I have noticed running the same parameters/input/prompt here than at the original google collab yields way worse results. Is it because of constraints in input size running locally (input image 512x512) versus running on tpus (input image 1024x1024)?

**Comment by master131** [comment]
Perhaps it is related to resolution; I kept the image small due to resource constraints and to make the image generate faster - will try a larger image later and see what happens.

**Comment by lstein** [comment]
I've noticed that increasing the step numbers helps improve sketch->image considerably. Also try changing the sampler.

If we are seeing consistently lower-quality images when performing apples to apples comparisons (same image size, sampler, scale, steps) then this is a bug we need to track down.

**Comment by manugarri** [comment]
```Also try changing the sampler.```
Which sampler would you think performs the best?

**Comment by manugarri** [comment]
Side note, increasing the steps to 200 indeed makes the image more faithful to the sketch IMHO
![image](https://user-images.githubusercontent.com/3670355/188447919-5ba27cba-9f24-4c87-b766-472b898b408e.png)

**Comment by lstein** [comment]
> `Also try changing the sampler.` Which sampler would you think performs the best?
> 
> For what i see DDIM is the default and some are not supported yet? ![image](https://user-images.githubusercontent.com/3670355/188447008-93b22fed-697b-4878-861d-2b6900b1469e.png)

Sorry about that stupid remark. Indeed, only the DDIM sampler is supported for img2img. I think something has indeed changed between this fork and the CompViz original. I also note that you need a large number of steps in order to get decent results from inpainting.

@bakkot, I think this is a place where your expert eye is needed to identify an inadvertent change to the handling of steps and strength.

**Comment by bakkot** [comment]
> @bakkot, I think this is a place where your expert eye is needed to identify an inadvertent change to the handling of steps and strength.

I get identical (crappy) output for the given 256x256 input image on the latest commit on `main` as on 7cb5149a02c0a22b63c44d1220d0c05013aefa30, which is approximately the beginning of the fork. And I'm using an Nvidia card, so it's not the architecture. So I don't think this is a regression. It seems that img2img just doesn't work very well with small images, and never has.

**Comment by Raymonf** [comment]
Yup, this is the expected behavior with lower resolutions.

**Comment by master131** [comment]
Thanks guys, it does appear related to resolution - I tried again with a 512x512 input and output and got a better result:

`"A fantasy landscape, trending on artstation" --init_img ../Downloads/sketch-mountains-512.jpg --strength 0.8 -W512 -H512 -s100`

![000027 1777662352](https://user-images.githubusercontent.com/1592009/188538266-93d6a39e-9dcf-4027-9eed-50c3a9b38d8c.png)
