### ISSUE TITLE
Runtime error: CUDA out of memory

### ISSUE THREAD

**Issue by ArtificialHuman007** [lstein/stable-diffusion#385]
I feel like I've jumped through so many hoops (not being a programmer or having experience) and I finally feel I'm at the last stage and says some memory issue on startup. I have 16gb ram GTX 1650ti I don't understand can anyone help? This is the log of when I run the final command:

>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "C:\Users\PoopF\stable-diffusion\scripts\dream.py", line 633, in <module>
    main()
  File "C:\Users\PoopF\stable-diffusion\scripts\dream.py", line 92, in main
    t2i.load_model()
  File "c:\users\poopf\stable-diffusion\ldm\simplet2i.py", line 592, in load_model
    model = self._load_model_from_config(config, self.weights)
  File "c:\users\poopf\stable-diffusion\ldm\simplet2i.py", line 666, in _load_model_from_config
    model.to(self.device)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 109
, in to
    return super().to(*args, **kwargs)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 907, in to
    return self._apply(convert)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "C:\Users\PoopF\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 3.19 GiB already allocated
; 1.70 MiB free; 3.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_
size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Can anybody help solve this problem? Also weirdly it says 4.00 GiB total capacity but checking in settings I have 16.

**Comment by lstein** [comment]
You're right - this crash is happening just before the system finishes loading the machine learning model and before it accepts its first generation command. Do you by any chance have multiple GPU devices in your system? It may be that the underlying torch library is picking the wrong one. The output of the command. "nvidia-smi" will help debug this.

**Comment by matteodefelice** [comment]
I have the same problem, this is the output from `nvidia-smi`: 
```
(ldm) C:\Users\matte\local_work\stable-diffusion>nvidia-smi
Mon Sep  5 13:41:38 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.72       Driver Version: 512.72       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   61C    P8     6W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by ArtificialHuman007** [comment]
I don't think I have multiple GPU's although it's a gaming laptop I'm not sure. This is what I got from the output
`| NVIDIA-SMI 457.63       Driver Version: 457.63       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 165... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8     6W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

**Comment by ArtificialHuman007** [comment]
Thanks for the help by the way. I'm not great with code and this kind of stuff, but this technology is too interesting not to try to learn!

**Comment by lstein** [comment]
nvidia-smi is indicating that both of you have GPUs with 4 GB of memory (the key value is "4096MiB" in the second row) . This is below what is needed to run this fork of stable diffusion. So what to do next?

1. If your GPUs really do have more than 4GB, then this is a driver bug and you need to do an update of the nvidia drivers on your system.
2. You could try one of the other forks that have implemented aggressive memory optimization. The most widely used one is https://github.com/basujindal/stable-diffusion
3. You *might* be able to get this fork running on a 4GB card if you reduce your graphical requirements by closing windows and other running applications that use the GPU.

Let me know what you find out and post back here.

**Comment by matteodefelice** [comment]
fantastic, thank you for the support. I apologise I didn't understand that 6 GB was the minimum requirement! I am trying now with the build you suggested and it is working!

**Comment by tildebyte** [comment]
@ArtificialHuman007;

> in settings I have 16

It's possible that this is a "shared video memory" number, which is not useful for this kind of work (as mentioned, the output from nvidia-smi is the "real" number).

**Comment by ArtificialHuman007** [comment]
Hi, I know I may sound stupid, but I really do think I have more than 4GB, I made sure to specify that I would have 16 before purchase. When I run    & "C:\Program Files\Git\usr\bin\winpty.exe" python scripts\dream.py    task manager shows that the terminal starts using over 10,000MB memory sometimes at over 1000mb/second on the disk, is it possible that this number reaches 10,000MB while only having 4GB of  RAM? I also tried the optimized anaconda to the same result. Its suggesting 

 If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I think somehow its trying to do everything at once or something.

**Comment by tildebyte** [comment]
@ArtificialHuman007;

>  task manager shows that the terminal starts using over 10,000MB memory

If you're looking at the "Memory" column of the "Processes" tab in Task Manager - that's main RAM, not VRAM. Check the "Performance" tab, whichever "GPU" entry on the left corresponds to your NVIDIA device - **that's** where you can see VRAM usage (bottom of the big pane). As mentioned, the *only* number that matters is "Dedicated GPU memory"; "Shared GPU memory" is *not* used by CUDA.

![Task_Manager_GPU](https://user-images.githubusercontent.com/337875/188506087-3ab80617-89dc-4f54-a98b-4813f4a70dad.png)

> If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Definitely don't do anything based on this. This is something which has to be integrated into the code; it won't solve a local problem.

**Comment by ArtificialHuman007** [comment]
You are right, only 4gb, this makes me sad.

**Comment by lstein** [comment]
> Hi, I know I may sound stupid, but I really do think I have more than 4GB, I made sure to specify that I would have 16 before purchase. When I run & "C:\Program Files\Git\usr\bin\winpty.exe" python scripts\dream.py task manager shows that the terminal starts using over 10,000MB memory sometimes at over 1000mb/second on the disk, is it possible that this number reaches 10,000MB while only having 4GB of RAM? I also tried the optimized anaconda to the same result. Its suggesting
> 
> If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> I think somehow its trying to do everything at once or something.

The process manager is showing you main memory (RAM), not video ram (VRAM). Looks like whoever sold you the video card didn't honor your request.

**Comment by MahouShoujoMivutilde** [comment]
@ArtificialHuman007 Don't be sad, I have a gtx 970 (4gb) and e.g. [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui) fork works beautifully (2s/it) with `--lowvram` flag for me.

**Comment by tildebyte** [comment]
IIUC https://github.com/basujindal/stable-diffusion is also optimized for 4G VRAM

**Comment by yudhanjaya** [comment]
Oddly, I just got the same error.
@lstein I'm using a GTX 1080 Ti. 11 gigs of VRAM, should technically be no issue at all.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:09:00.0  On |                  N/A |
|  0%   44C    P8    17W / 250W |   1004MiB / 11264MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by ArtificialHuman007** [comment]
Wow thanks for the info. Could you tell me how to enable full_precision for dummies?

**Comment by yudhanjaya** [comment]
> Wow thanks for the info. Could you tell me how to enable full_precision for dummies?

@ArtificialHuman007 sure! python /scripts/dream.py --full_precision

**Comment by ArtificialHuman007** [comment]
> > Wow thanks for the info. Could you tell me how to enable full_precision for dummies?
> 
> @ArtificialHuman007 sure! python /scripts/dream.py --full_precision

Hi, when I say for dummies, I really mean I don't know what I'm doing. Where am I meant to write that? When I put that line in it just says no such file or directory. Thanks for trying to help.

**Comment by yudhanjaya** [comment]
Essentially: follow the steps for installation on the main Readme.

Once installation is complete, open up an anaconda prompt (assuming you’re
on windows).  In the prompt, type in:

cd stable-diffusion
conda activate env ldm

This gets you into you folder and activates the environment.

Then type in:

python /scripts/dream.py --full_precision

Dream.py is a script that runs SD and extends its capacity. You’re
essentially telling it how to start the model up.
