### ISSUE TITLE
Real-esrgan taking more time than usual

### ISSUE THREAD

**Issue by gvijqb** [lstein/stable-diffusion#389]
**Describe your environment**
- GPU: RTX 3090
- VRAM: 24GB
- CPU arch: [x86/arm]
- OS: Linux
- Python: Anaconda

**Describe the bug**
I have tried Real-esrgan on local system and on Replicate demo as well. Usually it is able to upscale 2x in 5-7 seconds. But when I am adding upscaling option in dream API, it is taking 13-15 seconds on average. This becomes a problem when the iteration count is above 3 as it takes a long while to give outputs.

Any idea what I am doing wrong?

My configuration for upscaling is:
gfpgan_strength = 0
upscale_factor = 2
upscale_strength = 0.75

**Comment by lstein** [comment]
@blessedcoolant, do you have any insights into why this is occurring?

**Comment by blessedcoolant** [comment]
Let me do some testing to see if I can repro this.

**Comment by gvijqb** [comment]
> Is it tiling when the inference for real esrgan happens?

I don't see any tiling as such. It's just that the real esrgan is taking more time than stable diffusion for upscaling. Almost 13 seconds per image.. That too on a 3090 GPU. Which GPU did you use for the testing?
