### ISSUE TITLE
KDPM_2A and KEULER_A are not reproducible

### ISSUE THREAD

**Issue by netsvetaev** [lstein/stable-diffusion#397]
- GPU: MPS
- VRAM: ~12gb (MBP M1 Pro 16gb)
- CPU arch: ARM
- OS: MacOs 13
- Python: miniconda, 3.10.6
- Branch: On branch main

**Describe the bug**
I run different samplers with the same seed. KDPM_2A and KEULER_A always have different results. KDPM_2A outputs is somewhat similar to each other (great stylization btw), EULER_A's is not. Is that ok? The rest are reproducible 1:1.

Examples:

KDPM_2A

![000044 3343280900](https://user-images.githubusercontent.com/83028930/188546508-818ba35f-ed75-45a5-a2ae-6b87b51ab1c5.png)
![000049 3343280900](https://user-images.githubusercontent.com/83028930/188546520-7c0d6f05-de16-4e0c-879f-4e7c0599fa0e.png)

KEULER_A

![000046 3343280900](https://user-images.githubusercontent.com/83028930/188546588-9bb95585-db01-499b-982b-952c15b8cea0.png)
![000048 3343280900](https://user-images.githubusercontent.com/83028930/188546590-efdafa63-7320-422b-9986-8a7269095a94.png)

Others (klms, plms, etc)

![000043 3343280900](https://user-images.githubusercontent.com/83028930/188546687-48b09062-9adc-48b2-9a72-3a73d3a4fbb1.png)
![000050 3343280900](https://user-images.githubusercontent.com/83028930/188546693-560be403-498e-4c22-b53e-9b6843c79688.png)

**Comment by lstein** [comment]
@tildebyte, is this expected behavior?

**Comment by n00mkrad** [comment]
This is expected, not every sampler looks the same

**Comment by tildebyte** [comment]
> using the same seed will result in the same image

Yes, exactly. There are subtle differences between all of the samplers; the differences with the "ancestral" samplers are not-as-subtle (note that the last two rows are the "_a" samplers); indeed, one can see that the "_a" samplers are **closer to each other** than to all of the others:

*Note that this was taken from somewhere on reddit - not my work
 
![SD Sampler comparison](https://user-images.githubusercontent.com/337875/188684487-934dfe3b-6861-47d9-9f7a-0e71ead61a93.png)

**Comment by wbowling** [comment]
> And the results are reproducible. Using the same seed will result in the same image.

This is the issue as it's not the case when on a M1 Mac. When using `KEULER_A` or `KDPM_2A` there is no way to reproduce an image even when using the same configuration.

For example running `dream> landscape --seed 1234 --sampler k_euler_a --steps 20 --cfg_scale 8 --iterations 1 --width 512 --height 512` three times in a row produces three different images:

<img src="https://user-images.githubusercontent.com/1418260/188754380-a91423cb-98e8-469e-bf67-e716022d1781.png" alt="000002 1234" width="256"><img src="https://user-images.githubusercontent.com/1418260/188754396-5b542c66-74f0-4496-bb02-ce98a93daff3.png" alt="000003 1234" width="256"><img src="https://user-images.githubusercontent.com/1418260/188754401-fe3bdd85-10ad-49d2-8f9f-d1c93725cdc8.png" alt="000004 1234" width="256">


Where as the other samplers reproduce the same image as expected, `dream> landscape --seed 1234 --sampler k_lms --steps 20 --cfg_scale 8 --iterations 1 --width 512 --height 512`:

<img src="https://user-images.githubusercontent.com/1418260/188754391-533aca48-38b3-48a1-beea-d07289eaa1fc.png" alt="000005 1234" width="256"><img src="https://user-images.githubusercontent.com/1418260/188754406-c74dd054-0061-4bb6-a26e-9c04f4379bf3.png" alt="000006 1234" width="256"><img src="https://user-images.githubusercontent.com/1418260/188754415-b6e210c2-5900-49d7-9232-a4a755d8aa4d.png" alt="000007 1234" width="256">

**Comment by wbowling** [comment]
I think this is the underlying issue - https://github.com/pytorch/pytorch/issues/84288

**Comment by Any-Winter-4079** [comment]
This is not fixed yet in Release candidate 1.14.3. Maybe we should create a pull request.

**Comment by tildebyte** [comment]
Recommended. **If** it's high enough priority, and isolated enough to not break anything else, you might be able to convince @lstein to make a hotfix release on top of 1.14.x

**Comment by Any-Winter-4079** [comment]
I think it's not high priority (the sampler still works) but if something to remember, as this it needs a fix to reproduce images.
Maybe after things settle down with the release we can do a PR.

**Comment by Any-Winter-4079** [comment]
Now that the release is out, it might be a good time to pick thing up from here.
There is also this https://github.com/lstein/stable-diffusion/discussions/507 for which a good starting point may be adding k_euler to img2img.
