### ISSUE TITLE
Why using RealESRGAN_x4plus in v0.1.0 instead of v0.2.5

### ISSUE THREAD

**Issue by glonlas** [lstein/stable-diffusion#399]
**Is your feature request related to a problem? Please describe.**
The [gfpgan_tools.py file ](https://github.com/lstein/stable-diffusion/blob/main/ldm/gfpgan/gfpgan_tools.py#L87) and [`preload_models.py` scripts ](https://github.com/lstein/stable-diffusion/blob/main/scripts/preload_models.py#L69) are loading the RealESRGAN x4 v0.1.0 model, while a more recent model is available: [x4v3 v0.2.5 model](https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0). 

Is there a rationale to keep using the v0.1.0?

**Describe the solution you'd like**
1. Updating the line [in preload_models.py](https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0) with `model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth',`
2. Updating the line in [gfpgan_tools.py](https://github.com/lstein/stable-diffusion/blob/main/ldm/gfpgan/gfpgan_tools.py#L87) with `4: 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth',`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by glonlas** [comment]
Update. Changing the link to the model file will not work. It will also require reworking the RRDBNet model.
But still I am interested to know the benefits of the x4 v0.1.0 version.

**Comment by blessedcoolant** [comment]
At the time of implementation, that was the best model available. So I added that. He released a new model but I cannot find the model architecture code for it. So I cannot implement that just yet.
