### ISSUE TITLE
Windows probably doesn't need standalone Python

### ISSUE THREAD

**Issue by tildebyte** [lstein/stable-diffusion#40]
I don't think that 

> Install Python version 3.8.5 from here: https://www.python.org/downloads/windows/

is necessary. I simply installed (SPECIFICALLY, and man was that hard to figure out) Miniconda3-py38_4.9.2-Windows-x86_64 to get Python 3.8.5, and then followed the rest of the instructions. I *do* have Py 3.10 installed (from python.org), but after launching "Anaconda Prompt (miniconda3)", I can do

```
(ldm) C:\Users\xxxxxxxxxx\Source\stable-diffusion>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```

so Miniconda alone is providing 1) *a* version of Python and 2) the *correct* version.

The warning from Miniconda about there being an existing "default" Python 3.8 could be quite confusing for users not experienced with Python (particularly on Windows).

**Comment by lstein** [comment]
Good to know! I will fix the instructions accordingly.
