### ISSUE TITLE
CTRL+C does not work when running prompts from file

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#401]
Inside my file 50 prompts. I am forced to press CTRL+C 50 times to cancel this batch command.
`(ldm) ~/stable-diffusion$ python3 scripts/dream.py --from_file "path/to/prompts.txt"`

It would be nice if I could click CTRL+C just once instead.

**Comment by lstein** [comment]
Thanks for pointing this out. It should be an easy fix.
