### ISSUE TITLE
 No module named 'pytorch_lightning' 

### ISSUE THREAD

**Issue by loboere** [lstein/stable-diffusion#403]
![image](https://user-images.githubusercontent.com/15265895/188683483-60d437b1-8641-41e7-a2c8-c060e53d305d.png)

**Comment by tildebyte** [comment]
Click the green button up there ↗️

![image](https://user-images.githubusercontent.com/337875/188746197-7a35b086-2bc4-444d-80a6-3260b637e4fc.png)

Note the text at the left: "Bug Report". Click the green button.
![image](https://user-images.githubusercontent.com/337875/188746238-0003a557-bc31-4e16-8820-258c76ea5bb9.png)

Fill out as much of this information as you can

![image](https://user-images.githubusercontent.com/337875/188746439-d78ded7c-bfa5-4b22-922e-55f0e443c942.png)

**Comment by jameslh** [comment]
I had this problem also in the Colab notebook. 

Within xterm, run the following commands:
```pipenv install pytorch_lightning
pipenv install omegaconf
pipenv install transformers
pipenv run scripts/preload_models.py
```

Then you should be able to run `pipenv run scripts/dream.py`

**Comment by artmen1516** [comment]
My PR with colab improvements and fixes https://github.com/lstein/stable-diffusion/pull/422 was just merged to development branch,
until development is merged to main, colab shortcut will redirect to previous version, please use this link in the meantime.

https://colab.research.google.com/github/lstein/stable-diffusion/blob/development/Stable_Diffusion_AI_Notebook.ipynb
