### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by mhafiz17** [lstein/stable-diffusion#404]
Hello, every time I run the script on the Powershell 7, it throws me this error:

> Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "c:\users\mirza\stable-diffusion\ldm\simplet2i.py", line 382, in prompt2image
>     image = make_image(x_T)
>   File "c:\users\mirza\stable-diffusion\ldm\simplet2i.py", line 478, in make_image
>     samples, _ = sampler.sample(
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
>     K.sampling.__dict__[f'sample_{self.schedule}'](
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\k_diffusion\sampling.py", line 186, in sample_lms
>     denoised = model(x, sigmas[i] * s_in, **extra_args)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
>     uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\k_diffusion\external.py", line 100, in forward
>     eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\k_diffusion\external.py", line 126, in get_eps
>     return self.inner_model.apply_model(*args, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
>     x_recon = self.model(x_noisy, t, **cond)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
>     out = self.diffusion_model(x, t, context=cc)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 806, in forward
>     h = module(h, emb, context)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 88, in forward
>     x = layer(x, context)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\attention.py", line 298, in forward
>     x = block(x, context=context)
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\attention.py", line 232, in forward
>     return checkpoint(
>   File "c:\users\mirza\stable-diffusion\ldm\modules\diffusionmodules\util.py", line 155, in checkpoint
>     return func(*inputs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\attention.py", line 238, in _forward
>     x = self.attn1(self.norm1(x)) + x
>   File "C:\Users\mirza\.virtualenvs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "c:\users\mirza\stable-diffusion\ldm\modules\attention.py", line 196, in forward
>     attn = sim.softmax(dim=-1)
> RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 6.00 GiB total capacity; 2.61 GiB already alloca
> ted; 303.44 MiB free; 3.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_s
> plit_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> >> Are you sure your system has an adequate NVIDIA GPU?
> >> Usage stats:
> >>   0 image(s) generated in 0.35s
> >>   Max VRAM used for this generation: 3.34G
> Outputs:

I installed the script using [this](https://github.com/lstein/stable-diffusion/wiki/Easy-peasy-Windows-install). I use a laptop with RTX 3060. It tries to run but fails after a few seconds, and the task manager shows no GPU being used.

**Comment by tildebyte** [comment]
Please use and fill out the Bug Template (the text which was in the text box when you opened this issue).

If you opened a "blank issue", please open a Bug, using the Bug template.

**Comment by mhafiz17** [comment]
> Please use and fill out the Bug Template (the text which was in the text box when you opened this issue).
> 
> If you opened a "blank issue", please open a Bug, using the Bug template.

Alright thanks!
