### ISSUE TITLE
Write more metadata to output files

### ISSUE THREAD

**Issue by sowbug** [lstein/stable-diffusion#406]
Hi there, over on https://github.com/basujindal/stable-diffusion I've submitted a [PR](https://github.com/basujindal/stable-diffusion/pull/123) to write most of the command-line parameters to the generated picture files. This is similar in spirit to your function `save_image_and_prompt_to_png`, but it goes farther:

![Screenshot from 2022-09-06 13-25-51](https://user-images.githubusercontent.com/30292/188731531-832cb843-125c-44bc-95db-5c3027689612.png)

Since the @basujindal fork also optionally outputs JPEGs, the PR handles both file types. Anyway, if you're interested in this functionality, you're welcome to adapt the PR, or else ask me to do it.

**Comment by tildebyte** [comment]
We have ongoing work to improve metadata writing - I don't have the exact link handy. It's either in Issues, a PR, or Discussions.

**Comment by bakkot** [comment]
I have a proposal for exactly what metadata to include at https://github.com/lstein/stable-diffusion/issues/266.

@sowbug do you want to take a look at that? If there's other information which you think ought to be included, please leave a comment there.
