### ISSUE TITLE
NOTE: Images generated here do not match beta.dreamstudio.ai

### ISSUE THREAD

**Issue by tildebyte** [lstein/stable-diffusion#411]
I don't know if this is expected behavior or not (obviously we can't have any idea as to what kind of prompt massaging dreamstudio might be doing behind the scenes).

I got curious about the 1.5 model, so I went to check it out. That's not what this is about :D

My test prompt generation was so different from what I get with this repo with 1.5, that I decided to test with 1.4, and indeed it's quite different.

Prompt/parameters (lines split for readability)

```
a black and white medium format 85mm portrait photograph of a kitten wearing a tuxedo
on his way to a funeral, The photo is high quality and highly detailed with the kitten's
features clearly visible, photographer Edward Weston used Agfa Isopan ISO 25 film to
create this image, this image resembles Edward Weston's photograph Pepper No. 35
 -s75 -W512 -H704 -C7.0 -Ak_euler_a -S3185101922
```

This repo:
![000151 3185101922](https://user-images.githubusercontent.com/337875/188747026-6f7c2c37-00e3-4891-924a-05916a66562d.png)

dreamstudio beta 1.4 model:
![3185101922_a_black_and_white_medium_format_85mm_portrait_photograph_of_a_kitten_wearing_a_tuxedo_on_his_way_to_a_funeral__The_photo_is_high_quality_and_highly_detailed_with_the_kitten_s_features_clearly_visible__p](https://user-images.githubusercontent.com/337875/188747080-9676d0d2-3ad5-44fc-8af7-25eae5f50d1c.png)

**Comment by lkewis** [comment]
I think dream studio has messed up, I tried one of my prompts that previously matched this repo and dream studio and it's now different with v1.4. I also ran your prompt through the Deforum notebook and it gets the same result as this repo.

**Comment by tildebyte** [comment]
@lkewis; Nice, thanks for the investigation. 

I’ll leave this one open for a while for visibility.

**Comment by blessedcoolant** [comment]
Is the 1.5 model even publicly available anywhere?

**Comment by csabal** [comment]
That would be so cool, yeah!

**Comment by tildebyte** [comment]
> Is the 1.5 model even publicly available anywhere?

Still cooking, according to S-D Discord #announcements

**Comment by blessedcoolant** [comment]
> Still cooking, according to S-D Discord #announcements

Is there an ETA or any other info?

**Comment by GifCo** [comment]
1.5 went live on dreamstudio yesterday and is available through their API but the model is not available for download yet. Timeline was a week or two for that.

**Comment by n00mkrad** [comment]
> > Still cooking, according to S-D Discord #announcements
> 
> Is there an ETA or any other info?

2-3 weeks.
