### ISSUE TITLE
can you run GFPGan and upscaler on an image without regenerating the image

### ISSUE THREAD

**Issue by halpz** [lstein/stable-diffusion#423]
**Is your feature request related to a problem? Please describe.**
It seems a waste of time to regenerate an image that has already been generated

**Describe the solution you'd like**
I would like to select an image in the web ui and apply GFPGAN / upscaling to it without re-invoking stable-diffusion

**Describe alternatives you've considered**
I have tried running GFPGAN in a separate terminal window, but having the web server and another GFPGAN instance running at the same time causes memory problems, and it's a lot of work to close the web server and run GFPGAN for each image

**Comment by blessedcoolant** [comment]
Hmm... I guess one way to handle this would is to add a switch called 'upscale_only' and let the enable an entire pipeline just for enlarging the image so we can avoid loading anything else.

There's a code refactor that was done recently by @lstein that I have not fully accustomed myself with. I'll have a look and see what would be the best way to implement this.

**Comment by hipsterusername** [comment]
Thoughts:
- Use a switch for --gfpgan_only, which takes a filepath and allows for -G.
- Use a switch for --upscale_only, which takes a filepath and allows for upscale settings.
- --gfpgan_only and --upscale_only error out if passed in with normal SD prompt/settings.
- Build into new WebUI as well (likely as a completely different pane/screen, so as not to confuse the fact it is exclusive from SD/image generation)

**Comment by n00mkrad** [comment]
This is an image generation script, not an upscaling script. 
Personally I think this is out of scope.

**Comment by hipsterusername** [comment]
> This is an image generation script, not an upscaling script. Personally I think this is out of scope.

I think it's a fair point to raise, but one which requires a question about the intended usecases & workflows the project aims to support. 

Given that this fork integrates a number of high-value solutions into a single repo (including capabilities for supporting GFPGAN and RealESRGAN), I don't think it's unthinkable that these are seen as core to common end-to-end workflows the tool intends to serve.  

Upscaling after generation is a common UX feature of "competitive" solutions (e.g., Midjourney.) I admit the GFPGAN post-generation is less useful, although not completely irrelevant if one were to want to apply a different G strength on an existing image.

**Comment by Any-Winter-4079** [comment]
> This is an image generation script, not an upscaling script.
> Personally I think this is out of scope.

While you may be right, to me inpainting and img2img are more image modification than image generation. With that I mean that the images often need to go through a series of changes (several steps of img2img to iron out details, face restoration, upscaling, etc) before the final result.

Some images may even need more complex pipelines.

Now, since we're already loading GFPGAN and Real-ESRGAN, I think it's far to ask for the feature, and not have it set it up outside of this repo.

Something like this may be useful: https://github.com/lstein/stable-diffusion/issues/390

**Comment by magnusviri** [comment]
We may want to upscale an image we already generated but didn't upscale.

**Comment by psychedelicious** [comment]
This is planned for the new web UI.

**Comment by lstein** [comment]
> This is planned for the new web UI.

Perfect. I was about to suggest this.

For the CLI, I will add a command to invoke GFPGAN and/or ESRGAN on a previously generated image.
