### ISSUE TITLE
Stuck following the install guide for Linux

### ISSUE THREAD

**Issue by pepa65** [lstein/stable-diffusion#426]
**Linux Mint 20.3 (Ubuntu 20.04, Debian bullseye/sid)**
- GPU: GeForce GTX 960M
- VRAM: ?
- CPU arch: x86_64
- OS: Linux
- Python: Python 3.8.10, Anaconda 4.12.0
- Branch: main
- Commit: dbc8fc79008795875eb22ebf0c57927061af86bc

**Describe the bug**
During `conda env create -f environment.yaml` after Downloading and Extracting Packages, I get:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/data/anaconda3/envs/ldm/bin/python', '-m', 'pip', 'install', '-U', '-r', '/data/git/stable-diffusion/condaenv.s733ep1k.requirements.txt']
Pip subprocess output:

Pip subprocess error:
Traceback (most recent call last):
  File "/data/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 19, in <module>
    from pip._internal.utils import appdirs
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/appdirs.py", line 13, in <module>
    from pip._vendor import appdirs as _appdirs
ImportError: cannot import name 'appdirs' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)

failed

CondaEnvException: Pip failed
```

**To Reproduce**
Follow the Install guide for Linux

**Expected behavior**
No error, able to proceed to `conda activate ldm`

**Comment by GifCo** [comment]
A GTX 960M isnt going to work for this. You need at least 8GB VRAM(maybe get by with 6) You are better of sticking with Colab.

**Comment by artmen1516** [comment]
@pepa65 
I agree with @GifCo, Give it a try in colab!

My PR with colab improvements and fixes https://github.com/lstein/stable-diffusion/pull/422 was just merged to development branch,
until development is merged to main, colab shortcut will redirect to previous version, please use this link in the meantime.

https://colab.research.google.com/github/lstein/stable-diffusion/blob/development/Stable_Diffusion_AI_Notebook.ipynb

**Comment by pepa65** [comment]
Thanks for pointing me towards colab. I did `nvidia-smi -L` and found that my card wasn't actually running, so that is probably the first step to fix..! (Maybe an idea to include this step in this readme as well.)
