### ISSUE TITLE
Support huggingface Textual Inversion embeddings (.bin)

### ISSUE THREAD

**Issue by n00mkrad** [lstein/stable-diffusion#427]
**Is your feature request related to a problem? Please describe.**
[HuggingFace concepts](https://huggingface.co/sd-concepts-library) trained using textual inversion are not compatible with the current code unlike .pt files created with the existing textual inversion repos

**Describe the solution you'd like**
Add support for huggingface .bin embeddings

**Describe alternatives you've considered**
Possibly a converter?

**Comment by lstein** [comment]
Perhaps @Oceanswave can help. He wrote the textual inversion implementation.

**Comment by hipsterusername** [comment]
Are there any libraries (similar to HuggingFace) for .pt files trained? Biggest value add to me is having a library of concepts to draw from

**Comment by lstein** [comment]
Bringing in @Oceanswave and @nicolai256 into this conversation, as they both worked on the textual inversion implementation. Do either of you know how to load/generate the hugging face .pt files?

**Comment by thealanle** [comment]
It seems like the sd-concepts-library ".bin" embeddings are now usable on AUTOMATIC1111's repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/151

Could that solution be implemented here as well?

**Comment by lstein** [comment]
Support for .bin files is now merged in the development branch.
