### ISSUE TITLE
User accessibility: Adding a script to install Stable-diffusion?

### ISSUE THREAD

**Issue by glonlas** [lstein/stable-diffusion#443]
**Is your feature request related to a problem? Please describe.**
Installing Stable Diffusion on Mac (but also other platforms) is not accessible to everyone. This can block users from achieving the goal of installing and using it. **Should we provide scripts to do the installation on their behalf?** 

**Describe the solution you'd like**
I wrote a script to help myself install Stable-Diffusion on my Apple Silicon M1. This script performs the install if it is not already present on the system, then provides shortcuts to either the Web UI or Dream terminal. 

For transparency and audit, you can [find the script here](https://github.com/glonlas/Stable-Diffusion-Apple-Silicon-M1-Install). 

Of course the final script of this project will be different, but the idea is one command to install, keep up-to-date, and provide access to the best feature of Stable-diffusion.

**Describe alternatives you've considered**
Updating the README with lesser commands step to reduce the complexity. 

IMHO the best option is how Brew simplified the entire installation of their software in one single command. 
It can be seen on [their homepage](https://brew.sh/).

**Comment by daviddrummond95** [comment]
@glonlas I used your script this week for my first time installation and it was incredibly helpful. I thought your approach was wonderfully elegant!

**Comment by glonlas** [comment]
Thank you for the feedback. The script is long, but the idea is that each function can be tested individually. 
When I see the volume of messages, and tickets on people unable to have a working env, I feel it will be beneficial to have a script to install it.
