### ISSUE TITLE
Outpainting Implementation Considerations 

### ISSUE THREAD

**Issue by hipsterusername** [lstein/stable-diffusion#445]
Given the comments (and renaming of the existing Inpainting issue to remove references to Outpainting), opening another to discuss outpainting on its own. To frame the common use-case/workflow for outpainting:

> "I would like to pass in [all/some] of an existing image, along with a prompt, to generate _**and extend the image dimensions**_ of the original image"

Workarounds today, once inpainting is supported, would be to pass in ~half of a generated image, along with a mask on one half, generate, and compile in an external photo-editing program. 

Would like to pose the question to the group to kick off discussion of how "outpainting" might be supported here, and where different implementation paths might face complexity. Seemingly (and this is an ignorant/uninformed perspective), outpainting _may_ just be automating this process to some extent, by transforming an image to a larger canvas size, along with transparency, and passing it into the same process that inpainting is using?

**Comment by pbaylies** [comment]
As far as outpainting implementations, just saw this, looks really interesting: https://github.com/parlance-zz/g-diffuser-bot/tree/g-diffuser-bot-diffuserslib-beta

**Comment by XodrocSO** [comment]
I was about to bring up that reddit thread as well, looks very promising, although it doesn't look like it perfectly preserves the image it's extending, at least not the examples.

**Comment by Dschogo** [comment]
This approach looks very user friendly: [https://github.com/lkwq007/stablediffusion-infinity](https://github.com/lkwq007/stablediffusion-infinity)
