### ISSUE TITLE
LICENSE change?

### ISSUE THREAD

**Issue by tildebyte** [lstein/stable-diffusion#45]
IANAL, so don't take my advice 😁, but LICENSE changed completely in upstream's 69ae4b3

**Comment by lstein** [comment]
Ok, doke. Thanks for the heads-up. I'll review. Neither the LICENSE in force at the time I forked nor the current one actually addresses the legal status of the source code itself, which was derived from the latent-diffusion project and has a standard MIT open source license. I think the LICENSE has to do with the model weights, which isn't even being distributed from GitHub.

I think I'll replace the current license with the MIT one, which has the benefit of being understood by the community.

**Comment by tildebyte** [comment]
> I think the LICENSE has to do with the model weights, which isn't even being distributed from GitHub

Yeah, this was my impulse as well, but then... why just drop it in there as 'LICENSE', and not, say, 'MODEL LICENSE'?
Confusing, at best.

**Comment by lstein** [comment]
Much as I appreciate what they've done, I've never seen an open source product rollout quite so chaotic as this one.

**Comment by lstein** [comment]
I've added two licenses. One for the software and the other for the model. Also added copyright statements.
