### ISSUE TITLE
Max Steps Error on Textual Inversion Training

### ISSUE THREAD

**Issue by scrambled2** [lstein/stable-diffusion#455]
**Anaconda Windows 10**
- GPU: [2x3090]
- VRAM: [2x24GB]
- CPU arch: [AMD]
- OS: Windows/]
- Python: [Python 3.8.5]
- Branch: MAIN

**Describe the bug**
When I go to perform the textual inversion training I get the following error: 

Traceback (most recent call last):
  File "./main.py", line 863, in <module>
    trainer_kwargs['max_steps'] = trainer_opt.max_steps
AttributeError: 'Namespace' object has no attribute 'max_steps'

I cannot for the life of me figure out where to go from here. I greatly appreciate any help.

**Comment by lstein** [comment]
@oceanswave. could you look into this?

**Comment by lstein** [comment]
I'm not very familiar with this part of the code, but the option "max_steps" is supposed to come from the configuration file `configs\stable-diffusion\v1-finetune.yaml`. Could you confirm that the file is present and that the very last line reads "max_steps: 4000"?

**Comment by lstein** [comment]
@Oceanswave, pinging you again on this bug report?
