### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'models/ldm/stable-diffusion-v1/model.ckpt'

### ISSUE THREAD

**Issue by Conor125** [lstein/stable-diffusion#456]
I followed the 'Easy-Peasy Windows Install' guide and when I get to the point where I enter the "python scripts\dream.py" command it fails with the following error:

PS E:\stable-diffusion> python scripts\dream.py
* Initializing, be patient...
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "E:\stable-diffusion\scripts\dream.py", line 633, in <module>
    main()
  File "E:\stable-diffusion\scripts\dream.py", line 92, in main
    t2i.load_model()
  File "e:\stable-diffusion\ldm\simplet2i.py", line 592, in load_model
    model = self._load_model_from_config(config, self.weights)
  File "e:\stable-diffusion\ldm\simplet2i.py", line 660, in _load_model_from_config
    pl_sd = torch.load(ckpt, map_location='cpu')
  File "C:\Users\conor\.virtualenvs\ldm\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\conor\.virtualenvs\ldm\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\conor\.virtualenvs\ldm\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'models/ldm/stable-diffusion-v1/model.ckpt'

Things that I have tried so far:
-Run the Terminal/Powershell in Administrative mode.
-Force Python to run in Administrative mode. 
-Gave the folders read/write permissions to all users. 
-Repeated the installation process on a different drive.

I cannot figure out why it appears not to have permissions to the 'models/ldm/stable-diffusion-v1/model.ckpt'  directory.

Thanks in advance.

**Comment by lstein** [comment]
Can you open the file independently of the dream script? From the command line, try `certutil -hashfile models\ldm\stable-diffusion-v1\model.ckpt MD5`

**Comment by Conor125** [comment]
I ran `certutil -hashfile models\ldm\stable-diffusion-v1\model.ckpt MD5` and it failed, but then realised that it is trying to open "model.ckpt" as a file, but in my folder structure it is a folder that contains the model "sd-v1-4.ckpt". 
![image](https://user-images.githubusercontent.com/104375189/189302553-d4624d8b-ca6d-4d9d-81a5-2b7470938a1c.png)

I then ran `certutil -hashfile models\ldm\stable-diffusion-v1\model.ckpt\sd-v1-4.ckpt MD5` and it could access the file fine. 
This gave me the idea to just replace the folder "model.ckpt" with the model file "sd-v1-4.ckpt" and rename it to "model.ckpt"
![image](https://user-images.githubusercontent.com/104375189/189303191-360012d1-d9c1-451e-9080-638c8d213aef.png)

This worked! The `python scripts\dream.py` command now runs perfectly. I am assuming I must have not followed the guide correctly but also not sure where I went wrong. I think it could be step 8 that was creating the "model.ckpt" folder
`mkdir -p models\ldm\stable-diffusion-v1`
`copy C:\path\to\sd-v1-4.ckpt models\ldm\stable-diffusion-v1\model.ckpt`

**Comment by Lrnvrybthksa** [comment]
This worked for me! I had two files, a model.ckpt link file and the other file of sd-v1-4.ckpt, i changed this one's name to just model.ckpt and it worked! 

the readme directions are in linux for linking the weights 

```
mkdir -p models/ldm/stable-diffusion-v1/
ln -s <path/to/model.ckpt> models/ldm/stable-diffusion-v1/model.ckpt 

```
and i'm on windows and i used a different command 

and these directions want a soft link i think? (i forgot exactly the type of linking it wanted) 

i didn't check the file folder directly until i saw this post and i noticed the two different files and their names
