### ISSUE TITLE
Pip failed Using miniconda3 on Windows 10

### ISSUE THREAD

**Issue by Neosettler** [lstein/stable-diffusion#459]
Using:
conda env create -f environment.yaml

return:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['python.exe', '-m', 'pip', 'install', '-U', '-r', '\\condaenv.v4isk7im.requirements.txt']
Pip subprocess output:
Requirement already satisfied: pillow==9.2.0 in c:\users\perro\miniconda3\envs\ldm\lib\site-packages (from -r \condaenv.v4isk7im.requirements.txt (line 10)) (9.2.0)
Obtaining clip from git+https://github.com/openai/CLIP.git@main#egg=clip (from -r \condaenv.v4isk7im.requirements.txt (line 16))
  Updating \clip clone (to revision main)

Pip subprocess error:
ERROR: Command errored out with exit status 1: git reset --hard -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 Check the logs for full command output.

failed

CondaEnvException: Pip failed

Any idea?

**Comment by Neosettler** [comment]
modified to this:

name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - taming-transformers
    - openai
    - -e .

launching dream.py returns:

import k_diffusion as K\r\nModuleNotFoundError: No module named 'k_diffusion'

Any idea?

**Comment by lstein** [comment]
The k_diffusion library is itself a git repository that is brought in by conda during the install process and saved under src. Sometimes an incomplete install results in a broken src directory. Try removing the **src** directory and all its contents. Then run `conda env update -f environmental.yaml'

@Neosettler , what changes did you need to make to environment.yaml?

**Comment by Neosettler** [comment]
started form scratch and it seems to work now. I'm guessing download and extract repo not the same as git clone repo.

**Comment by lstein** [comment]
Both methods should do exactly the same thing, but I haven't tested the download and extract method. Is this what you tried at first?
