### ISSUE TITLE
Crash when -C argument equals to 1

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#46]
dream> red elephant -C 1
Crash

**Comment by lstein** [comment]
Oooh. That's bad. Will fix.

Similar issue is that if --strength is 0.0 or 1.0, you also get a hard crash that freezes the GPU.

Not enough error checking in the underlying CompViz code....

**Comment by lstein** [comment]
Assertion checks now in place. Script will warn, but not crash.
