### ISSUE TITLE
Only DDIM sampler supported with init_img option

### ISSUE THREAD

**Issue by alexshultz** [lstein/stable-diffusion#465]
M1 MacBook Pro
M1 Pro chip
16GB
MacOS 12.5.1
Anaconda
Branch: main
Commit: can't find a line with "Merge"

In dream.py I'm trying to use an input image. Each time I get a message similar to "sampler 'k_dpm_2' is not yet supported. Using DDIM sampler" regardless of whether I use the default sampler or if I use the --sampler flag to choose a sampler. The process still produces an image each time.

I wondered if the message was in error and maybe the different samplers ARE being used. I used an input image with a seed and the default sampler. I also tried several more times with different samplers, keeping all the other options the same. Each output image appears to be identical. It seems like the sampler option is being ignored if an input image is used.

I have get no error messages about the sampler if I do NOT use an input image.

**To Reproduce**
in dream.py
a prompt with --init_img and an input image (and optionally) --sampler using one of the listed samplers, like one of these:
"green giant" --init_img ./sample-image.png
"green giant" --init_img ./sample-image.png --sampler "plms"

The error for the default sampler shows up as:
sampler 'k_dpm_2' is not yet supported. Using DDIM sampler

The error for the plms sampler shows up as:
sampler 'plms' is not yet supported. Using DDIM sampler

The system keeps on working and produces an image but presumably using the DDIM sampler instead of the desired one. The log file shows that the sampler flag is still used:

outputs/img-samples/000319.925524758.png: "green giant" -s50 -W512 -H512 -C7.5 -Ak_dpm_2 -I./sample.image.png -f0.75 -F -S925524758

**Expected behavior**
The system would not give an error about the sampler and would produce an image use the desired sampler, if one was chosen.

**Comment by lstein** [comment]
The message is correct. When an initialization image is added (or inpainting is requested), the DDIM sampler is used. Fortunately this sampler works quite well on initialization images, however it is on the big TODO list to provide support for the other samplers. To see the TODO list, go to Discussions and check out the big pinned banner at the top.
