### ISSUE TITLE
Templates in arguments

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#47]
Format of proposed template: 
{start_value, end_value, increment}

Usage example:
> "red elephant on a bike" -C{2,10,0.5} -f{0.5,1.0,0.02} -n 100 -S 2828484928

It will result in these 100 prompts:
> "red elephant on a bike" -C 2 -f 0.5 -n 1 -S 2828484928
> "red elephant on a bike" -C 2.5 -f 0.52 -n 1 -S 2828484928

and so on.

I noticed that when you change -C parameter newly generated image is a slight variation of original image so by automatically generating bunch of images with different -C value (for txt2img) or different -f value (for img2img) variations of the same Seed image can be generated.

**Comment by lstein** [comment]
I've been thinking of something along the same lines. There's another issue request that came in this morning from a person who has gotten nice img2img results by modifying the text of the prompt slightly by injecting a random number into it. I think the possibilities are endless.

However, I'm wondering whether it mightn't be better to write some examples of using the dream.py API to do it programmatically. Then you can simply modify the example scripts to suit your own needs and you'll have some practical programming experience to boot. You can literally generate an image using two lines of code.

That aside, I don't quite understand how your template example  works. The -C and -f parameters give you 3x3=9 combinations. And then you want to run each of the 9 combinations 10 times for 90 images? Don't you need to vary the seed?
Maybe you intend:
~~~~
"red elephant on a bike" -C 2 -f 0.5  -n10 -S 2828484928
"red elephant on a bike" -C 2 -f 1.0   -n10 -S 2828484928
"red elephant on a bike" -C 2 -f 0.02 -n10 -S 2828484928
"red elephant on a bike" -C 10 -f 0.5 -n10 -S 2828484928
...
~~~~

**Comment by morganavr** [comment]
> However, I'm wondering whether it mightn't be better to write some examples of using the dream.py API to do it programmatically
Yes, you are right. API is the way to go. 

> Don't you need to vary the seed?
Seed should be the same. Only with the same initial seed I can get variations of the same "master" image.


> That aside, I don't quite understand how your template example works
Sorry for not providing enough information about its intended behavior, at least how I see it.

Let's see at these 3 examples - they differ only in -f argument
```
"red elephant on a bike" -C 2 -f 0.25  -n 1 -S 2828484928
"red elephant on a bike" -C 2 -f 0.3   -n 1 -S 2828484928
"red elephant on a bike" -C 2 -f 0.35 -n 1 -S 2828484928
```

Here's a template:
"red elephant on a bike" -C 2 -f{0.25, 1, 0.05} -n 100 -S 2828484928

Even if we specified "-n 100" it does not mean that 100 images will be created because we can run out of values (for "-f" argument sooner - in around 15 iterations). Then it does not make any sense to continue computations because "-f" will equal to 1 and the same image will be generated over and over again.

If I wanted two arguments to be modified at the same time I would create another template:
"red elephant on a bike" -C{2, 20, 0.5} -f{0.25, 1, 0.05} -n 100 -S 2828484928

This template would stop running as soon as "-C" == 20 && "-f" == 1

**Comment by bakkot** [comment]
In terms of generating variations, I think it makes sense to allow the user to choose "keep", "tweak", or "anything" for each option, where "keep" uses the current value, "tweak" tweaks it a little bit (as in #81), and "anything" picks any reasonable value without regard to the original value. (Maybe this only makes sense for the web ui; that would be a complicated prompt from the REPL and it's easy enough to do programmatically, at least if we expose a "tweak seed" method as in #81.)

And then separately it would be cool to have the option to interpolate between two sets of options (though they'd have to have certain features the same, like the sampler and size and (in the case of img2img) the init_img).

**Comment by xraxra** [comment]
@bakkot I messed around with a possible solution for this, 

`"some amazing prompt" -s32 -C8:11 -S42 -n30`  

the `-C8:11` is saying use a starting value of 8 and and end value of 11 

if an end value is set on any parameter, the seed remains frozen when iterating (usually it calls `seed = self._new_seed()` )

so in the above example, you end up with 30 images w/ seed 42, starting at C8 and going up to C11 each image being a 0.1 change in C

would something like that be useful? 

To make it work I created a class which you initialize in prompt2image (like `Lerper(cfg_scale, iterations)`), places that originally expected a float or int use `cfg_scale.value`  

I was trying to figure out if it would work with __iter__ or __next__ but not sure... 

Will try to get it cleaned up + work for the other parameters and in a branch 

One issue is the png info written doesn't take into account the lerping value (it stores the original prompt), not sure how to resolve that
