### ISSUE TITLE
Announcement: Testers needed

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#470]
We are preparing a point release that includes VRAM optimizations (for generating larger images), enhancements to the simple web user interface, inpainting support, and more. 

You can help pitch in by testing the release candidate on your system to identify any bugs that may have slipped through. To participate, simply go to [Release candidate 1.14 ready for testing](https://github.com/lstein/stable-diffusion/discussions/461), and follow the instructions posted there.

Thanks in advance for your help,
@lstein

**Comment by smoke2007** [comment]
Everything seems to work fine for me , aside from the snake sushi ground being dirt instead of wood.

![000008 42](https://user-images.githubusercontent.com/17826183/189451321-6c7429ef-71c0-4ae4-89a3-37b80f44d322.png)
