### ISSUE TITLE
Seed shortcut not operating as expected

### ISSUE THREAD

**Issue by kmullinax** [lstein/stable-diffusion#476]
** First off, I want to THANK YOU for this amazing fork of SD.  It's absolutely awesome. **

- GPU: CUDA
- VRAM: 8GB
- CPU arch: x86
- OS: Windows 11
- Python: Miniconda3
- Branch: on branch
- Commit: 049ea02fc7e2e0e77908e08455e32f2028e232e9 (HEAD -> main, origin/main, origin/HEAD)

**Describe the bug**
When attempting to use the shortcut to rerun the last seed(s), the results are inconsistent and unknowable.
For instance, after running -n8, if I want to rerun the prompt with the 2nd image created, I should be able to enter -S-7 but the result is seemingly randomly any one of the 8 generated seeds.  
I've error-tested it in multiple ways, adjusting for -1 incase the -S-1 is actually the second to last generated - that didn't work.
I've assumed that perhaps the second image of 8 was actually -S-2 and not -S-7, but that still doesn't work.
I thought maybe the order of the 8 images mattered, so I've tried it sorted on creation time and sorted on filename.  Same results.

**To Reproduce**
1. create 8 images
2. attempt to reproduce the second image generated by rerunning the prompt with -S-7

**Expected behavior**
I expect that image2 will be recreated, but it's randomly any of the 8 originally images instead

**Comment by lstein** [comment]
Thank you for the report. I will fix this problem now, but in the next release I'm going to refactor how the whole thing works so that you can refer much more conveniently to previous outputs.

**Comment by kmullinax** [comment]
Great!  Thanks for your response!
