### ISSUE TITLE
img2img: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'

### ISSUE THREAD

**Issue by Macmee** [lstein/stable-diffusion#478]
**Describe your environment**
- GPU: m1 ultra gpu
- VRAM: 128gb unified memory
- CPU arch: aarch64
- OS: Mac OS 12.4
- Python: miniforge3
- Branch: main
- Commit: 79ac0f34201b69c4e8d44ef476a6d96a7844c900

**Describe the bug**
When I run img2img I get the error:

img2img: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'

**To Reproduce**
 inside of dream ran: "eating a pizza" --init_img=/Users/me/downloads/test-image.png --strength=0.5 -s100 -n4

**Comment by ryudrigo** [comment]
Hello! I'm not a mantainer, but I'm trying to solve this bug. Can you try replacing your file ldm/modules/attention.py with the one from PR #432?  (I attached it as a zip if you want faster access)

It would also be great to know how much time it took and your image size, if it does work. Thank you!

[attention.zip](https://github.com/lstein/stable-diffusion/files/9539354/attention.zip)

**Comment by Macmee** [comment]
> Hello! I'm not a mantainer, but I'm trying to solve this bug. Can you try replacing your file ldm/modules/attention.py with the one from PR #432? (I attached it as a zip if you want faster access)
> 
> It would also be great to know how much time it took and your image size, if it does work. Thank you!
> 
> [attention.zip](https://github.com/lstein/stable-diffusion/files/9539354/attention.zip)

hello friend, thanks for replying and trying to help! I replaced the file with the one you provided although unfortunately it did not fix the error

**Comment by ryudrigo** [comment]
Hmm do you get the same error with txt2img, or just img2img? What is the size of the initial image you're using?

**Comment by Macmee** [comment]
> Hmm do you get the same error with txt2img, or just img2img? What is the size of the initial image you're using?

txt2img works! My image is 209kb, 2063 × 3648

**Comment by ryudrigo** [comment]
Oh, so it's probably the size. Try reduzing the image beforehand, your computer won't be able to process this size anyway (2000x36000 is really huge for this kind of application)

**Comment by Macmee** [comment]
> Oh, so it's probably the size. Try reduzing the image beforehand, your computer won't be able to process this size anyway (2000x3600 is really huge for this kind of application)

Thanks, I just tried a smaller image and this time it completed but the output looks strange:

"with a dog running around" --init_img=/Users/me/downloads/xp.png --strength=0.75 -s100 -n4

the original image and outputs are attached

![xp](https://user-images.githubusercontent.com/1286638/189465499-c0994a21-6759-4a75-b6e5-59229a8c2370.png)

![000001 2102127704](https://user-images.githubusercontent.com/1286638/189465505-2bd4afec-9beb-4a35-99fa-52e7cc0bcc49.png)
![000001 3203166192](https://user-images.githubusercontent.com/1286638/189465508-cca997e3-900f-48d5-bb41-87fc37de3fa4.png)
![000001 3369980266](https://user-images.githubusercontent.com/1286638/189465511-0e783f1e-a3d3-494f-99d2-40156e44b5c1.png)
![000001 3987644261](https://user-images.githubusercontent.com/1286638/189465512-6b2fa5bc-79e2-48d8-a28e-2224198605c0.png)

but it's progress 😀
