### ISSUE TITLE
Running On Gradient Notebooks

### ISSUE THREAD

**Issue by DrMxrcy** [lstein/stable-diffusion#48]
Can this be ran on Gradient Notebooks? Want to us emy gpu power I have https://www.paperspace.com/gradient/notebooks

**Comment by lstein** [comment]
Yeah, I think you should be able to. These notebook apps can run arbitrary python packages, and I know that some have gotten this up and running on Google Colab. However, I'm not familiar with Gradient (or Colab for that matter) and I can't offer you any help with the install. If you do get it up and running on Gradient, would you be willing to write a brief HOWTO to help others along?

**Comment by GeorvityLabs** [comment]
@lstein , could you share the link to the colab notebook.
I have trained in colab , but the issue comes when trying to run inference , "a photo of *" , it was failing on colab.
I have downloaded the checkpoint (.pt files) locally , and if you have a colab link I can test it out there.
