### ISSUE TITLE
retrieve random seeds

### ISSUE THREAD

**Issue by Neosettler** [lstein/stable-diffusion#481]
greetings,

I'm trying to print seed numbers that are being generated in dream.py. I cant make sense of where the seeds are being populated. Could anyone help out to clear this up?

Thank you,

**Comment by blessedcoolant** [comment]
When an image is generated, you can find the seed for that image in the command that is printed to the screen. The value that follows `-S` argument is the seed.

Additionally, the image that gets saved also has the seed in it. The second value separated by `.` in the file name is the seed.

Thirdly, the entire thing is logged to the `dream_log.txt` file. You can jut search for your filename and the entire command that was used to generate it will be available there. Which will also include the seed followed by `-S`.

The prompt for an image is also saved in the metadata of that image. You can get the seed from there too.

**Comment by Neosettler** [comment]
thank you so much for your feed back, 

long story short, after studying your implementation, I decided to start a QProcess from a QT C++ app and run dream.py. The beauty here is that QProcess is listening to all "print" from dream.py so I can parse incoming messages and act on it on the C++ side. ei: 

in dream.py > print('!initialized')  
C++ > '!initialized' message is received then act on it.

The reverse also works, I can "write" the "!dream" command to the QProcess to simulated command line inputs to dream.py main loop.

That said, my main focus here is to handle all metadata mechanisms on the C++ side. In the spirit of handling one json metadata file per images, whenever a new image is being generated, I want to collect it's seed number and save a json file with a specific naming convention. Therefore, I need to pipe: print(f'!seed:<{seed}>') somewhere in dream.py.

So far, I'm not entirely sure where to put that in, ideally, it would be in dream.py to keep things encapsulated as much as possible.

Any thoughts on what line in dream.py code would it'd go?

**Comment by blessedcoolant** [comment]
Seed logging would happen inside the generate module. Look into `ldm.generate`

**Comment by Neosettler** [comment]
Thank you for your input. humm... I did a search on the entire repo and I got nothing. Would you mind to elaborate? You mean there is no where in dream.py that would also work?

**Comment by lstein** [comment]
Seeds are generated by ldm.dream.generator.base in the method new_seed()

This method is called once just before each image is generated and passed to the torch.seed_everything() method. There is no way to recover the seed *after* the image is generated, so what we do is to keep track of the seed used at the time generator started and write it to the logfile and into the metadata of the PNG image.

**Comment by Neosettler** [comment]
Thank you for your support. ldm.dream.generator.base does spit out the end results but I'd like to open each file after they are being generated and/or save a json file with the seed just before the generation process begins. If the metadata can be written to each image. This is probably where I should look for. Would you mind pointing me to which file this is happening?

**Comment by Neosettler** [comment]
Still digging to find a spot where images are being generated, I yet to find any for loop. I wonder (and searching closely at) where this call is being made:

Generating: 100%|
