### ISSUE TITLE
-F value in Usage stats/Outputs to make command re-usable

### ISSUE THREAD

**Issue by Any-Winter-4079** [lstein/stable-diffusion#483]
I'm on the development branch, and when I generate an image, say with
`"banana sushi" -s10 -W1024 -H1024 -C7.5 -Ak_lms`
 I get something like
```
>> Usage stats:
>>   1 image(s) generated in 54.77s
>>   Max VRAM used for this generation: 0.00G
Outputs:
outputs/img-samples/000564.4225530836.png: "banana sushi" -s10 -W1024 -H1024 -C7.5 -Ak_lms -F -S4225530836
```
This last part is useful because it includes the command I used && the seed
`"banana sushi" -s10 -W1024 -H1024 -C7.5 -Ak_lms -F -S4225530836`
However, reusing it does not work. The problem (I assume) is -F has no value -which by the value, what does -F mean? -f is strength, but upper-case?

The solution would be either to remove -F from this output if no -F value is passed, or to print out the default -F value

**Comment by Any-Winter-4079** [comment]
It's not high in the list of priorities, but it's something to take note of.

**Comment by lstein** [comment]
-F is not supposed to be in the normalized prompt. I will remove.

**Comment by lstein** [comment]
-F is now gone.
