### ISSUE TITLE
ImportError: cannot import name 'ReduceOp' from 'torch.distributed' Mac M1 workaround

### ISSUE THREAD

**Issue by SteveElbows** [lstein/stable-diffusion#485]
Installed today on a M1 Mac Pro with Monterey using the no pyenv route from the installation instructions.

Things went wrong when running preload_models.py. I established that the right python was being used, etc etc, but I was getting errors that all boiled down to:

ImportError: cannot import name 'ReduceOp' from 'torch.distributed'

I had a look on the internet and it sounded like on the M1 PyTorch binaries are currently build with distributed support disabled.

I was able to workaround this issue by commenting the following line out from ~/miniconda3/envs/ldm/lib/python3.9/site-packages/accelerate/utils/operations.py

line 24: from torch.distributed import ReduceOp

preload_models.py then ran successfully and everything is working.

I'm not really a python person so apologies for any flaws in this report and workaround.

**Comment by lstein** [comment]
Gee. This is so annoying.

We've been doing a lot of work on the development branch to make Mac installs more seamless. If you were working from the "main" branch (or using the zip file), could you try checking out **development** and see if the experience is smoother?

You'll have to start from scratch by deactivating and removing the old environment:

~~~
conda deactivate
conda env remove -n ldm
~~~

I appreciate this is very troublesome, particularly after you got it working, but your help will assist other Mac users. If you experienced this problem on the development branch, you don't need to do this! Just let me know which branch the problem occurred on.

**Comment by SteveElbows** [comment]
I've got a 2nd M1 mac that probably doesnt have enough RAM to use with this stuff properly but I can probably at least troubleshoot the installation steps using it. The issue happened with main so I will try development branch on this other mac and let you know what happens, cheers.

**Comment by SteveElbows** [comment]
Development branch worked on my other M1 mac without that issue. I suppose cannot totally rule out some other factor having caused the problem on the other computer so might try main branch on this other machine too.

**Comment by SteveElbows** [comment]
Main seemed to work ok on the other mac, so I'll probably file around to see if I can find out why I had these problem on the original mac, in ase I can provide any useful info.

**Comment by SteveElbows** [comment]
OK I went back to original M1 mac. Ruled out a couple of things, established that a fresh install of main branch still had this issue, established that the development branch fixes the issue on this machine too. Thanks for your help.
