### ISSUE TITLE
Error: 'NoneType' object has no attribute 'enhance'

### ISSUE THREAD

**Issue by glonlas** [lstein/stable-diffusion#487]
**Describe your environment**
- GPU: [cuda/amd/mps/cpu] MPS and Cuda
- VRAM: [if known] N/A
- CPU arch: [x86/arm] ARM
- OS: [Linux/Windows/macOS] macOS
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)] miniconda
- Branch: [if `git status` says anything other than "On branch main" paste it here] development
- Commit: [run `git show` and paste the line that starts with "Merge" here] bfb278127923fbd461c4549a4b7f2f2c1dd34b8c

**Describe the bug**
Error `'NoneType' object has no attribute 'enhance'` when using GFPGAN via the Web UI.
```
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
```

**To Reproduce**
**On MPS:** 
1. Run the server with `python scripts/dream.py --full_precision --web`
2. Generate an image with `Upscaling Level = x2|x3|x4` (`GPFGAN Strength` can be anything)

**On CUDA**
1. Run the server with `python scripts/dream.py --full_precision --web`
2. Generate an image with `Upscaling Level = x3` (`GPFGAN Strength` can be anything)

The terminal will return 
```
>> Real-ESRGAN Upscaling seed:XXXX : scale:3x
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
```

**Expected behavior**
The generation of the image works with GPFGAN and Upscaling without any trouble.

**Comment by glonlas** [comment]
I confirm the issue is visible in the current `development` branch. But [this PR fix it](https://github.com/lstein/stable-diffusion/pull/424). When I switch to this PR upscale work.


**When on current `development` the terminal output is: (Failed)**
```
>> Real-ESRGAN Upscaling seed:1586105133 : scale:2x
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
```

**When I switched to the [PR #424](https://github.com/lstein/stable-diffusion/pull/424)  the terminal output is: (Successful)**
```
>> Real-ESRGAN Upscaling seed:1857161085 : scale:2x
127.0.0.1 - - [10/Sep/2022 23:18:09] "GET /outputs/img-samples/000008.1857161085.png HTTP/1.1" 200 -
[0 Apple M1]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M1]  bugsbn1=0  bugbilz=97  bugcopc=0  bugihfa=0
[0 Apple M1]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M1]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
0.00%
11.11%
22.22%
33.33%
44.44%
55.56%
66.67%
77.78%
88.89%
>> Usage stats:
>>   1 image(s) generated in 30.51s
>>   Max VRAM used for this generation: 0.00G
```

**Comment by glonlas** [comment]
# For System other than MPS
A fix is needed.

# To understand the error.

The error happens in:
```
>> Real-ESRGAN Upscaling seed:3350596856 : scale:2x
Traceback (most recent call last):
  File "/ldm/generate.py", line 467, in upscale_and_reconstruct
    image = real_esrgan_upscale(
  File "ldm/gfpgan/gfpgan_tools.py", line 149, in real_esrgan_upscale
    output, img_mode = upsampler.enhance(
AttributeError: 'NoneType' object has no attribute 'enhance'

>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
```

When we look at the code, this happens when: 
```python
def real_esrgan_upscale(image, strength, upsampler_scale, seed):
    print(
        f'>> Real-ESRGAN Upscaling seed:{seed} : scale:{upsampler_scale}x'
    )

    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=DeprecationWarning)
        warnings.filterwarnings('ignore', category=UserWarning)

        try:
            upsampler = _load_gfpgan_bg_upsampler(
                opt.gfpgan_bg_upsampler, upsampler_scale, opt.gfpgan_bg_tile
            )
        except Exception:
            import traceback

            print('>> Error loading Real-ESRGAN:', file=sys.stderr)
            print(traceback.format_exc(), file=sys.stderr)

    output, img_mode = upsampler.enhance(
        np.array(image, dtype=np.uint8),
        outscale=upsampler_scale,
        alpha_upsampler=opt.gfpgan_bg_upsampler,
    )
```

**Comment by glonlas** [comment]
As of today the x3 cannot work with the implementation of the python lib of Real-ESRGAN. While it works if we use the Bin. 
@blessedcoolant you were 100% about the non support of x3 upscaling. 

We need to revert this PR: https://github.com/lstein/stable-diffusion/pull/442 (I will do the revert)

cc: @lstein

**Comment by lstein** [comment]
@glonlas could you confirm that upscaling is now working on the Macintosh platform? Please check either "development" HEAD, or the tag release-candidate-1.14.2.

Thnx

**Comment by Any-Winter-4079** [comment]
For the time being it works. In the future, it may be worth looking into using the executables (there's versions for Linux/Windows/Mac) if these reports are true https://github.com/lstein/stable-diffusion/discussions/511#discussioncomment-3625915 (about quality) and https://github.com/lstein/stable-diffusion/discussions/511#discussioncomment-3626482 (about time). But anyway, it works
