### ISSUE TITLE
Allow loading of different weight files

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#49]
It would be great if I could specify weight file during script launch, like so:

python scripts/dream.py --model=sd13
python scripts/dream.py --model=sd14
python scripts/dream.py --model=sd12
python scripts/dream.py --model=sd11
python scripts/dream.py --model=sd13_leaked

This command should go to folder \models\ldm\stable-diffusion-v1\ and find a file with exact name passed in argument list + add ".ckpt" extension to it to load a model.

The reason for this request is that all these models produce slightly different images for the same Seed and prompt and the latest version is not the best one for all prompts.

**Comment by lstein** [comment]
Sure! Great suggestion and easy to implement (I think). Is it OK to assume that all models will have the same associated configuration file (configs/stable-diffusion/v1-inference.yaml) or should I allow for selection of the conf file as well?

**Comment by morganavr** [comment]
config is the same. At least it works out of the box.
