### ISSUE TITLE
prompt2prompt (cross attention control)

### ISSUE THREAD

**Issue by tmm1** [lstein/stable-diffusion#490]
Some interesting discussion and developments on r/StableDiffusion regarding prompt control

This implementation seems very straightforward and would be worth pulling in:

https://github.com/Doggettx/stable-diffusion/commit/3b5c504bb0c11a882252c0eb2b1955474913313a

More discussion:

- https://reddit.com/r/StableDiffusion/comments/xas2os/simple_prompt2prompt_implementation_with_prompt/
  - https://github.com/Doggettx/stable-diffusion/tree/prompt2prompt
- https://www.reddit.com/r/StableDiffusion/comments/xapbn8/prompttoprompt_image_editing_with_cross_attention/
  - https://github.com/bloc97/CrossAttentionControl
- https://reddit.com/r/StableDiffusion/comments/x98py5/reproducing_the_method_in_prompttoprompt_image/
  - https://arxiv.org/abs/2208.01626

EDIT: I see @Doggettx is already active on this repo, so I am singing to the choir.

**Comment by hipsterusername** [comment]
A repo that I stumbled on with another implementation of Cross Attention capabilities —

https://github.com/bloc97/CrossAttentionControl

**Comment by lstein** [comment]
@doggettx, this looks really cool. I'd welcome a PR.

**Comment by Doggettx** [comment]
Never done a PR ;) Will have to check how that works

**Comment by tildebyte** [comment]
I'm going to put this on the ToDo list.

I skimmed the original paper last night; this is an incredibly powerful technique...

**Comment by tmm1** [comment]
hm where was this implemented?

I started to port @Doggettx's patch but it is non-trivial to translate

**Comment by tildebyte** [comment]
> I started to port @Doggettx's patch but it is non-trivial to translate

Agreed,  @Doggettx' patch was based on old very old code, and a lot has changed in here

@lstein; Did you perhaps conflate this with #621? This is a completely different feature.

**Comment by morganavr** [comment]
> 

https://github.com/Doggettx/stable-diffusion/tree/prompt2prompt-v2
