### ISSUE TITLE
Generated images are pure green

### ISSUE THREAD

**Issue by pedropachecog** [lstein/stable-diffusion#50]
It runs without any error, but it generates images where all pixels are the same shade of green (#007B00).

In the basujindal repo, changing the default precision from "autocast" to "full" in the file optimized_txt2img.py fixes this problem. So I tried to do the same for this repo in the file scripts/orig_scripts/txt2img.py but it didn't make a difference.

Whenever I run dream.py with --full_precision it runs out of memory. I have 6 GB of VRAM.

**Comment by lstein** [comment]
Oh dear. Have you tried the original CompViz/stable-diffusion? My code is a close fork of theirs, and if there's a solution there, it'll work here.

I haven't had any other "green screen of SD death" complaints, but maybe  they'll start pouring in now. :-(

**Comment by lstein** [comment]
I hear on Discord that this problem can appear when running the script on a GPU that does not support mixed precision math. You can work around it by passing the -F (full-precision) flag to dream.py. However, this will increase the script's VRAM requirements.

**Comment by Zenahr** [comment]
@lstein I tried to pass `-F` but this options seems gone now. Has the API for setting the precision level changed?

Also, using T2I.prompt2image() doesn't seem to have a "precision" or "precision_full" parameter available.
