### ISSUE TITLE
Training a model

### ISSUE THREAD

**Issue by nihirv** [lstein/stable-diffusion#501]
Hi there.

Thanks for the fantastic work.

I'm currently working through getting a model up and training on a smaller dataset such as lsun, but it'd be very useful to newcomers of the repo if you could provide some commands/instructions that can get us started with training a model from scratch using one of the existing configs

Thank you

**Comment by lstein** [comment]
I'm afraid we've been spending our time working on the inference (image generation) side of the equation and have not worked on improving (or documenting) the training side. Have patience and we'll get to the training. In the meantime, the best we have to offer is the section named "Personalizing Text-to-Image Generation" in the README.

**Comment by nihirv** [comment]
I've also found some instructions on the latent diffusion repo https://github.com/CompVis/latent-diffusion which can at least help get up and running with using this repo to train latent diffusion models. Though it looks like there's some differences in the main.py files between this repo and theirs.

Seems like this issue has someone who managed to start training a model too: https://github.com/lstein/stable-diffusion/issues/386. 

When I figure it out I'll open a PR, but any help in the mean time is appreciated

**Comment by nihirv** [comment]
ok, I got something training on LSUN but it required some me commenting out some code that was added in the ddpm.py file. 

I had to make a couple of other changes, but a large part of the changes were commenting out lines 668-688.

I'm not entirely sure of the best way to go about opening a PR for this change. It looks like that code was added in specifically for using this repo for inference and text-to-image.. I'm still getting used to the codebase so I'll seem if there is a clean way to use some configs to enable/disable this behaviour

**Comment by lstein** [comment]
@Oceanswave, could you take a look at this? The lines in question were added by you in commit 8952196bbfa75cf2f4a66a847e1f3b7a50d76cf5 for the textual inversion support. It looks like there should be a conditional around them to allow for conventional training to work again.

**Comment by lstein** [comment]
@nihirv, the thing to do is to make a PR against the development branch. I and others will examine the changes you made in the context of textual inversion support, and will advise you if changes need to be made. I really appreciate your working on this.

Also heads up to #386 that @nihirv has isolated the problem.

**Comment by nihirv** [comment]
@lstein I'll open a PR later today.

Seems most of the codebase is specific to providing text inputs. You'll see what I mean when I open the PR

**Comment by nihirv** [comment]
@lstein opened #546

**Comment by lstein** [comment]
Much obliged to you.
