### ISSUE TITLE
Censorship?

### ISSUE THREAD

**Issue by Neosettler** [lstein/stable-diffusion#502]
greetings, 

SD vanilla have censorship enabled by default. What is the censorship status with this repo?

Thank you,

**Comment by Neosettler** [comment]
Also, is there any hidden watermarks?

**Comment by hipsterusername** [comment]
The safety checker and watermark lines don’t exist in the files, which presumably indicates they’ve been removed in this fork.

**Comment by lstein** [comment]
No censorship and no watermarks at present. However, I think watermarks will be added as an optional feature in the next release.

**Comment by peterc** [comment]
It's not *quite* the same, but the prompts are embedded as plain text into the PNG, so if you distributed the raw output, it's theoretically possible to extract what prompts you used (this is generally considered a good thing especially when you forgot what you were doing to create an image!)

**Comment by lstein** [comment]
So is the feature request to install the NSFW filter and watermarking? I'm happy to do that.

**Comment by hipsterusername** [comment]
I think he was confirming they weren’t present, since it wasn’t explicitly called out in the readme one way or the other.

**Comment by lstein** [comment]
Good point. Is the lack of censorship/watermarking something people would consider a "feature" that should be called out in the feature list, or is it something that the less said about the better?

**Comment by peterc** [comment]
(Solely my personal opinion, but) I think "censorship" is a tricky term as it evokes different things in different groups of people. I think things are OK as they are given the experimental nature of the project, but if it's a FAQ it could warrant a "privacy" section in the README to state the facts around what the code does or does not do. For example: no watermarking, no filtering of output, no "phoning home", metadata is written, etc.

**Comment by tildebyte** [comment]
> Is the lack of censorship/watermarking something people would consider a "feature" 

At a minimum, it should be noted.

As a semi-aside, my understanding (possibly incorrect) is that the watermark (which consists entirely of the text "Stable Diffusion") is there so that **future** models aren't contaminated (overwhelmed, even?) by ML-generated images.

**Comment by lstein** [comment]
> As a semi-aside, my understanding (possibly incorrect) is that the watermark (which consists entirely of the text "Stable Diffusion") is there so that future models aren't contaminated (overwhelmed, even?) by ML-generated images.

I hadn't thought of that. I'd better bring the watermarking code in.

**Comment by hipsterusername** [comment]
Do we know what is encoded in the watermark? Privacy (as noted above) may be the better way to view this, and I imagine an "opaque" watermarking process might be seen as imposing on that. 

From what I can see suggested (anecdotally), it is indeed just a "Stable Diffusion" flag. However, I imagine folks might still be wary.

**Comment by tildebyte** [comment]
The code doesn't lie, and upstream simply has the string "StableDiffusionV1" (converted to pixel data, of course)

```python
wm = "StableDiffusionV1"
wm_encoder = WatermarkEncoder()
wm_encoder.set_watermark('bytes', wm.encode('utf-8'))
.
.
.
# Here, 'img' is the generated image
def put_watermark(img, wm_encoder=None):
    if wm_encoder is not None:
        img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
        img = wm_encoder.encode(img, 'dwtDct')
        img = Image.fromarray(img[:, :, ::-1])
    return img
```

which is then called as `img = put_watermark(img, wm_encoder)`

**Comment by hipsterusername** [comment]
@lstein - Proposal for some readme text, if helpful - yours to edit and change as you see fit. I am assuming that only the code setting these flags has been removed (e.g., safety_cheker_input  and image, has_nsfw_concept). 

This seems to implement a "Safety Checker" flag, which may be interesting to implement as a feature if users find it useful. https://github.com/huggingface/diffusers/pull/254/files



### Privacy & Safety
As a principle, the contributors to this fork strive to ensure the ethical development and use of this emerging technology. Decisions have been made regarding the safety checking & watermarking implementations in Stable Diffusion.

**Safety Checking** - 
Safety Checking has been disabled by default from this fork as is common among other forks looking to access the full range of model output. This may result in outputs uninhibited by filters that would remove things commonly seen as "NSFW". If you are using this for any use cases which this output may be inappropriate, it is advised to re-implement this checking manually by updating txt2img.py with

`safety_cheker_input = self.feature_extractor(self.numpy_to_pil(image), return_tensors="pt").to(self.device)
        image, has_nsfw_concept = self.safety_checker(images=image, clip_input=safety_cheker_input.pixel_values)`

**Watermarking**
Watermarking allows for the encoding of information into images which can then be decoded through observing pixel-level data in the image. This can be used for various purposes and reasons, depending on the party implementing the watermark. With any kind of watermarking implementation, privacy can be a concern, if any personally identifiable information is encoded. The code invoking the watermark encoder is accessible within this repo, and is used primarily to identify ML generated content to prevent future model iterations of Stable Diffusion from training on its own outputs. A simple "StableDiffusionV1" watermark is added to output images for this purpose, and there are absolutely no privacy implications associated with the encoding of this information. It helps ensure that the Stable Diffusion ecosystem will continue to compete in quality model development against other closed-source and centralized offerings, but if you have any objections, the code for the Watermark Encoder can be removed manually.

The purpose of this repo is to offer a sophisticated and fully featured toolset, combining the latest developments in the space, while working towards common goals as a broader community. We appreciate your help!

**Comment by pci** [comment]
@hipsterusername That seems a really good idea, though on the 'Safety Checking' - I believe users will need similar in `ldm/generate.py` otherwise dream.py, etc. would still be unfiltered?

**Comment by hipsterusername** [comment]
The flag would seemingly be useful to some to be able to control as a "Default", and more easily controlled by end-user than directly modifying multiple .py files. I know that there has been discussion around other "default" settings users would like to be able to control - e.g., resolutions, samplers, etc. 

I just don't know how much of a priority it is. Most are probably fine with the checker off, by default - The readme is more of a helpful FYI for the corner cases.

**Comment by ZeroEkkusu** [comment]
> So is the feature request to install the NSFW filter

IMO giving users freedom to create by default is one of the strengths of the fork.

If such limitations are ever implemented, there should be an option to override the same. A flag, as others have suggested, and/or an environment variable would be good UX.

**Comment by Neosettler** [comment]
> No censorship and no watermarks at present.

> The code doesn't lie, and upstream simply has the string "StableDiffusionV1" (converted to pixel data, of course)

getting mixed messages here, is there watermarks embed in generated image or not? If yes, how it is being decode/visualized?

**Comment by tildebyte** [comment]
The watermark code is NOT in this repo. I was referring to the original watermark code, which is still upstream (in CompVis/stable-diffusion).

> If yes, how it is being decoded/visualized?

The same library which writes the watermarks can read them, though it's been weeks since I looked into it (briefly), so I don't remember the details.

**Comment by LexiconCode** [comment]
Filtering is not censorship when it's optional at the user's discretion. There are number of comments that mention there are cultural and personal differences in what's considered explicit or triggering. Therefore I think it's worthwhile pursuing a customizable filter that's available from the web interface.

Filtering could go a number of ways but categorically
- NSFW content
	- Generating explicit images unintentionally is a possibility and not always desirable. 
- Keywords or associations used in generation
	- For example a fear of spiders eg arachnophobia. 
	
This can be made into a new issue if deemed appropriate.

**Comment by lstein** [comment]
We can include the Hugging Face NSFW filter, although I'm not sure how much
work this will require since we are not using their Diffusers library at
present. As far as keyword filtering goes, I think this is up to the writer
of the prompts to avoid. For example, it is not clear that the word
"skyscraper" would generate imagery that could trigger someone with a fear
of heights.

**Comment by lstein** [comment]
> The code doesn't lie, and upstream simply has the string "StableDiffusionV1" (converted to pixel data, of course)
> 
> ```python
> wm = "StableDiffusionV1"
> wm_encoder = WatermarkEncoder()
> wm_encoder.set_watermark('bytes', wm.encode('utf-8'))
> .
> .
> .
> # Here, 'img' is the generated image
> def put_watermark(img, wm_encoder=None):
>     if wm_encoder is not None:
>         img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
>         img = wm_encoder.encode(img, 'dwtDct')
>         img = Image.fromarray(img[:, :, ::-1])
>     return img
> ```
> 
> which is then called as `img = put_watermark(img, wm_encoder)`

I hope someone will volunteer to bring the watermarking code in. It is benign and useful.
