### ISSUE TITLE
Remove Homebrew dependencies

### ISSUE THREAD

**Issue by peastman** [lstein/stable-diffusion#509]
**Is your feature request related to a problem? Please describe.**
The install instructions for Mac say to use Homebrew for installing cmake, protobuf, and rust.  That isn't needed, since all those packages are available through conda.  Using an extra package manager creates extra steps for the user and extra chances for things to go wrong.

**Describe the solution you'd like**
Just add those packages to `environment-mac.yaml` and they'll get installed automatically.  There's no need for the user to install or use brew.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lstein** [comment]
There was an extensive discussion of getting the same versions of python, torch, etc running smoothly on all three platforms, and we ended up with a bit of a compromise. You can catch up with the discussion at #331, but with the warning that it's a **long** thread.

It's possible that we should not have introduced brew into the mix (is that a mixed metaphor?), but I suggest waiting a few days for @magnusviri to return from his break. He is the resident Mac expert here.

**Comment by peastman** [comment]
Thanks.  For what it's worth, I installed them with conda and everything seems to be working well.

**Comment by papaver** [comment]
installing `onnxruntime` in conda fixes the protobuf dependency when it needs to build onnx from scratch and binaries are not available.  would def be nice to be completely self contained instead of relying on brew for libraries (don't use brew myself).

don't think installing rust separately is an issue.
