### ISSUE TITLE
img2img generates 512x512 image although 568x568px were specified

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#51]
Here's a prompt:
> "photo dogs playing with cats happy family" -W 576 -H 576 -n 1 -S 2152503213 --init_img=./init-images/00036.png --strength=0.6 -C 10 -s 100

It's worth mentioning that provided init_img has dimensions of 512x512px but I thought that if I specified explicit -W and -H after the prompt then image should be created with 576x576px

**Comment by thezveroboy** [comment]
double not single:

--H H                 image height, in pixel space
--W W                 image width, in pixel space

**Comment by morganavr** [comment]
> double not single:
> 
> --H H image height, in pixel space --W W image width, in pixel space

![image](https://user-images.githubusercontent.com/51041813/186272490-e5f79925-c7a8-48a3-9da3-e68cd626fd5a.png)

**Comment by lstein** [comment]
You can use either -W or --width (short vs long option).

The issue here is that the init image is used as the starting point for image generation in img2img mode, and whatever width and height you specified will be ignored. I'll add a warning message for this case.
