### ISSUE TITLE
ANNOUNCE: Please help beta test release 1.14

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#512]
Hi All,

After quite a lot of work by many hands, we have a release candidate for 1.14. It runs on all three platforms (Windows, Mac, Linux), and has memory optimizations that allow it to produce 512x512 images on 4 GB GPU cards, and up to 2560x2560 images on 32 GB GPUs. 

This release also adds a bevy of new features, including inpainting, easier face-fixing and upscaling, [seamless tiling mode](https://github.com/lstein/stable-diffusion/pull/339), and an improved web interface.

We would like to get confirmation that the candidate is running acceptably well on all three platforms with a variety of GPUs and system hardware. If you have some time, please read through the testing instructions at Discussion #511 and the preflight checklist at #457.  Report any anomalies in comments to Discussion #511.

Happy bug hunting!

Lincoln and the stable-diffusion dream team.

**Comment by Any-Winter-4079** [comment]
Testers with M1 16-32GB
If you want the best of both worlds (fast 512x512 image generation, as in `main` branch and generating larger images than you could before), please participate in https://github.com/lstein/stable-diffusion/discussions/457#discussioncomment-3626695

**Comment by LipcaCZ** [comment]
Great release! On a laptop with RTX 3060 6GB I'm now able to generate images in resolution up to 960x960. Before I was able to make only 576x512.
I also love that new web ui loads all old images, but can't say the same about that clicking on the image just opens the image, but does not fill in settings like it was in previous releases. Please put this back, users will be still able to open it by right clicking on the image and choosing open image in new tab in browser.
