### ISSUE TITLE
Loading huggingface textual inversions

### ISSUE THREAD

**Issue by tmm1** [lstein/stable-diffusion#513]
🤗/sd-concepts-library has prettained textual inversions: https://huggingface.co/sd-concepts-library

would be nice to be able to easily load and use these

cc https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/151

**Comment by lstein** [comment]
The ability to read hugging face .bin files was just added today. You'll find it in the development branch, and documented in docs/features/TEXTUAL_INVERSION.md

**Comment by tmm1** [comment]
Thank you!

https://github.com/lstein/stable-diffusion/blob/development/docs/features/TEXTUAL_INVERSION.md

**Comment by tmm1** [comment]
Looks like training doesn't yet work on M1. Has anyone started looking into this alread?

**Comment by tmm1** [comment]
I confirmed that this does work.

For example, download https://huggingface.co/sd-concepts-library/ugly-sonic/blob/main/learned_embeds.bin and save as uglysonic.bin

Then run `scripts/dream.py --embedding_path uglysonic.bin` and use `"a photo of <ugly-sonic>"` and you will get a photo:

![000318 458685514](https://user-images.githubusercontent.com/2567/189800848-76bce25e-7510-45ea-97cb-828a50fa11af.png)
