### ISSUE TITLE
Environment name changed to sd-ldm, not working with inplace update

### ISSUE THREAD

**Issue by ArDiouscuros** [lstein/stable-diffusion#525]
**Describe your environment**
Release 
**Describe the bug**
Environment name changed to sd-ldm, so after update to latest release and running conda env update from  active environment ldm was getting errors like
(ldm) G:\Programs\SDAI\StableDiffusionManual\repo\lstein\stable-diffusion-main>python scripts/dream.py --full_precision
Traceback (most recent call last):
  File "scripts/dream.py", line 12, in <module>
    import ldm.dream.readline
ModuleNotFoundError: No module named 'ldm.dream'

**Expected behavior**
Keep old env name or give a hint in the documentation

**Comment by lstein** [comment]
The change was inadverent. I have just made a 1.14.1 release to correct the issue. Sorry for the inconvenience!
