### ISSUE TITLE
Dream process gets Killed unexpectedly 

### ISSUE THREAD

**Issue by Yakumwamba** [lstein/stable-diffusion#53]
![Screenshot 2022-08-23 at 23 53 58](https://user-images.githubusercontent.com/72974932/186273263-73f2512b-6f8d-423f-bef1-357903dc01a6.png)

Sorry for dumb question
Im on linux  and when I run the `python3 ./scripts/dream.py` I get event "Killed" 
Also trying to change my env to ldm gives me these errors which I have tried to install the packages oone by one but nothing so far.....I tried to run `conda upgrade --all` but still cant get the packages to install. Please Kindily assist me in any way 

![Screenshot 2022-08-23 at 23 55 55](https://user-images.githubusercontent.com/72974932/186273478-66d53d83-4a34-4a83-9b86-c52a1edf42fc.png)

Yaku

**Comment by lstein** [comment]
You to have be working in the anaconda3 (miniconda) command window. Then try "conda env create -f environment.yaml" again. It should work.

**Comment by govardhan26** [comment]
I have the same issue too, i'm working with pycharm's venv. @lstein can you help me out with this?

(venv) activelearning@activelearning:~/Documents/govardhan/invokeAI/InvokeAI$ python3 scripts/invoke.py --web

* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Killed
