### ISSUE TITLE
The web server does not display the generate image

### ISSUE THREAD

**Issue by i3oc9i** [lstein/stable-diffusion#536]
**Describe your environment**
- GPU: mps
- VRAM: M1 unified 128G
- CPU arch: arm
- OS: macOS 12.5.1
- Python: miniconda 3.10.5
- Branch: release 1.4.1
- Commit: 9b28c65e4b0526956fd90ad86e2118536e4eaa9b

**Describe the bug**
I start the `dream.py` script using the `--outdir ` options. The image is generated correctly in the specified outdir location, but the web server does not display the image when the output directory is located in another location but the dream server.

The server log is
`127.0.0.1 - - [13/Sep/2022 10:22:02] "GET /Users/ivano/Pictures/dream/000001.1168870281.png HTTP/1.1" 404 -`

I have tested with chrome, firefox and safari

Note that the alternative image is displayed showing the seed and the prompt, so I dont think is a problem of access right.

If the `--outdir` option is not given or if it is relative to the location of the `dream.py` script then all works as expected.

**To Reproduce**
`python scripts/dream.py --full_precision --outdir /Users/ivano/Pictures/dream --web`

**Expected behavior**
the image is displayed in the web browser respecting the value of the `--outdir `option.

**Screenshots**

![Screen Shot 2022-09-13 at 10 12 17 AM](https://user-images.githubusercontent.com/4766500/189850610-89d1bcec-9a52-4c31-a1ea-bf79fe2f9fc9.png)

**Comment by peterc** [comment]
I encountered this as well. With v1.13, the `--outdir` option was ignored and everything ended up in the relative `outputs` folder. Now it's respected and followed, but the HTTP server can't access the files as they're outside of its usual space. Forming a symbolic link at startup *or* proxying the images will probably be necessary.

**Comment by peterc** [comment]
Oh, looking at the code in `server.py`, it seems like it's already proxying any paths that aren't /, /config.js, /run_log.json or /cancel, but there's probably a better way to do it specifically and securely for outputs now with the new feature. Something like having /images specifically only access files in the `--outdir` specified folder. If I come up with a patch I'll post again – my Python is rusty.

**Comment by lstein** [comment]
Sorry, I was working to fix this bug and didn't see @peterc 's solution come in. This issue is now addressed in PR #550. In addition to the bad behavior that @i3oc9i observed, the original implementation had a gaping security hole that would allow the web user to download *any* file in the stable-diffusion directory. I'm glad this bug was reported, because otherwise the hole would have been missed. 

@peterc your solution will work, but you have hardcoded the output directory and so it's not fully generalizable.

Thanks for everyone's patience.

**Comment by peterc** [comment]
That is totally fine. I knew it was a bit inelegant, I just wanted to get it working for myself in the interim, and thought I'd share my work ;-) All a good learning experience! This is a fantastic project, and I hope I'll be able to contribute in a more concrete way in time.

**Comment by i3oc9i** [comment]
fixed in development 9df743e2bf54829eabe87fbbb1f4aaa1c75ba0c1
