### ISSUE TITLE
using k_euler_ancestral

### ISSUE THREAD

**Issue by Parfolomew** [lstein/stable-diffusion#54]
i've found that if editing this line in txt2img.py

samples_ddim = K.sampling.sample_lms(model_wrap_cfg, x, sigmas, extra_args=extra_args, disable=not accelerator.is_main_process)

to *this*

samples_ddim = K.sampling.sample_euler_ancestral(model_wrap_cfg, x, sigmas, extra_args=extra_args, disable=not accelerator.is_main_process)

it *actually works*

it appears to work in another iteration i'm using, but i do not believe that it would carry over to dream.py since it does not appear to utilize the txt2img script anymore.

utilizing k_euler_ancestral would be extremely vital for many users since it has a faster sampling rate and is more accurate at lower steps!

**Comment by morganavr** [comment]
There is a PR
https://github.com/lstein/stable-diffusion/pull/52
