### ISSUE TITLE
`PromptFormatter().normalize_prompt()` should output spaces between flags and values

### ISSUE THREAD

**Issue by psychedelicious** [lstein/stable-diffusion#554]
**Is your feature request related to a problem? Please describe.**
The normalized prompt outputs something like this:
`"kangaroo" -s15 -W512 -H512 -C7.5 -Ak_lms --fit -S3037685144`

IMO this is far less readable than:
`"kangaroo" -s 15 -W 512 -H 512 -C 7.5 -A k_lms --f it -S 3037685144`

On a related note, the seed used is not written by this function - it is written manually when `save_image_and_prompt_to_png()` is called, using string formatting. Feels awkward. 

Besides being more readable (IMO), spaces between flags and values make the command parse-able by [`shlex`](https://docs.python.org/3/library/shlex.html#shlex.split). If I can `shlex.split()` a `dream.py` REPL command, I can reconstruct it in a UI.

I suppose when the metadata RFC is finalized, this will be a moot point as we will write that data directly to the image, in a far more consumable format.

**Describe the solution you'd like**
Add some spaces to `PromptFormatter().normalize_prompt()`

**Describe alternatives you've considered**
Write a parser that can deal with no spaces - yikes!

**Comment by lstein** [comment]
This fix is coming in my next PR.

**Comment by lstein** [comment]
This is now in development branch.
