### ISSUE TITLE
img2img is no longer possible, because as soon as -I is used, the script tries to do inpainting instead

### ISSUE THREAD

**Issue by n00mkrad** [lstein/stable-diffusion#561]
**Describe your environment**
- GPU: RTX 3090
- VRAM: 24 GB
- CPU arch: x86_64
- OS: Windows 10
- Python: miniconda
- Branch: development
- Commit: dedf8a36924787731d29418521a0619c3d6d147c

**Describe the bug**
img2img is no longer possible, the script will try to run inpainting, but since there is no mask or transparent region, it simply outputs the input image.

**To Reproduce**
Run `prompt of your choice -f 0.5 -I init.png`

**Expected behavior**
I get an image that resembles my prompt while being influenced by the init image

**Additional context**
A CLI switch to enable inpainting is needed.

**Comment by lstein** [comment]
I cannot confirm this. Is it possible that your image contains transparent pixels (i.e. a non-empty alpha layer)? If the image contains any transparent pixels, it will try to do inpainting.

To confirm, open your image in a photoeditor program and remove its alpha layer if present. Then try again to do img2img.

**Comment by n00mkrad** [comment]
Ah, this was caused by some code I wrote that automatically resizes the input and saves it as PNG, apparently with an alpha layer.

**Comment by n00mkrad** [comment]
I'm still unhappy with this implementation - It claims that my BMP input has transparent pixels, even though BMP does not support alpha.
