### ISSUE TITLE
Textual inversion crashes if no initializer words are passed

### ISSUE THREAD

**Issue by hopibel** [lstein/stable-diffusion#572]
**Describe the bug**
Running textual inversion without initializer words causes embedding_manager to use a randomly initialized vector instead. This triggers a crash because SD expects vectors of length 768, not 1280.

Crash message:
```
  File "/home/hope/src/sd/lstein-sd/ldm/modules/embedding_manager.py", line 156, in forward
    embedded_text[placeholder_idx] = placeholder_embedding
RuntimeError: shape mismatch: value tensor of shape [1280] cannot be broadcast to indexing result of shape [2, 768]
```

Relevant line: https://github.com/lstein/stable-diffusion/blob/main/ldm/modules/embedding_manager.py#L85
Correct value in rinongal's repo: https://github.com/rinongal/textual_inversion/blob/main/ldm/modules/embedding_manager.py#L60

Manually changing the value to 768 fixes the crash.

**To Reproduce**
1. Modify `configs/v1-finetune.yaml` and set `initializer_words: []`
2. In the project root: `python main.py --base ./configs/v1-finetune.yaml -t --actual_resume <path/to/model.ckpt> -n 'test' --gpus 0, --data_root <folder with images>`
3. Crash with RuntimeError shown above

**Expected behavior**
Training proceeds normally

**Comment by lstein** [comment]
I've made this change in the development branch. Could you confirm that it is working?

**Comment by hopibel** [comment]
Works on my end 👍
