### ISSUE TITLE
M1 Mac slowdown

### ISSUE THREAD

**Issue by thelamedia** [lstein/stable-diffusion#578]
GREAT job you guys on the overall improvements in 1.14.  One note is that the memory improvements made for smaller graphics cards did seem to take pressure off the system in an M1, but did slow down generation time for me by about 50%.  Before this pull, a 512x512 at 50 steps would take between 28 and 32 seconds.  Now, 40 steps take between 48-55 on average.  I can see that the memory utilization is lower, which might be contributing to this slow down.  I'm not going to complain though!  Pretty much everything I've tested on my M1 works like a charm in the latest release.  KUDOS!

**Comment by Any-Winter-4079** [comment]
How much RAM do you have in your M1?

**Comment by Any-Winter-4079** [comment]
Some samplers are slower, though.
`dream> ocean` takes 28s for me (DDIM sampler)
but
`dream> ocean -m k_dpm_2_a` takes 56s (K_DPM_2_A sampler)
Not sure if it's Mac specific.

**Comment by thelamedia** [comment]
> How much RAM do you have in your M1? We tested with all RAM sizes from 8 to 128GB and reported speeds were not worse than before. Besides, every M1 except 8GB ones are running the original CompVis code (which is the fastest) for 512x512. So I'm curious about what might be going on.

I'm running 64 GB M1 Max. 
`dream> ocean` takes 59 seconds for me. 
`dream> ocean -m k_dpm_2_a` takes 1:55

**Comment by Any-Winter-4079** [comment]
Same M1 Max here. 64GB. That is very strange.
On a side note, I do see my times are more unstable (before it used to climb to 1.78-1.82it/s and stay there, while now one random generation may drop to 1.5it/s or even 1.15it/s. But I didn't experience that while I was testing all of the M1 fixes (it was at least a couple of days and many, many times I ran the dream > prompt, so maybe there's a change afterwards that made things a bit shaky?)

In any case, even with shakier times, I am nowhere near those times you report. Are you using the development branch?

**Comment by thelamedia** [comment]
I'm using the main branch.  I'll give everything a fresh install later tonight on a new conda config and see if I can get those times any lower.  Very strange indeed!

**Comment by Any-Winter-4079** [comment]
If you setup a new environment, try arm64 (if you don't have it).

**Comment by thelamedia** [comment]
I do have arm64 installed currently. Thanks.  I'll report back.

**Comment by thelamedia** [comment]
New environment, fresh install, same timings. Any other suggestions?

**Comment by Any-Winter-4079** [comment]
This is a bit of how versioning is on my side,
`python --version`
python 3.9.13

`conda list torch`
pytorch                   1.12.1                  py3.9_0    pytorch
pytorch-lightning         1.7.5                    pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
torchvision               0.13.1                 py39_cpu    pytorch

OS version: 12.5.1

**Comment by thelamedia** [comment]
The development branch brought my times back into range!  50 steps now completes at 32 seconds with dev rather than 59 seconds with main.

**Comment by Any-Winter-4079** [comment]
Awesome! Happy to see the performance is back!
