### ISSUE TITLE
Embiggen works on M1 but not well

### ISSUE THREAD

**Issue by heurihermilab** [lstein/stable-diffusion#586]
MacBook Pro 14" 16MB, M1 Pro CPU
- CPU arch: ARM
- OS: macOS 12.6
- Python: 3.10.6 in base Conda, 3.10.? in ldm environment
- Branch: On branch development / Your branch is up to date with 'origin/development'.
- Commit: Merge: 9208bfd b02ea33 [development + #553]

Embiggen is working on the M1 but not well.  Doing an x4 on a 1344 x 768 input file took 22,618 sec (6 1/4+ hrs), and one of the 25 tiles was fully black.

I have an installation of Real-ESRGAN elsewhere on the same machine that does the same in 4.5 seconds.

I'm happy to do further testing to help resolve this.

**Comment by heurihermilab** [comment]
Supplemental —

`banana sushi -s30 -W512 -H512 -n1  -save_orig -embiggen 4 0.75 0.1 -I outputs/banana-sushi.png` executed in 1781 seconds (~30 min).

**Comment by travco** [comment]
Embiggen doesn't function like ESRGAN and it doesn't do the same, it's putting the image back though Img2Img in sections. Taking much longer than ESRGAN isn't just expected, it's basically guaranteed.
Also much like Img2Img, you probably want to specify a lower strength `-f 0.4` (default is all the way up at 0.75) so it preserves more of the original, that might also help you with the black square.
