### ISSUE TITLE
Setting up a Discord for Collab?

### ISSUE THREAD

**Issue by manzke** [lstein/stable-diffusion#591]
Hey guys, I'm following the project and promoting it across my network right. I see a lot of feature requests, work on the PRs, questions, bug reports etc.
**What do you think about setting up a discord server**, especially for the collab between the contributors. People tend to "chat" in the issues, which leads to a lot of noise and it is hard to concentrate on the real topics.

I'm happy to help with it. I know that right now we have thousands popping up, because they all use SD as their base. For me it is more about collab and not generating for people.

What do you think?

**Comment by hipsterusername** [comment]
Seems like a good move - common for many dev efforts these days.

**Comment by tildebyte** [comment]
Definite +1. I've been meaning to bring this up with @lstein, but I hadn't quite decided on a forum (but Discord is fine - my other thought was Slack).

**Comment by hipsterusername** [comment]
Discord just released forums so I think it ends up serving this groups purposes well, on many fronts.

**Comment by tildebyte** [comment]
> Discord just released forums 

Nice!

It's funny to me that "standard" Discord *supports* "threads" (like Slack), but NO ONE USES THEM. It's just everyone all talking at the same time. Welcome to irc 😁

**Comment by hipsterusername** [comment]
Based on interest, I put server together with a few common channels - It might facilitate some of the back/forth as work is done to get Web UI MVP out. Keeping most discussions pertaining to the repo **in** the repo is probably best practice.

https://discord.gg/htRgbc7e

CC: @lstein

**Comment by lstein** [comment]
Happy to give it a try, but personally I find Discord a bit chaotic. I’d prefer Slack.

**Comment by lstein** [comment]
Oh, thanks for doing that!  I’ll join the party.

**Comment by tildebyte** [comment]
> Happy to give it a try, but personally I find Discord a bit chaotic. I’d prefer Slack.

It will be a bit like herding cats, but I think if we can encourage people to use threads, we can keep it from becoming overwhelming

**Comment by manzke** [comment]
@lstein i prefer slack as well, but I thought it is the easier Opp for open source right now.
Slacks free model is ok, but you lose content after a while and it is cheaper to boost a discord server.

Let's give it a try. We can still switch. :)

@hipsterusername thx for setting it up
