### ISSUE TITLE
img2img confusion

### ISSUE THREAD

**Issue by Dartterious** [lstein/stable-diffusion#60]
Hi, me again with another low/no code brain. The instructions for img2img aren't clear. There was no file with int-images in the stable diffusion file so I assume I had to create it myself. Still couldn't make it work, so I assumed maybe the dimestions of the initial image had to be 512x512. So I cut it down to those dimetions. But I am still not understanding something here. 

Please help! I keep getting these errors. 
![2022-08-24 15_07_46-Anaconda Prompt (Anaconda3) - python  scripts_dream py](https://user-images.githubusercontent.com/109719059/186353818-5a02644c-67b7-42a0-a639-530cbab4be13.png)
![2022-08-24 15_07_35-Anaconda Prompt (Anaconda3) - python  scripts_dream py](https://user-images.githubusercontent.com/109719059/186353827-9b472997-c205-40af-9f5a-6ea978507d71.png)
![2022-08-24 15_07_18-Anaconda Prompt (Anaconda3) - python  scripts_dream py](https://user-images.githubusercontent.com/109719059/186353829-24e0a4f4-a899-47a8-a841-ccc820b6af4a.png)

**Comment by Dartterious** [comment]
> There is a space between your image and test. There should be no spaces. If your file name has spaces, then wrap the entire path inside quotes.
Thank you, however I now get the following issue:
![image](https://user-images.githubusercontent.com/109719059/186391045-6e7901fe-481c-4e94-9bcf-d29853f1c5bd.png)

**Comment by blessedcoolant** [comment]
Is there an image file called "imagetestt.png" in a folder called init-images which is located in the main folder?
Also remove the first backslash -- the one before init-images.

**Comment by Dartterious** [comment]
> Is there an image file called "imagetestt.png" in a folder called init-images which is located in the main folder? Also remove the first backslash -- the one before init-images.

There is yes. Still getting this issue.
![2022-08-24 18_24_51-Anaconda Prompt (Anaconda3)](https://user-images.githubusercontent.com/109719059/186395585-b0dabdb9-4c94-41a8-a631-77fee276b822.png)
![2022-08-24 18_21_40-init-images](https://user-images.githubusercontent.com/109719059/186395590-a069aeef-09b1-4948-89f9-69df03216c93.png)

**Comment by blessedcoolant** [comment]
Use this as your code.

`"a red robot playing computer games" -I "init-images/imagetestt.png" -f 0.5`

Exactly the same with the quotes.

**Comment by lstein** [comment]
I bet it will work if you use a forward slash in the rather than a backwards one.
