### ISSUE TITLE
The image comes out in green

### ISSUE THREAD

**Issue by OMGSAMUELRBR** [lstein/stable-diffusion#61]
Hello, good, I've been trying to get Stable Diffusion to work but I'm doing something wrong, the images come out green.

Example:

![000006 2470758828](https://user-images.githubusercontent.com/66468335/186377747-98e95c5e-fcf3-4bf5-94c7-7bde0bbab1df.png)

I have an NVIDIA GTX 1660 SUPER, could it be the graphics problem?

Thanks greetings

**Comment by neilmahaseth** [comment]
This is because the NVIDIA GTX 16X series do not have support for mixed precision. At present use [this fork](https://github.com/basujindal/stable-diffusion) with --precision full argument. Here is the Reddit post on the problem  [more detail](https://www.reddit.com/r/StableDiffusion/comments/wv90jv/installed_sd_locally_with_the_new_weights_but/)

**Comment by OMGSAMUELRBR** [comment]
Thanks

> This is because the NVIDIA GTX 16X series do not have support for mixed precision. At present use [this fork](https://github.com/basujindal/stable-diffusion) with --precision full argument. Here is the Reddit post on the problem [more detail](https://www.reddit.com/r/StableDiffusion/comments/wv90jv/installed_sd_locally_with_the_new_weights_but/)

**Comment by OMGSAMUELRBR** [comment]
But I have a problem now, when I say the instruction of what I want it to do, I get the following:


(ldm) E:\IA Stable Diffusion\stable-diffusion-main>python optimizedSD/optimized_img2img.py --prompt "A realistic image of a mouse sitting on a horse" --H 512 --W 512 --precision full
init_seed =  393717
Global seed set to 393717
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "optimizedSD/optimized_img2img.py", line 221, in <module>
    assert os.path.isfile(opt.init_img)
  File "C:\Users\samue\anaconda3\envs\ldm\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
