### ISSUE TITLE
Low VRAM Version for GPU Not Supporting Mixed Precision [Feature Request]

### ISSUE THREAD

**Issue by neilmahaseth** [lstein/stable-diffusion#62]
I love this fork of stable diffusion but can not run it. Like [this fork]( https://github.com/basujindal/stable-diffusion) can you please provide a low VRAM version for full_precision for GPU that does not support mixed precision? As it is not possible to run the script with low VRAM.

**Comment by tildebyte** [comment]
This would also be nice for people with enough VRAM for the existing code who want to play around with full precision... if the diff between here and basujindal isn't too crazy, it shouldn't be that hard.

**Comment by lstein** [comment]
There's been a lot of divergence from basujindal, but this feature request is definitely on the TODO list.
