### ISSUE TITLE
Load concept form Stable Diffusion concepts library

### ISSUE THREAD

**Issue by HugoSega** [lstein/stable-diffusion#620]
Hello everyone,
Is there a way to load concepts or what changes have to be made to be able to use them?

https://huggingface.co/sd-concepts-library

**Comment by smoke2007** [comment]
yes , start the dream.py script with the parameter

python3 ./scripts/dream.py --embedding_path /path/to/embedding.pt or .bin

**Comment by HugoSega** [comment]
Thank you very much
