### ISSUE TITLE
Global --outdir no longer works on development branch

### ISSUE THREAD

**Issue by db3000** [lstein/stable-diffusion#628]
**Describe your environment**
- GPU: RTX 3060
- VRAM: 12GB
- CPU arch: x86
- OS: Linux
- Python: python3.10
- Branch: development
- Commit: [run `git show` and paste the line that starts with "Merge" here]
```
commit 622db491b255d2ab4e15d930b20782c06b04c14b (HEAD -> development, origin/development)
Author: Lincoln Stein <lincoln.stein@gmail.com>
Date:   Fri Sep 16 18:25:43 2022 -0400

    change tensor length to 768 per #572
```

**Describe the bug**
`dream.py` takes a default `--outdir` but it no longer seems to be used. Passing `--outdir` to a single dream prompt works though

**To Reproduce**
```
$ python3 scripts/dream.py --outdir newdir
* Initializing, be patient...
...
dream> test -s1
....
Outputs:
[1] outputs/img-samples/000014.3211573219.png: "test -s 1 -W 512 -H 512 -C 7.5 -A k_lms -S 3211573219 -n 1 -f 0.75
```

**Expected behavior**
Output file should be in newdir, not in outputs/img-samples

**Comment by lstein** [comment]
Fixed. Thanks for reporting the bug.
