### ISSUE TITLE
--prompt_as_dir no longer functions as intended on development

### ISSUE THREAD

**Issue by maddavid123** [lstein/stable-diffusion#649]
**Describe your environment**
- GPU: CUDA
- VRAM: 12GB
- CPU arch: x86? idk
- OS: Windows
- Python: Anaconda
- Branch: development
- Commit: Everything after https://github.com/lstein/stable-diffusion/commit/403d02d94f467337666c155ca5b35e4ed7e6f03f

**Describe the bug**
--prompt_as_dir does not function as intend

**To Reproduce**

1. Check out https://github.com/lstein/stable-diffusion/commit/403d02d94f467337666c155ca5b35e4ed7e6f03f
2. launch python scripts/dream.py -p
3. dream> dream -s 10

**Expected behavior**
Images should generate into the subfolder dream.
Instead, they generate into the base folder.

**Additional context**
I ran a git bisect, and that's the commit that the error is introduced.
You can check out https://github.com/lstein/stable-diffusion/commit/45af30f3a4c98b50c755717831c5fff75a3a8b43 and run the same steps to reproduce, it works there.

**Comment by maddavid123** [comment]
Looks like https://github.com/lstein/stable-diffusion/blob/development/scripts/dream.py#L198 should be an if instead of elif?

`if opt.outdir` always seems to be true, meaning the `if opt.prompt_as_dir` is never firing. That's weird, because that's not actually something changing in the commit I specified. Only thing I can imagine is whether passing the data in via the introduced Args system changed things.

**Comment by lstein** [comment]
Thanks for the report. I'll take care of it.

**Comment by maddavid123** [comment]
Alright, got it.

So in versions before the erroneous one, https://github.com/lstein/stable-diffusion/blob/development/scripts/dream.py#L194 refers to the per-dream --outdir, as opposed to the original initialisation --outdir. 

It looks like after the commit, it's now using the original initialisation --outdir, which always has a default value. This results in the behaviour seen, where opt.prompt_as_dir never gets a chance to be reached.

It's a messy one.

**Comment by lstein** [comment]
Pull request #654 should fix this.

**Comment by maddavid123** [comment]
Closing with #654 being merged in.
Thanks for fixing!
