### ISSUE TITLE
Not able to dream anymore?

### ISSUE THREAD

**Issue by vekst** [lstein/stable-diffusion#67]
Everything was working fine last night, but I did a git pull this morning and suddenly I can't seem to get dream to work anymore. I run the dream.py script, but it just goes back to the ldm mode instead of running dream (so it seems, I'm not tech savvy whatsoever)

![77h8m](https://user-images.githubusercontent.com/20705525/186461892-8cf3294f-ef20-4813-b15c-c59a9c9f7b9f.png)

**Comment by lendrick** [comment]
Pull again.  I was having this issue and the most recent commit fixed it.

**Comment by vekst** [comment]
Thanks, that fixed it! Guess I pulled at a bad time lmao.
