### ISSUE TITLE
Current implementation of RFC #587 incorrect

### ISSUE THREAD

**Issue by psychedelicious** [lstein/stable-diffusion#686]
In #587, the metadata RFC is partially implemented but is incorrect. It always writes a key `images` with value an array of image metadata, even if the generation was not a grid.

Per the RFC:
> and then also one of the following two fields, depending on whether this is a grid:
>
>    image: an object in one of the formats specified below
>    images: an array of such objects

**Comment by psychedelicious** [comment]
I intended to set the branch's upstream to my own fork but had it set to this repo instead and pushed that branch, oops. I'll keep that in mind next time.

Please let me know if I've messed up anything else.

**Comment by psychedelicious** [comment]
Resolved by #688

**Comment by lstein** [comment]
I've accepted the PR, but I think this is a place where the RFC needs to change. (@Kyle0654 suggested the same in a comment).  It makes sense to me to have a single tag that I can look at and infer whether it is a single image or multiple images by counting the elements of the array. The same reason that we have a single "prompt" tag that is an array of len > 1 for weighted subprompts and an array of len one  for a single prompt.

**Comment by psychedelicious** [comment]
My PR didn't update `metadata_loads()` - I need to fix that!

IMO the RFC should not have 'grid', it should be a for a single image. I believe this is what @Kyle0654  was suggesting. It's a metadata spec for a single image generated by SD + whatever other postprocessing methods. "image grid" is not a concept the metadata spec needs to have

**Comment by lstein** [comment]
I was just thinking to check whether you'd made the change. I think the PR I just proposed for direct post processing of PNG images will break now. But that's OK. I've converted it to a draft and am working with @blessedcoolant on a newer and better version.

Very annoyingly, I cannot find the RFC in Discussions any longer. I've been searching, and wonder if someone closed it. Am I just going blind?

**Comment by psychedelicious** [comment]
@lstein I updated fix-metadata-rfc branch with a simple fix. But I'm not sure what else could be affected. 

I clicked Revert on my PR thinking it would let me choose what to do before it did anything, but it's gone and made a new branch. 

I'd prefer if I don't have access to this repo, concerned I'm going to blow something up. Happy to just make PRs until I do some more reading on git/github and feel comfortable being close to scary buttons. Can you please remove me?

**Comment by lstein** [comment]
Not a problem. I'll remove your access. There's almost nothing you can do that can't be undone. If you simply created an unwanted branch, I can just go ahead and delete it.

**Comment by psychedelicious** [comment]
Yeah, it's the "almost" that has me worried. Heh. Thanks.

**Comment by lstein** [comment]
That's why we tell people that the development branch is unstable and caveat emptor.
