### ISSUE TITLE
Latest release breaks img2img

### ISSUE THREAD

**Issue by Oceanswave** [lstein/stable-diffusion#69]
On CUDA enabled devices, attempting to execute img2img results in:

```
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_gather)
```

Investigating...

**Comment by lstein** [comment]
Thanks for the report. Looking into it.

**Comment by Oceanswave** [comment]
The check in ddim/plms that ensures the device is on cuda that was removed in the PR is the cause of the regression... guess this needs to be here, just needs an additional check

**Comment by lstein** [comment]
Thanks, I've backed out the changes to ddims. Since plms sampler is not currently used in img2img, I have kept the PR changes to plms.py.
