### ISSUE TITLE
Does anyone want to keep the grid option?

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#73]
I'm considering removing support for the grid option from the next version. Is anybody using it?

**Comment by vekst** [comment]
Haven't used it a single time so far, doubt I will in the future either.

**Comment by MarcusLlewellyn** [comment]
Yeah, this was useful in Discord to keep things tidy. Now that I can run this locally I really haven't needed it.

**Comment by warner-benjamin** [comment]
I find the grid option useful

**Comment by lstein** [comment]
Ummmm, does thumbs down mean "get rid of grid" or "I hate this idea, keep it"?

**Comment by codedealer** [comment]
I personally meant it as "get rid of". Never used it.

**Comment by BlueAmulet** [comment]
I have never used the grid, before this fork always used --skip_grid

**Comment by slix** [comment]
If friends ask for a prompt I copy a 3x4 grid to Discord. I can't imagine doing that for 12 separate images.

The programmer side of me thinks the grid is nonsense because the "correct" representation is 1 image per file. But without it I can't easily show a bunch of outputs to someone who's interested.

**Comment by Fuzzeee** [comment]
I regularly use the grid feature, it'd be pretty easy to find an alternative I imagine, but it'd still be annoying if it was ditched.

**Comment by bmaltais** [comment]
No use for it

**Comment by 1blackbar** [comment]
i was using it on discord just to get moreimages at once , now i dont have to hurry so id say not needed

**Comment by lendrick** [comment]
I use it from time to time just to be able to show people a bunch of images easily.  If it's taking time to maintain, though, I wouldn't miss it very much.

**Comment by softyoda** [comment]
I think it would be cool to allow this feature to be present in another script, if you refactor your code, maybe include this grouping option as a [group_img(list_img)] function called on image list.

**Comment by morganavr** [comment]
I do not use grid option and don't like it. I would remove it.

**Comment by Cubox** [comment]
I actually use it so much, I edited the script to use it by default

**Comment by lkewis** [comment]
Use it all the time personally even though I didn't with the dreambot until it was enforced

**Comment by lstein** [comment]
I've left the grid option in. After reorganizing the code it was straightforward (prior to this there were a zillion "if not grid" statements). Thanks everyone for weighing in!
