### ISSUE TITLE
Processing a list of prompts from a file

### ISSUE THREAD

**Issue by oppie85** [lstein/stable-diffusion#82]
I don't know if this is already on the roadmap, if it has been suggested before, or maybe it's even already possible (if so, apologies) but one feature I'd like to see is the possibility to load a list of prompts from a text file and have them processed in sequence. I imagine this could just be a text file with each line being a "dream prompt". This would be very useful when trying to generate a lot of images with slight prompt variations.

**Comment by softyoda** [comment]
I think that invoking the dream.py from another batching.py could be a solution to easily script, batch process prompts for small variation, execute in painting or image enlargement using stripes technics, automate image2image processing.

Is there style to style (without prompt) feature to stable-diffusion?

**Comment by codedealer** [comment]
It can already do that. Run the script with from_file argument like so
```
python scripts/dream.py --from_file="path/to/file"
```

**Comment by lstein** [comment]
I've added instructions to the README documentation. Thanks for bringing it up!
