### ISSUE TITLE
Include GFPGAN

### ISSUE THREAD

**Issue by carterworks** [lstein/stable-diffusion#87]
I understand that it might require an extra installation step (another model to install), but I think it would benefit people to have a flag that runs the result through [GFPGAN](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth) to include the face quality. There are a few other interfaces for Stable Diffusion that include GFPGAN, like

- [hlky/stable-diffusion-webui](https://github.com/hlky/stable-diffusion-webui)
- [mallorbc/stable-diffusion-klms-gui](https://github.com/mallorbc/stable-diffusion-klms-gui/blob/main/scripts/web_gui.py)

A flag like this

```python
parser.add_argument(
  '-G',
  '--gfpgan_strength',
  default=0.0,
  type=float,
  help="The strength at which to apply the GFPGAN model to the result, in order to improve faces."
)
```

Maybe after you commit the refactor, I'll try to submit a PR.

**Comment by Oceanswave** [comment]
This is great - I didn't realize that some of the other forks already have this built in. "What a time to be alive"

**Comment by 1blackbar** [comment]
keep in mind that storing gfpgan model in memory will limit your sizes in Sdiffusion

**Comment by carterworks** [comment]
> keep in mind that storing gfpgan model in memory will limit your sizes in Sdiffusion with systems that have less than 20GB

That's a good point - I didn't think about that.
