### ISSUE TITLE
Low quality results

### ISSUE THREAD

**Issue by DrakeFruit** [lstein/stable-diffusion#9]
my test prompt was car -W 256 -H 256 -n 2 -s 50 -S 10 but the results I get are horrible quality, whats wrong here?

![00000](https://user-images.githubusercontent.com/94070205/185725387-9fb329b1-b712-465a-b90f-4e15244a2f00.png)
![00001](https://user-images.githubusercontent.com/94070205/185725388-39788843-606e-4da8-a958-265a82bb8b3e.png)

**Comment by xraxra** [comment]
> my test prompt was car -W 256 -H 256 -n 2 -s 50 -S 10 but the results I get are horrible quality, whats wrong here?

you need one dimension (W or H) to be at least 512 or higher

**Comment by DrakeFruit** [comment]
I immediately run out of vram on a 2060 super if I try that

**Comment by DrakeFruit** [comment]
got it to run but the results still suc
![00002](https://user-images.githubusercontent.com/94070205/185731917-432977c1-aa85-494a-8f05-022b0551cde0.png)

k

**Comment by 1blackbar** [comment]
test same prompt on discord and post if you want... we cant really tell, without side by side comparison

**Comment by lstein** [comment]
Which weights file are you using, LAION400m or stable-diffusion-v1? Low quality is expected with the former.

**Comment by 1blackbar** [comment]
v1.3 that are about 8gb , but the thing with SD weights is they released model that looks worse than even first version of the bot from discord.
Now they alsoswapped to worse version for 2 days and a lot of people noticed, they might release new version that might not look as good as their own used in dreamstudio.We will see. For now  my results are fine with 1.3 but not as good as the ones from bot.
Also i recommended your repo fon SD discord channel to people who want discord bot experience back, they shut down all the bots today.

**Comment by DrakeFruit** [comment]
> Which weights file are you using, LAION400m or stable-diffusion-v1? Low quality is expected with the former.

IM using v1, the 7gb file

**Comment by lstein** [comment]
At the dream> command you can include the option -I/path/to/file.png (that's a "dash-eye") and it will modify the image like img2img. The --strength (or -f) option lets you balance how aggressively to modify the image - 0.0 keeps the original; 1.0 ignores the original completely.

I am thinking that the difference in quality is due to the latent diffusion source code using plms and ddim sampling, and not k_lms as the Discord bot used. I do have examples of  k_lms  implementations and am planning to fold it in.

**Comment by DrakeFruit** [comment]
I guess I got the leaked one, I thought it was a pre-release or something haha
