### ISSUE TITLE
BEWARE: current main may break

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#92]
I've just refactored a lot of the code and things have been moved around. I have tested the core functionality, but there may be edge cases that break. The version tagged version-1.10 should be stable, and you should use that until full testing on main is complete.

**Comment by Ratinod** [comment]
For me "version-1.10" shows a strange error:
`* Initializing, be patient...

Traceback (most recent call last):
  File "scripts\dream.py", line 428, in <module>
    main()
  File "scripts\dream.py", line 55, in main
    t2i = T2I(width=width,
TypeError: __init__() got an unexpected keyword argument 'embedding_path'
`
How do I properly "update" to the new version?

**Comment by csunberry** [comment]
I'm having the exact same issue. "Embedding path."

Traceback (most recent call last):
  File "scripts/dream.py", line 289, in <module>
    main()
  File "scripts/dream.py", line 43, in main
    t2i = T2I(width=width,
TypeError: __init__() got an unexpected keyword argument 'embedding_path'

**Comment by yunsaki** [comment]
@Ratinod @csunberry Besides updating the repo you might need to do a `pip install -e .`. This error occurs due to the version of ldm/simplet2i.py installed on your guys' systems being incompatible with the current version of scripts/dream.py.

**Comment by yunsaki** [comment]
@lstein Listing the repo itself as a dependency and installing (which the base repo introduced) it is not a great idea imo. Maybe doing `sys.path.append("..")` in dream.py could replace that? I didn't test whether that works though.

**Comment by tildebyte** [comment]
@lstein; Will you PTAL @ https://github.com/lstein/stable-diffusion/discussions/76 ?

**Comment by lstein** [comment]
Are you guys running "conda env update -f environment.yaml" ? It ends with a line that is supposed to run "pip install -e ."  This wasn't my design decision - it was like that in the base.

I've played with adding sys.path.append('.') and sys.path.append('..') in the main script, but this seems to have different effects on different platforms. I'm a novice python programmer (old time C, java and perl programmer) and it shows. So any advice on how to package this right will be taken with great gratitude.

**Comment by yunsaki** [comment]
@lstein For now I think it should be specified that you should update your conda env after updating the repo and that *in a well visible place* (like as a first section in the readme).

**Comment by Ratinod** [comment]
Ok. "conda env update -f environment.yaml" just stuck on "Installing pip dependencies: \" (more than 40 minutes)
But "pip install -e ." solves the problem.

**Comment by csunberry** [comment]
> 

I was able to update the env, and I have used pip install -e previously, but now, when I use that, it just spits out some weird...error about requiring 1 argument.

Also, the dream web server works fine. 

@lstein Thank you, too. I did update the environment and it downloaded something. Still the same error but hey, the web dream server works.

**Comment by yunsaki** [comment]
@csunberry it needs an argument. The `.` is important, it basically means "current directory". So `pip install -e .` installs the current directory as a package,

**Comment by csunberry** [comment]
> @csunberry it needs an argument. The `.` is important, it basically means "current directory". So `pip install -e .` installs the current directory as a package.

Omg. I knew I was missing something but my thick skull couldn't recall what I was missing. 

Good heavens, I should stop while I'm ahead. I should be glad my head is even on!

Thank you!!

**Comment by tildebyte** [comment]
FTR: `pip install -e .` "installs" the current directory (assuming that it's something which 'pip' can understand) in "developer mode".

This means that the repo *acts* as though it were fully installed into the system (or virtual environment, or whatever), but it is actually still "live", so that any changes you make to any files in the repo are used immediately (obviously anything which is running must be restarted).

IOW, if you make local changes, or sync new changes from master, you *shouldn't* have to re-pip.

What's happened here recently was the business involving dependencies moving from being installed *in the repo*, to being submodules, to being normal pip-installed dependencies. THOSE kinds of changes will *definitely* break things 😁

**Comment by csunberry** [comment]
> What's happened here recently was the business involving dependencies moving from being installed _in the repo_, to being submodules, to being normal pip-installed dependencies. THOSE kinds of changes will _definitely_ break things 😁

And broken, twas it. Makes sense.

"Requirement already satisfied: torch in c:\users\sun\anaconda3\envs\ldm\lib\site-packages (from latent-diffusion==0.0.1) (1.11.0)
Requirement already satisfied: numpy in c:\users\sun\anaconda3\envs\ldm\lib\site-packages (from latent-diffusion==0.0.1) (1.23.2)
Requirement already satisfied: tqdm in c:\users\sun\anaconda3\envs\ldm\lib\site-packages (from latent-diffusion==0.0.1) (4.64.0)
Requirement already satisfied: typing_extensions in c:\users\sun\anaconda3\envs\ldm\lib\site-packages (from torch->latent-diffusion==0.0.1) (4.3.0)
Requirement already satisfied: colorama in c:\users\sun\anaconda3\envs\ldm\lib\site-packages (from tqdm->latent-diffusion==0.0.1) (0.4.5)
Installing collected packages: latent-diffusion
  Attempting uninstall: latent-diffusion
    Found existing installation: latent-diffusion 0.0.1
    Uninstalling latent-diffusion-0.0.1:
      Successfully uninstalled latent-diffusion-0.0.1
  Running setup.py develop for latent-diffusion
Successfully installed latent-diffusion"

And break. Broken. Not installed. So many things of randomly not installed somehow. It's like a game. A game of finding what didn't install. 

Unfortunately....still having the embedding path. Hm.

**Comment by tildebyte** [comment]
@csunberry; Have you tried doing a `git pull` recently?

**Comment by csunberry** [comment]
> @csunberry; Have you tried doing a `git pull` recently?

I sure did!

**Comment by tildebyte** [comment]
@csunberry; If you're up for acting as a test subject, I have a [gist][] with much simplified Windows installation instructions.

You **will** need to remove all conda environments, delete your existing repo clone, uninstall Miniconda/Anaconda (and possibly other things I can't think of right now...) - you want as much of a blank slate as you can get.

[gist]: https://gist.github.com/tildebyte/792e815f1f8b473f7e62cb4fa099c4f9
